/***************************************************************************************
Sub Program	: DEAL_ERROR_INPUTS
Main		: ERROR_CHECK
Purpose		: Inputs needed to run MASTER_ERROR_CHECK in each job & sub-program
Programmer  : Spencer Hopkins, JUSTIN HUBBARD
****************************************************************************************/

* INCLUDE MASTER_ERROR_CHECK PROGRAM;
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SAS MACRO\MASTER_ERROR_CHECK.SAS";

/*
============================================================================= 
     INPUTS & SETUP
=============================================================================
*/

* NAME OF PROGRAM/JOB;
%LET JOB = DEAL DATAMART;

* NAME(S) OF SUB PROGRAMS INCLUDED IN JOB;
%LET SUB1 = EADV INPUT;
%LET SUB2 = QF1_QF2 INPUT;
%LET SUB3 = QF1 TITLE INPUT;
%LET SUB4 = QF3 TXTITLE INPUT;
%LET SUB5 = QF3 TETL INPUT;
%LET SUB6 = QF3 TTOC INPUT;
%LET SUB7 = QF3 FAI INPUT;
%LET SUB8 = QF4 TLP INPUT;
%LET SUB9 = QF4 PDL INPUT;
%LET SUB10 = QF5 ILP INPUT;
%LET SUB11 = QF5 PDL INPUT;
%LET SUB12 = QF5 TLP INPUT;
%LET SUB13 = NG INPUT;
%LET SUB14 = ONLINE INPUT;
%LET SUB15 = LOC INPUT;
%LET SUB31 = FUSE INPUT;

/*UPLOAD STEPS*/
%LET SUB16 = UPLOAD_EADV;
%LET SUB17 = UPLOAD_QF1_QF2;
%LET SUB18 = UPLOAD_QF1T;
%LET SUB19 = UPLOAD_QF3TXTITLE;
%LET SUB20 = UPLOAD_QF3TETL;
%LET SUB21 = UPLOAD_QF3TTOC;
%LET SUB22 = UPLOAD_QF3FAI;
%LET SUB23 = UPLOAD_QF4TLP;
%LET SUB24 = UPLOAD_QF4PDL;
%LET SUB25 = UPLOAD_QF5ILP;
%LET SUB26 = UPLOAD_QF5PDL;
%LET SUB27 = UPLOAD_QF5TLP;
%LET SUB28 = UPLOAD_NG;
%LET SUB29 = UPLOAD_ONLINE;
%LET SUB30 = UPLOAD_LOC;


* NAME OF TEMP ERROR TABLE;
%LET TEMP_TBL = DEAL_TEMP_ERROR;

* PEOPLE WHO NEED TO RECEIVE ERROR EMAIL;
%LET PPL_TO_EMAIL = 'SHOPKINS@ADVANCEAMERICA.NET','JHUBBARD@ADVANCEAMERICA.NET','JROSE@ADVANCEAMERICA.NET','RMUGABE@ADVANCEAMERICA.NET','ADOBBINS@ADVANCEAMERICA.NET';

