%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";

LIBNAME BIOR ORACLE
	USER=&USER
	PASSWORD=&PASSWORD
	PATH=BIOR
	SCHEMA=BIOR;

LIBNAME EDW ORACLE
	USER=&USER
	PASSWORD=&PASSWORD
	PATH=EDWPRD
	SCHEMA=EDW;

/* DOWNLOAD DEAL SUMMARY */
DATA WORK.LOCAL_ODESA;
	SET BIOR.O_DEAL_SUMMARY_ALL;
RUN;

/* DOWNLOAD D_LOCATION */
DATA WORK.LOCAL_D_LOCATION;
	SET EDW.D_LOCATION;
RUN;

/* D_LOCATION REFRESH HERE */
PROC SQL;
	CREATE TABLE WORK.DEAL_LOC_UPDATE AS
	SELECT
		 BIOR.PRODUCT
		,BIOR.POS
		,BIOR.INSTANCE
		,BIOR.BRANDCD
		,BIOR.BANKMODEL
		,CASE WHEN LOC.CTRY_CD = '' THEN BIOR.COUNTRYCD ELSE LOC.CTRY_CD END AS COUNTRYCD
		,CASE WHEN LOC.ST_PVC_CD = '' THEN BIOR.STATE ELSE LOC.ST_PVC_CD END AS STATE
		,LOC.ADR_CITY_NM AS CITY
		,LOC.MAIL_CD AS ZIP
		,CASE WHEN LOC.HIER_ZONE_NBR = . THEN BIOR.ZONENBR ELSE LOC.HIER_ZONE_NBR END AS ZONENBR
		,LOC.HIER_ZONE_NM AS ZONENAME
		,CASE WHEN LOC.HIER_RGN_NBR = . THEN BIOR.REGIONNBR ELSE LOC.HIER_RGN_NBR END AS REGIONNBR
		,LOC.HIER_RDO_NM AS REGIONRDO
		,CASE WHEN LOC.HIER_DIV_NBR = . THEN BIOR.DIVISIONNBR ELSE LOC.HIER_DIV_NBR END AS DIVISIONNBR
		,LOC.HIER_DDO_NM AS DIVISIONDDO
		,COMPRESS(PUT(CASE WHEN LOC.BUSN_UNIT_ID = . THEN INPUT(BIOR.BUSINESS_UNIT,BEST32.) ELSE LOC.BUSN_UNIT_ID END,32.)) AS BUSINESS_UNIT
		,BIOR.LOCNBR
		,LOC.OPEN_DT AS LOC_OPEN_DT
		,LOC.CLS_DT AS LOC_CLOSE_DT
		,BIOR.DEAL_DT
		,BIOR.DEAL_DTTM
		,BIOR.LAST_REPORT_DT
		,BIOR.DEALNBR
		,BIOR.TITLE_DEALNBR
		,BIOR.CUSTNBR
		,BIOR.SSN
		,BIOR.ADVAMT
		,BIOR.FEEAMT
		,BIOR.NSFFEEAMT
		,BIOR.LATEFEEAMT
		,BIOR.OTHERFEEAMT
		,BIOR.WAIVEDFEEAMT
		,BIOR.REBATEAMT
		,BIOR.COUPONAMT
		,BIOR.TOTALPAID
		,BIOR.TOTALOWED
		,BIOR.CONSECUTIVEDEALFLG
		,BIOR.CASHAGNCNT
		,BIOR.DUEDT
		,BIOR.DEALENDDT
		,BIOR.WRITEOFFDT
		,BIOR.DEPOSITDT
		,BIOR.DEFAULTDT
		,BIOR.CUST_STATUS
		,BIOR.CHECKSTATUSCD
		,BIOR.DEALSTATUSCD
		,BIOR.ACHSTATUSCD
		,BIOR.RETURNREASONCD
		,BIOR.COLLATERAL_TYPE
		,BIOR.CUSTCHECKNBR
		,BIOR.ETLDT
		,BIOR.PREVDEALNBR
		,BIOR.PRODUCTCD
		,BIOR.INTERESTFEE
		,BIOR.ACHAUTHFLG
		,BIOR.UPDATEDT
		,BIOR.OUTSTANDING_DRAW_AMT
		,BIOR.UNDER_COLLATERALIZED
	FROM WORK.LOCAL_ODESA BIOR
	LEFT JOIN
	WORK.LOCAL_D_LOCATION LOC
	ON(BIOR.LOCNBR=LOC.LOC_NBR)
;
QUIT;

/*--------------------------------------------------------*/
/* DROP AND REFRESH BIOR WITH UPDATED LOCATION DIMENSIONS */
/*--------------------------------------------------------*/

PROC SQL;
	CONNECT TO ORACLE(USER=&USER PASSWORD=&PASSWORD PATH=BIOR);
	EXECUTE(TRUNCATE TABLE BIOR.O_DEAL_SUMMARY_ALL) BY ORACLE;
	DISCONNECT FROM ORACLE;
;
QUIT;

/* BULK LOAD DEAL SUMMARY */
PROC SQL;
	INSERT INTO BIOR.O_DEAL_SUMMARY_ALL (BULKLOAD=YES BL_DELETE_FILES=YES BL_DEFAULT_DIR ="E:\SHARED\CADA\SAS DATA\USER\BULKLOAD\")
	SELECT * FROM WORK.DEAL_LOC_UPDATE;
RUN;

/* ADD GRANTS, PRIMARY KEY, AND INDEXES */
/*PROC SQL;*/
/*  CREATE SELECT GRANTS  */

/*	CONNECT TO ORACLE (USER=&USER PASSWORD=&PASSWORD PATH=BIOR);*/
/*	EXECUTE(GRANT SELECT ON BIOR.O_DEAL_SUMMARY_ALL TO BIOR_SELECT_ONLY) BY ORACLE;*/
/*	DISCONNECT FROM ORACLE;*/

/*	CREATE INDICES */

/*	CONNECT TO ORACLE (USER=&USER PASSWORD=&PASSWORD PATH=BIOR);*/

/*  PRIMARY KEY  */
/*	EXECUTE (CREATE UNIQUE INDEX IDX_DEAL_SUM_PK ON BIOR.O_DEAL_SUMMARY_ALL (INSTANCE,DEALNBR,TITLE_DEALNBR) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  SSN  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_ALL_SSN ON BIOR.O_DEAL_SUMMARY_ALL (SSN) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  DEAL NUMBER  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_DEALNBR ON BIOR.O_DEAL_SUMMARY_ALL (DEALNBR) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  LOCATION NUMBER  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_LOCNBR ON BIOR.O_DEAL_SUMMARY_ALL (LOCNBR) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  DEAL DATE  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_DT ON BIOR.O_DEAL_SUMMARY_ALL (DEAL_DT) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  CUSTNBR  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_CUSTNBR ON BIOR.O_DEAL_SUMMARY_ALL (CUSTNBR) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  DUE DATE  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_DUEDT ON BIOR.O_DEAL_SUMMARY_ALL (DUEDT) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  PRODUCT/STATE INDEX  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_PRODST ON BIOR.O_DEAL_SUMMARY_ALL (PRODUCT, STATE) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  SSN/INSTANCE/DEAL_DT  */
/*	EXECUTE (CREATE INDEX IDX_DEAL_SUM_SSNINSTDT ON BIOR.O_DEAL_SUMMARY_ALL (SSN, INSTANCE, DEAL_DT) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*  STATE  */
/*	EXECUTE (CREATE INDEX IDS_DEAL_SUM_ST ON BIOR.O_DEAL_SUMMARY_ALL (STATE) TABLESPACE FINOR_TBL9_INDEX) BY ORACLE;*/
/*	DISCONNECT FROM ORACLE;  */


/*  CREATE CONSTRAINT FOR PK  */
/*	CONNECT TO ORACLE (USER=&USER PASSWORD=&PASSWORD PATH=BIOR) ;*/
/*	EXECUTE (ALTER TABLE BIOR.O_DEAL_SUMMARY_ALL ADD (CONSTRAINT IDX_O_DEAL_SUM_ALL_PK */
/*			 PRIMARY KEY (INSTANCE, DEALNBR, TITLE_DEALNBR) */
/*		     USING INDEX SVC_SASUSER.IDX_DEAL_SUM_PK ENABLE VALIDATE)) BY ORACLE;*/
/*	DISCONNECT FROM ORACLE;  */
/*QUIT;*/