/*EADV*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_EADV
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_EADV
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_EADV ON SKYNET.DEALSUM_DATAMART_EADV(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------QF12-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF1QF2
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF1QF2
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF12 ON SKYNET.DEALSUM_DATAMART_QF1QF2(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------QF1T----------------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF1T
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF1T
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QFT ON SKYNET.DEALSUM_DATAMART_QF1T(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------QF3TXTITLE-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF3TXTITLE
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF3TXTITLE
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF3TX ON SKYNET.DEALSUM_DATAMART_QF3TXTITLE(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------QF3_TETL-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF3TETL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF3TETL
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF3TETL ON SKYNET.DEALSUM_DATAMART_QF3TETL(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------QF3_TOTC-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF3TTOC
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF3TTOC
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF3TTOC ON SKYNET.DEALSUM_DATAMART_QF3TTOC(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------QF3_FAI-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF3FAI
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF3FAI
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF3FAI ON SKYNET.DEALSUM_DATAMART_QF3FAI(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------QF4_TLP-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF4TLP
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF4TLP
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF4TLP ON SKYNET.DEALSUM_DATAMART_QF4TLP(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------QF4_PDL-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF4PDL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF4PDL
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF4PDL ON SKYNET.DEALSUM_DATAMART_QF4PDL(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------OHCSO_ILP-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF5ILP
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF5ILP
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF5ILP ON SKYNET.DEALSUM_DATAMART_QF5ILP(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------OHCSO_PDL-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF5PDL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF5PDL
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF5PDL ON SKYNET.DEALSUM_DATAMART_QF5PDL(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------OHCSO_TLP-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_QF5TLP
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_QF5TLP
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_QF5TLP ON SKYNET.DEALSUM_DATAMART_QF5TLP(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------NG-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_NG
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_NG
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_NG ON SKYNET.DEALSUM_DATAMART_NG(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*-------------------ONLINE-----------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_OL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_OL
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_ONE_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TWO_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(STATE,INSTANCE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_THR_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FOU_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_FIV_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SIX_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(DUEDT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_SEV_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(LOCNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_EIG_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_NIN_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(PRODUCT,STATE)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TEN_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(SSN,INSTANCE,DEAL_DT)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_ELE_DES_OL ON SKYNET.DEALSUM_DATAMART_OL(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*-------------------LOC--------------------------*/

PROC SQL;
	DROP TABLE SKY.DEALSUM_DATAMART_LOC
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DEALSUM_DATAMART_LOC
	LIKE TMP_TBLS.UNION_TABLE
;
QUIT;

OPTIONS NOXWAIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
/*	EXECUTE(CREATE INDEX IDX_O_ONE_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(STATE)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TWO_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(STATE,INSTANCE)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_THR_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(CUSTNBR)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_FOU_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(DEALNBR)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_FIV_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(DEAL_DT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_SIX_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(DUEDT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_SEV_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(LOCNBR)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_EIG_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(INSTANCE,DEALNBR,TITLE_DEALNBR)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_NIN_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(PRODUCT,STATE)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TEN_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(SSN,INSTANCE,DEAL_DT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_ELE_DES_LOC ON SKYNET.DEALSUM_DATAMART_LOC(SSN)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_ONE_TRANSP ON BIOR.O_DEAL_SUMMARY_ALL(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
	EXECUTE(CREATE INDEX IDX_O_DSC_DEAL ON BIOR.O_DEAL_SUMMARY_ALL(DEALSTATUSCD)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUSTNBR_DEAL ON BIOR.O_DEAL_SUMMARY_ALL(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUSTFN ON BIOR.O_CUSTOMER_ALL(UPPER(FIRSTNM))) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUSTLN ON BIOR.O_CUSTOMER_ALL(UPPER(LASTNM))) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;




