/*--------------------------TRUNCATE STAGING TABLES--------------------------


	PURPOSE OF THIS PROGRAM IS TRUNCATE THE DEAL SUMMARY STAGING TABLES
	BEFORE THE DAYS RUN. THIS TRUNCATION WILL OCCUR AT THE START OF THE
	DATAMART DRIVER


-------------------------------------------------------------------------------*/

/*EADV*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_EADV) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF1QF2*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF1QF2) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF1TITLE*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF1T) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF3TXTITLE*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF3TXTITLE) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*TETL*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF3TETL) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*TTOC*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF3TTOC) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*FAI*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF3FAI) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF4TLP*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF4TLP) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF4PDL*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF4PDL) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF5ILP*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF5ILP) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF5PDL*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF5PDL) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF5TLP*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_QF5TLP) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*NG*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_NG) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*ONLINE*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_OL) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*ONLINE*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DEALSUM_DATAMART_LOC) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;