*WRITES THE DAILY BALANCE FILE AND CREATES A NEW FILE FOR EACH TRANCHE. EACH FILE ENDS WITH ITS RESPECTIVE TRANCHE NUMBER;
%MACRO BALANCE_FILE();
%LET J=1;
%LET VALS=&T_ID_BAL;
%PUT &VALS;
%LET DIR = &FILEPATH;
%DO %WHILE(%SCAN(&VALS,&J) NE );
  %LET I=%SCAN(&VALS, &J);
	%DO;
	%IF &X = &I %THEN %DO;
		DATA HEADER_TRANS;
			NUMBER_TRANCHE = "&I";
			COMPANY_NAME = "ADVANCE AMERICA";
			COUNTRY_SHORT = "USA";
			FULL_AMOUNT_OFFERED = &AMTOFFERED;
			PRODUCT_NUMBER = 10000+&I;
			FORMAT FULL_AMOUNT_OFFERED COMMA25.2;
			CALL SYMPUTX('FILENAME_TRANS',CAT("AAB",COMPRESS(((&RUNDATE_USE))),"&I"),'G');
		RUN;
		TITLE;
		ODS CSVALL FILE="&FILEPATH.\&FILENAME_TRANS..CSV";
	%END;
	%ELSE %DO;
		DATA HEADER_TRANS;
			NUMBER_TRANCHE = "&I";
			COMPANY_NAME = "ADVANCE AMERICA";
			COUNTRY_SHORT = "USA";
			FULL_AMOUNT_OFFERED = 0;
			PRODUCT_NUMBER = 10000+&I;
			FORMAT FULL_AMOUNT_OFFERED COMMA25.2;
			CALL SYMPUTX('FILENAME_TRANS',CAT("AAB",COMPRESS(((&RUNDATE_USE))),"&I"),'G');
		RUN;
		TITLE;
		ODS CSVALL FILE="&FILEPATH.\&FILENAME_TRANS..CSV";
	%END;
		
		PROC PRINT DATA=HEADER_TRANS NOOBS; 
		RUN;
		PROC PRINT DATA=TRANS_SFTP_LAYOUT NOOBS;
			VAR SECURITYITEMNUMBER SECURITYITEMTYPEID SECURITYITEMSOURCEID SECURITYITEMOPERATIONTYPEID PAIDAMOUNT CURRENTAMOUNT OPERATIONDATE APPLICATIONDATE;
			WHERE TRANCHE_ID = &I;
		RUN;
	ODS CSVALL CLOSE;

	%END;
  %LET J=%EVAL(&J+1);
%END;
%MEND;
%BALANCE_FILE()


/*EMAIL WHEN FINISHED*/
/*OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;*/
/*FILENAME MYMAIL EMAIL; */
/*DATA _NULL_;*/
/*   FILE MYMAIL*/
/*		TO=('JHUBBARD@ADVANCEAMERICA.NET','JHAMES@ADVANCEAMERICA.NET','JROSE@ADVANCEAMERICA.NET')*/
/*	    FROM='SECURITIZATION_FILES@COMPLETE.COM'*/
/*		SUBJECT="WEEKLY PURCHASE FILES FOR MEX";*/
/*		PUT "THE WEEKLY PURCHASE FILES HAVE BEEN WRITTEN TO THE SFTP TRANSFER SITE." /;*/
/*		PUT "TOTAL BORRORINGS FOR THIS WEEK: $&AMTOFFEREDTXT..";*/
/*RUN;*/