/*SFTP LAYOUT*/
PROC SQL;
	CREATE TABLE SFTP_LAYOUT AS
	SELECT *
	FROM SFTP_LAYOUT_EAPROD1
	UNION ALL CORR
	SELECT *
	FROM SFTP_LAYOUT_NG
	UNION ALL CORR
	SELECT *
	FROM SFTP_LAYOUT_AANET
;
QUIT;

/*TRANS SFTP LAYOUT*/
PROC SQL;
	CREATE TABLE TRANS_SFTP_LAYOUT AS
	SELECT *
	FROM TRANS_SFTP_LAYOUT_EAPROD1
	UNION ALL CORR
	SELECT *
	FROM TRANS_SFTP_LAYOUT_NG
	UNION ALL CORR
	SELECT *
	FROM TRANS_SFTP_LAYOUT_AANET
	ORDER BY SECURITYITEMNUMBER
			,TRANDT
;
QUIT;

/*DEAL LEVEL INFO*/
PROC SQL;
	CREATE TABLE DEAL_LVL_INFO AS
	SELECT *
	FROM DEALSUM_SECUR_EAPROD1
	UNION ALL CORR
	SELECT *
	FROM DEALSUM_SECUR_NG
	UNION ALL CORR
	SELECT *
	FROM DEALSUM_SECUR_AANET

;
QUIT;

/*PAYWEEK DEALS*/
PROC SQL;
	CREATE TABLE PAYWEEK_DEALS AS
	SELECT *
	FROM PAYWEEK_FOR_DEALS_EAPROD1
	UNION ALL CORR
	SELECT *
	FROM PAYWEEK_FOR_DEALS_NG
	UNION ALL CORR
	SELECT *
	FROM PAYWEEK_FOR_DEALS_AANET
;
QUIT;