/*SEE WHAT DATASETS WE HAVE TO COMBINE SECURITIZATION*/

PROC DATASETS LIB=WORK;
	CONTENTS DATA=_ALL_
	OUT=DATASETS;
RUN;

/*SFTP TABLES*/
PROC SQL;
	CREATE TABLE DISTINCT_TABLES_SFTP AS
	SELECT DISTINCT MEMNAME
	FROM DATASETS
	WHERE MEMNAME LIKE ('SFTP_LAYOUT%')
;
QUIT;

DATA SFTP_COUNT;
	SET DISTINCT_TABLES_SFTP;
	RETAIN COUNT 0;
	COUNT+1;
	TOTAL_COUNTER = COUNT;
	TYPE = TRANWRD(MEMNAME,'_',' ');
RUN;

/*TRANS_SFTP*/
PROC SQL;
	CREATE TABLE DISTINCT_TABLES_SFTP_TRANS AS
	SELECT DISTINCT MEMNAME
	FROM DATASETS
	WHERE MEMNAME LIKE ('%TRANS_SFTP%')
;
QUIT;

DATA SFTPTRANS_COUNT;
	SET DISTINCT_TABLES_SFTP_TRANS;
	RETAIN COUNT 0;
	COUNT+1;
	TOTAL_COUNTER = COUNT;
	TYPE = TRANWRD(MEMNAME,'_',' ');
RUN;

/*PAYWEEK*/
PROC SQL;
	CREATE TABLE DISTINCT_TABLES_PAYWEEK AS
	SELECT DISTINCT MEMNAME
	FROM DATASETS
	WHERE MEMNAME LIKE ('%PAYWEEK%')
;
QUIT;

DATA PAYWEEK_COUNT;
	SET DISTINCT_TABLES_PAYWEEK;
	RETAIN COUNT 0;
	COUNT+1;
	TOTAL_COUNTER = COUNT;
	TYPE = TRANWRD(MEMNAME,'_',' ');
RUN;

/*DEAL LEVEL INFO*/
PROC SQL;
	CREATE TABLE DISTINCT_TABLES_DEALLVLINFO AS
	SELECT DISTINCT MEMNAME
	FROM DATASETS
	WHERE MEMNAME LIKE ('%DEALSUM_SECUR%')
;
QUIT;

DATA DEALLVLINFO_COUNT;
	SET DISTINCT_TABLES_DEALLVLINFO;
	RETAIN COUNT 0;
	COUNT+1;
	TOTAL_COUNTER = COUNT;
	TYPE = TRANWRD(MEMNAME,'_',' ');
RUN;

%MACRO CHECK_FIRST_FILE_IN(FILE=,TOTAL_COUNTER=,FILE_NAME=,EXTENSION=);

	%IF &TOTAL_COUNTER.= 1  %THEN 
		%DO;

			
		

		%END;

	%ELSE %IF &TOTAL_COUNTER. ^= 1 %THEN 
		%DO;

			%PUT &FILE;
			%PUT &EXTENSION;

			DATA _NULL_;
				CALL SYMPUTX("FILE_USE","&FILE",'G');
				CALL SYMPUTX("TOTAL_COUNTER_USE",&TOTAL_COUNTER.,'G');
			RUN;	

			/*IMPORT PIPE DELIMITED FILE	*/
			%INCLUDE "&WHEREPRGMSAT.\BEAM FILE IMPORT.SAS";
				%BEAM_IMPORT
			/*BEAM_ACOUNT_EXTRACT_&TOTAL_COUNTER. IS CREATED*/


			PROC APPEND BASE=BEAM_ACCT_EXTRACT DATA=BEAM_ACOUNT_EXTRACT_&TOTAL_COUNTER. FORCE;
			RUN;

		%END;
%MEND;



