%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";

LIBNAME BIOR ORACLE
	USER=&USER.
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=BIOR DEFER=YES;

LIBNAME TMP_TBLS ORACLE 
	USER=&USER. 
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=TEMPTABLES DEFER=YES;

LIBNAME XLS_SRC "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SECURITIZATION-V2\FINAL DATASETS\PAYDAY";
/*LIBNAME XLS_SRC "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SECURITIZATION-V2\FINAL DATASETS\PAYDAY";*/

%LET STARTDT_TOTAL = 02NOV2015; 

DATA _NULL_;

	*PORTFOLIO START;
	CALL SYMPUTX('STARTDATE_TOTAL',"'&STARTDT_TOTAL'D",'G');
	CALL SYMPUTX('STARTDATETIME_TOTAL',"'&STARTDT_TOTAL.:00:00:00'DT",'G');

RUN;

