/*PAYDAY SECURITIZATION MACRO ASSIGNMENTS

	INSTANCES CURRENTLY IN PAYDAY SECURITIZATION
		
		-EADV
		-NG
		
*/

/*INSTANCES*/
%LET INSTANCE = 'NG';
%LET INSTANCE_NAME = NG;

/*RUN DATE*/
%LET RUNDT = TODAY();
%LET MAX_WEEKS = 17;


/*NG_STATES*/
%LET BU = '16', '17', '917', '217', '240', '40';
%LET STARTDT    = 02NOV2015; 
%LET NG_STARTDT = 04DEC2017;
%LET KS_STARTDT = 04DEC2017;
%LET KY_STARTDT = 04DEC2017;
%LET SC_STARTDT = 04DEC2017;

DATA _NULL_;
*AS OF DATE;
	CALL SYMPUTX('RUNDATE',&RUNDT,'G');
	CALL SYMPUTX('RUNDATETIME',DHMS(&RUNDT.,0,0,0),'G');
*KANSAS;
	CALL SYMPUTX('KS_STARTDATE',"'&KS_STARTDT'D",'G');
	CALL SYMPUTX('KS_STARTDATETIME',"'&KS_STARTDT.:00:00:00'DT",'G');
*KENTUCKY;
	CALL SYMPUTX('KY_STARTDATE',"'&KY_STARTDT'D",'G');
	CALL SYMPUTX('KY_STARTDATETIME',"'&KY_STARTDT.:00:00:00'DT",'G');
*SOUTH CAROLINA;
	CALL SYMPUTX('SC_STARTDATE',"'&SC_STARTDT'D",'G');
	CALL SYMPUTX('SC_STARTDATETIME',"'&SC_STARTDT.:00:00:00'DT",'G');
*PORTFOLIO START;
	CALL SYMPUTX('STARTDATE',"'&STARTDT'D",'G');
	CALL SYMPUTX('STARTDATETIME',"'&STARTDT.:00:00:00'DT",'G');
RUN;

%LET BU_ASSIGNMENT_BEGIN = 
				   (CASE WHEN BUSN_UNIT_ID IN (40,240)  			THEN &SC_STARTDATE
			             WHEN BUSN_UNIT_ID IN (17,217,917) 			THEN &KY_STARTDATE
			             WHEN BUSN_UNIT_ID =  16 					THEN &KS_STARTDATE   ELSE ''D END) FORMAT MMDDYY10. 	AS BEGINDT;

%LET BU_ASSIGNMENT_ENDDT = (CASE WHEN BUSN_UNIT_ID IS NOT MISSING THEN '31DEC9999'D  ELSE '31DEC9999'D END) FORMAT MMDDYY10. 	 AS ENDDT;
