/*PAYDAY SECURITIZATION MACRO ASSIGNMENTS

	INSTANCES CURRENTLY IN PAYDAY SECURITIZATION
		
		-EADV
		-NG
		
*/

/*INSTANCES*/
%LET INSTANCE = 'EAPROD1';
%LET INSTANCE_NAME = EAPROD1;

/*RUN DATE*/
%LET RUNDT = TODAY();
%LET MAX_WEEKS = 17;

/*EADV_STATES*/
%LET BU = 0, 1, 5, 9, 12, 13, 14, 16, 18, 24, 25, 28, 36, 39, 40, 
		  42, 44, 46, 47, 49, 50, 108, 115, 124, 127, 149, 201, 
		  222, 224, 236, 240, 249, 318, 340, 801, 901, 918, 924, 927, 942, 946;

%LET STARTDT    = 02NOV2015; 
%LET RI_STARTDT = 02NOV2015;
%LET LA_STARTDT = 23NOV2015;
%LET IN_STARTDT	= 30NOV2015;
%LET TN_STARTDT = 07DEC2015;
%LET TN_ENDDT   = 04JAN2016;
%LET VA_STARTDT = 07DEC2015;
%LET WY_STARTDT = 07DEC2015;
%LET WY_ENDDT   = 25APR2016;
%LET CA_STARTDT = 14DEC2015;
%LET FL_STARTDT = 21DEC2015;
/*NEW STATES ADDED 27NOV2017*/
%LET AL_STARTDT = 27NOV2017;
%LET DE_STARTDT = 27NOV2017;
%LET IA_STARTDT = 27NOV2017;
%LET ID_STARTDT = 27NOV2017;
%LET IL_STARTDT = 27NOV2017;
%LET KS_STARTDT = 27NOV2017;
%LET MI_STARTDT = 27NOV2017;
%LET MO_STARTDT = 27NOV2017;
%LET MS_STARTDT = 27NOV2017;
%LET NE_STARTDT = 27NOV2017;
%LET NV_STARTDT = 27NOV2017;
%LET OK_STARTDT = 27NOV2017;
%LET SC_STARTDT = 27NOV2017;
%LET UT_STARTDT = 27NOV2017;
%LET WA_STARTDT = 27NOV2017;
%LET WI_STARTDT = 27NOV2017;
%LET WY_STARTDT = 27NOV2017;

DATA _NULL_;
*AS OF DATE;
	CALL SYMPUTX('RUNDATE',&RUNDT,'G');
	CALL SYMPUTX('RUNDATETIME',DHMS(&RUNDT.,0,0,0),'G');
	CALL SYMPUTX('RUNDATE_USE',COMPRESS(CATX('',"'",PUT(&RUNDT,DATE9.),"'")),'G');
*RHODE ISLAND;
	CALL SYMPUTX('RI_STARTDATE',"'&RI_STARTDT'D",'G');
	CALL SYMPUTX('RI_STARTDATETIME',"'&RI_STARTDT.:00:00:00'DT",'G');
*LOUISIANA;
	CALL SYMPUTX('LA_STARTDATE',"'&LA_STARTDT'D",'G');
	CALL SYMPUTX('LA_STARTDATETIME',"'&LA_STARTDT.:00:00:00'DT",'G');
*INDIANA;
	CALL SYMPUTX('IN_STARTDATE',"'&IN_STARTDT'D",'G');
	CALL SYMPUTX('IN_STARTDATETIME',"'&IN_STARTDT.:00:00:00'DT",'G');
/**TENNESSEE**/
	CALL SYMPUTX('TN_STARTDATE',"'&TN_STARTDT'D",'G');
	CALL SYMPUTX('TN_STARTDATETIME',"'&TN_STARTDT.:00:00:00'DT",'G');
	CALL SYMPUTX('TN_ENDDATE',"'&TN_ENDDT'D",'G');
	CALL SYMPUTX('TN_ENDDATETIME',"'&TN_ENDDT.:00:00:00'DT",'G');
/**VIRGINIA**/
	CALL SYMPUTX('VA_STARTDATE',"'&VA_STARTDT'D",'G');
	CALL SYMPUTX('VA_STARTDATETIME',"'&VA_STARTDT.:00:00:00'DT",'G');
/**WYOMING**/
	CALL SYMPUTX('WY_STARTDATE',"'&WY_STARTDT'D",'G');
	CALL SYMPUTX('WY_STARTDATETIME',"'&WY_STARTDT.:00:00:00'DT",'G');
	CALL SYMPUTX('WY_ENDDATE',"'&WY_ENDDT'D",'G');
	CALL SYMPUTX('WY_ENDDATETIME',"'&WY_ENDDT.:00:00:00'DT",'G');
/**CALIFORNIA**/
	CALL SYMPUTX('CA_STARTDATE',"'&CA_STARTDT'D",'G');
	CALL SYMPUTX('CA_STARTDATETIME',"'&CA_STARTDT.:00:00:00'DT",'G');
/**FLORIDA**/
	CALL SYMPUTX('FL_STARTDATE',"'&FL_STARTDT'D",'G');
	CALL SYMPUTX('FL_STARTDATETIME',"'&FL_STARTDT.:00:00:00'DT",'G');
/**ALABAMA**/
	CALL SYMPUTX('AL_STARTDATE',"'&AL_STARTDT'D",'G');
	CALL SYMPUTX('AL_STARTDATETIME',"'&AL_STARTDT.:00:00:00'DT",'G');
/**DELAWARE**/
	CALL SYMPUTX('DE_STARTDATE',"'&DE_STARTDT'D",'G');
	CALL SYMPUTX('DE_STARTDATETIME',"'&DE_STARTDT.:00:00:00'DT",'G');
/**IOWA**/
	CALL SYMPUTX('IA_STARTDATE',"'&IA_STARTDT'D",'G');
	CALL SYMPUTX('IA_STARTDATETIME',"'&IA_STARTDT.:00:00:00'DT",'G');
/**IDAHO**/
	CALL SYMPUTX('ID_STARTDATE',"'&ID_STARTDT'D",'G');
	CALL SYMPUTX('ID_STARTDATETIME',"'&ID_STARTDT.:00:00:00'DT",'G');
/**ILLINOIS**/
	CALL SYMPUTX('IL_STARTDATE',"'&IL_STARTDT'D",'G');
	CALL SYMPUTX('IL_STARTDATETIME',"'&IL_STARTDT.:00:00:00'DT",'G');
/**KANSAS**/
	CALL SYMPUTX('KS_STARTDATE',"'&KS_STARTDT'D",'G');
	CALL SYMPUTX('KS_STARTDATETIME',"'&KS_STARTDT.:00:00:00'DT",'G');
/**MICHIGAN**/
	CALL SYMPUTX('MI_STARTDATE',"'&MI_STARTDT'D",'G');
	CALL SYMPUTX('MI_STARTDATETIME',"'&MI_STARTDT.:00:00:00'DT",'G');
/**MISSOURI**/
	CALL SYMPUTX('MO_STARTDATE',"'&MO_STARTDT'D",'G');
	CALL SYMPUTX('MO_STARTDATETIME',"'&MO_STARTDT.:00:00:00'DT",'G');
/**MISSISSIPPI**/
	CALL SYMPUTX('MS_STARTDATE',"'&MS_STARTDT'D",'G');
	CALL SYMPUTX('MS_STARTDATETIME',"'&MS_STARTDT.:00:00:00'DT",'G');
/**NEBRASKA**/
	CALL SYMPUTX('NE_STARTDATE',"'&NE_STARTDT'D",'G');
	CALL SYMPUTX('NE_STARTDATETIME',"'&NE_STARTDT.:00:00:00'DT",'G');
/**NEVADA**/
	CALL SYMPUTX('NV_STARTDATE',"'&NV_STARTDT'D",'G');
	CALL SYMPUTX('NV_STARTDATETIME',"'&NV_STARTDT.:00:00:00'DT",'G');
/**OKLAHOMA**/
	CALL SYMPUTX('OK_STARTDATE',"'&OK_STARTDT'D",'G');
	CALL SYMPUTX('OK_STARTDATETIME',"'&OK_STARTDT.:00:00:00'DT",'G');
/**SOUTH CAROLINA**/
	CALL SYMPUTX('SC_STARTDATE',"'&SC_STARTDT'D",'G');
	CALL SYMPUTX('SC_STARTDATETIME',"'&SC_STARTDT.:00:00:00'DT",'G');
/**UTAH**/
	CALL SYMPUTX('UT_STARTDATE',"'&UT_STARTDT'D",'G');
	CALL SYMPUTX('UT_STARTDATETIME',"'&UT_STARTDT.:00:00:00'DT",'G');
/**WASHINGTON**/
	CALL SYMPUTX('WA_STARTDATE',"'&WA_STARTDT'D",'G');
	CALL SYMPUTX('WA_STARTDATETIME',"'&WA_STARTDT.:00:00:00'DT",'G');
/**WISCONSIN**/
	CALL SYMPUTX('WI_STARTDATE',"'&WI_STARTDT'D",'G');
	CALL SYMPUTX('WI_STARTDATETIME',"'&WI_STARTDT.:00:00:00'DT",'G');
/**WYOMING**/
	CALL SYMPUTX('WY_STARTDATE',"'&WY_STARTDT'D",'G');
	CALL SYMPUTX('WY_STARTDATETIME',"'&WY_STARTDT.:00:00:00'DT",'G');
	*PORTFOLIO START;
	CALL SYMPUTX('STARTDATE',"'&STARTDT'D",'G');
	CALL SYMPUTX('STARTDATETIME',"'&STARTDT.:00:00:00'DT",'G');
RUN;

%PUT &RUNDATE_USE;

%LET BU_ASSIGNMENT_BEGIN = (CASE WHEN BUSN_UNIT_ID    = 39		THEN &RI_STARTDATE
                     WHEN BUSN_UNIT_ID = 18 			THEN &LA_STARTDATE
                     WHEN BUSN_UNIT_ID = 14 			THEN &IN_STARTDATE 
                     WHEN BUSN_UNIT_ID = 50 			THEN &WY_STARTDATE
                     WHEN BUSN_UNIT_ID = 42 			THEN &TN_STARTDATE
                     WHEN BUSN_UNIT_ID = 46 			THEN &VA_STARTDATE
                     WHEN BUSN_UNIT_ID = 5 				THEN &CA_STARTDATE
                     WHEN BUSN_UNIT_ID = 9 				THEN &FL_STARTDATE
					 WHEN BUSN_UNIT_ID = 1				THEN &AL_STARTDATE
					 WHEN BUSN_UNIT_ID = 201			THEN &AL_STARTDATE
					 WHEN BUSN_UNIT_ID = 801			THEN &AL_STARTDATE
					 WHEN BUSN_UNIT_ID = 108			THEN &DE_STARTDATE
					 WHEN BUSN_UNIT_ID = 115			THEN &IA_STARTDATE
					 WHEN BUSN_UNIT_ID = 12				THEN &ID_STARTDATE
					 WHEN BUSN_UNIT_ID = 13				THEN &IL_STARTDATE
					 WHEN BUSN_UNIT_ID = 14				THEN &IN_STARTDATE
					 WHEN BUSN_UNIT_ID = 16				THEN &KS_STARTDATE
					 WHEN BUSN_UNIT_ID = 318			THEN &LA_STARTDATE
					 WHEN BUSN_UNIT_ID = 18				THEN &LA_STARTDATE
					 WHEN BUSN_UNIT_ID = 222			THEN &MI_STARTDATE
					 WHEN BUSN_UNIT_ID = 25				THEN &MO_STARTDATE
					 WHEN BUSN_UNIT_ID = 224			THEN &MS_STARTDATE
					 WHEN BUSN_UNIT_ID = 24				THEN &MS_STARTDATE
					 WHEN BUSN_UNIT_ID = 124			THEN &MS_STARTDATE
					 WHEN BUSN_UNIT_ID = 127			THEN &NE_STARTDATE
					 WHEN BUSN_UNIT_ID = 28				THEN &NV_STARTDATE
					 WHEN BUSN_UNIT_ID = 36				THEN &OK_STARTDATE
					 WHEN BUSN_UNIT_ID = 236			THEN &OK_STARTDATE
					 WHEN BUSN_UNIT_ID = 240			THEN &SC_STARTDATE
					 WHEN BUSN_UNIT_ID = 40				THEN &SC_STARTDATE
					 WHEN BUSN_UNIT_ID = 44				THEN &UT_STARTDATE
					 WHEN BUSN_UNIT_ID = 47				THEN &WA_STARTDATE
					 WHEN BUSN_UNIT_ID = 49				THEN &WI_STARTDATE
					 WHEN BUSN_UNIT_ID = 149			THEN &WI_STARTDATE
					 WHEN BUSN_UNIT_ID = 249			THEN &WI_STARTDATE
					 WHEN BUSN_UNIT_ID = 50 			THEN &WY_STARTDATE	ELSE ''D END) FORMAT MMDDYY10. AS BEGINDT;


%LET BU_ASSIGNMENT_ENDDT = (CASE WHEN BUSN_UNIT_ID = 42 THEN &TN_ENDDATE
                   			  	 WHEN BUSN_UNIT_ID = 50 AND DEAL_DT <= '27NOV2017'D THEN &WY_ENDDATE
                     			ELSE '31DEC9999'D END) 	FORMAT MMDDYY10.										AS ENDDT;
