/*PAYDAY SECURITIZATION MACRO ASSIGNMENTS

	INSTANCES CURRENTLY IN PAYDAY SECURITIZATION
		
		-EADV
		-NG
		-AANET
		
*/

/*INSTANCES*/
%LET INSTANCE = 'AANET';
%LET INSTANCE_NAME = AANET;

/*RUN DATE*/
%LET RUNDT = TODAY();
%LET MAX_WEEKS = 17;
%LET STARTDT    = 02NOV2015; 
%LET BEGINDT = 20JAN2019;

DATA _NULL_;
	*AS OF DATE;
	CALL SYMPUTX('RUNDATE',&RUNDT,'G');
	CALL SYMPUTX('RUNDATETIME',DHMS(&RUNDT.,0,0,0),'G');
	CALL SYMPUTX('RUNDATE_USE',COMPRESS(CATX('',"'",PUT(&RUNDT,DATE9.),"'")),'G');
	*PORTFOLIO START;
	CALL SYMPUTX('STARTDATE',"'&STARTDT'D",'G');
	CALL SYMPUTX('STARTDATETIME',"'&STARTDT.:00:00:00'DT",'G');
	*BEGINDT AANET STATES;
	CALL SYMPUTX('BEGINDT_AANET',"'&BEGINDT'D",'G');
	CALL SYMPUTX('BEGINDATETIME_AANET',"'&BEGINDT.:00:00:00'DT",'G');
RUN;

%LET BU_ASSIGNMENT_BEGIN = &BEGINDT_AANET FORMAT MMDDYY10. AS BEGINDT;


%LET BU_ASSIGNMENT_ENDDT =  '31DEC9999'D 	FORMAT MMDDYY10. AS ENDDT;