/*-------------------------------------------------------------------------------------------

	TITLE: PAYDAY SECURITIZATION
	AUTHOR: JUSTIN HUBBARD
	GOAL: TO GATHER THE CURRENT TRANCHES ACTIVITY AND CREATE DATA AVAILABLE TO INSERT INTO THE SECURITIZATION MODEL

	PROCEDURE:
		
		1)

---------------------------------------------------------------------------------------------------------------------------------------------------*/

OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT NOQUOTELENMAX LRECL=32767;
/*WHERE ARE THE PROGRAMS?*/
%LET WHEREPRGRMSAT = E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SECURITIZATION-V2\PAYDAY;
/*%LET WHEREPRGRMSAT = E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SECURITIZATION-V2\PAYDAY;*/

/*%LET FILEPATH = \\AACSS\CSSFILES\SAS SECURITIZATION FILES\PAYDAY;*/
%LET FILEPATH = E:\SHARED\CADA\SAS SOURCE CODE\Development\JHubbard\Securitization-v2\Payday\Files;

%LET PRODUCT = 'PAYDAY';
%PUT &PRODUCT;

/*ASSIGN LIBRARIES*/
%INCLUDE "&WHEREPRGRMSAT\LIBRARIES.SAS";

/*TRANSACTIONS*/
%INCLUDE "&WHEREPRGRMSAT\TRANSACTIONS FOR TRANCHE.SAS";

	%SECURITIZATION_TRAN(EAPROD1)
	%SECURITIZATION_TRAN(NG)
	%SECURITIZATION_TRAN(AANET)
/*	%SECURITIZATION_TRAN(FUSE)*/
/*	%SECURITIZATION_TRAN(QFUND4)*/
/*	%SECURITIZATION_TRAN(QFUND3)*/


%INCLUDE "&WHEREPRGRMSAT\COMBINE DATA ACROSS POS.SAS";

%INCLUDE "&WHEREPRGRMSAT\STATISTICS ON TRANCHE.SAS";

%INCLUDE "&WHEREPRGRMSAT\PURCHASE FILE.SAS";

%INCLUDE "&WHEREPRGRMSAT\BALANCE FILE.SAS";

%INCLUDE "&WHEREPRGRMSAT\ROLLUP FINAL DATASETS.SAS";

/*EMAIL WHEN FINISHED*/
OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;
FILENAME MYMAIL EMAIL; 
DATA _NULL_;
   FILE MYMAIL
		TO=('JHAMES@ADVANCEAMERICA.NET','JHUBBARD@ADVANCEAMERICA.NET','JROSE@ADVANCEAMERICA.NET')
	    FROM='SECURITIZATION@COMPLETE.COM'
		SUBJECT="SECURITIZATION FILES ARE COMPLETE - PAYDAY MODEL";
		PUT "THE FILES ARE READY FOR THE PAYDAY CASH FLOW MODEL" /;
		PUT "TOTAL PAYDAY BORRORINGS FOR THIS WEEK: $&AMTOFFEREDTXT.." /;
		PUT "REMEMBER TO INPUT PRESTON'S PAYDAY SPV NUMBERS ";
RUN;


