*WRITES THE DAILY PURCHASE FILE.;
%MACRO PURCHASE_FILE();
	DATA HEADER_DEAL;
		NUMBER_OFFERED = "&X";
		COMPANY_NAME = "ADVANCE AMERICA";
		COUNTRY_SHORT = "USA";
		FULL_AMOUNT_OFFERED = &AMTOFFERED;
		PRODUCT_NUMBER = 10000+&X;
		CALL SYMPUTX('FILENAME_DEAL',CAT("AAR",COMPRESS(((&RUNDATE_USE))),"&X"),'G');
		FORMAT FULL_AMOUNT_OFFERED COMMA25.2;
	RUN;
	TITLE;
	ODS CSVALL FILE="&FILEPATH.\&FILENAME_DEAL..CSV";

	PROC PRINT DATA=HEADER_DEAL NOOBS; 
	RUN;
	PROC PRINT DATA=SFTP_LAYOUT NOOBS;
		VAR LOAN_NUMBER CUSTOMER_ID PRODUCT_TYPE SOURCE_PRODUCT STATE DEALDT DUEDT TERM LOCNBR CASH_AGN ADVAMT FEES TOTAL_AMT;
		WHERE TRANCHE_ID = &X;
	RUN;
	ODS CSVALL CLOSE;
%MEND;
%PURCHASE_FILE()