PROC SQL;
	CREATE TABLE WORK.FULL_AMT_OFFERED AS
	SELECT (SUM(t1.ADVAMT)) FORMAT=20.2 AS ADVAMT
	FROM SFTP_LAYOUT T1
;
QUIT;

PROC SQL NOPRINT;
	SELECT ADVAMT INTO :AMTOFFERED
	FROM FULL_AMT_OFFERED;
	SELECT COUNT(*) INTO :TRANSCNT
	FROM TRANS_SFTP_LAYOUT;
	SELECT DISTINCT TRANCHE_ID INTO :T_ID_BAL
	SEPARATED BY " "
	FROM TRANS_SFTP_LAYOUT;
	SELECT DISTINCT TRANCHE_ID INTO :T_ID_PURCH
	SEPARATED BY " "
	FROM SFTP_LAYOUT;
	SELECT MAX(DATEPART(OPERATIONDATE)) INTO :MAX_DEAL_DT
	FROM TRANS_SFTP_LAYOUT;
QUIT;

DATA _NULL_;
	CALL SYMPUTX("AMTOFFEREDTXT",COMPRESS(PUT(&AMTOFFERED,COMMA20.2)));
RUN;

DATA;
	LAST_T_ID=INTCK('WEEK',("&STARTDATE_TOTAL"D),(&MAX_DEAL_DT)-1)+1;
	CALL SYMPUTX('X',LAST_T_ID,'G');
	CALL SYMPUT('PRETTYDT',TRIM(LEFT(PUT(TODAY(),WORDDATE20.))));
RUN;

PROC FORMAT;
	PICTURE DAYSTAMP OTHER= %0M%0D%0Y (DATATYPE=DATE);
RUN;