PROC SQL;
   CREATE TABLE INBOUND_REQUEST AS 
   SELECT T1.FI_EEE_IN_REQUEST_ID, 
          T1.FD_CREATE_DATE,
          T1.FC_SSN, 
          (	CASE WHEN FC_PRODUCT_CODE = 'I' THEN 'INSTALLMENT'
			WHEN  FC_PRODUCT_CODE = 'A' THEN 'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'T' THEN 'TITLE'
			WHEN  FC_PRODUCT_CODE = 'C' THEN 'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'TR' THEN 'TITLE'
			WHEN  FC_PRODUCT_CODE = 'CR' THEN 'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'L' THEN 'LINEOFCREDIT'
			WHEN  FC_PRODUCT_CODE = 'IR' THEN  'INSTALLMENT'
			WHEN  FC_PRODUCT_CODE = 'AR' THEN  'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'F'  THEN  'INSTALLMENT'
			WHEN  FC_PRODUCT_CODE = 'TTOC' THEN  'TITLE'
			WHEN  FC_PRODUCT_CODE = 'TTOCR' THEN  'TITLE'
			WHEN  FC_PRODUCT_CODE = 'FR' THEN  'INSTALLMENT' END ) AS PRODUCT
		,FC_PRODUCT_CODE	
      FROM RTDM.TA_EEE_INBOUND_REQUEST T1
	  WHERE FD_CREATE_DATE <= DATETIME()
;
QUIT;

PROC SQL;
	CREATE TABLE SCORE AS
	SELECT FI_EEE_IN_REQUEST_ID
		   ,FC_RESPONSE_TYPE_CODE
		   ,FD_CREATE_DATE
		   ,FI_REQUEST_ID
		   ,FC_TRACK_ID
		   ,FI_SCORE						AS RISK_MODEL_SCORE
	FROM RTDM.TA_EEE_OUTBOUND_RESPONSE
	WHERE FD_CREATE_DATE <= DATETIME()
;
QUIT;


PROC SQL;
	CREATE TABLE COMBINE_SCORE AS
	SELECT A.PRODUCT	AS PRODUCT
	      ,A.FI_EEE_IN_REQUEST_ID	AS REQUEST_ID
		  ,A.FC_SSN				AS SSN
		  ,B.FC_TRACK_ID		AS TRACK_ID
		  ,B.RISK_MODEL_SCORE
		  ,B.FD_CREATE_DATE		AS EFFECTIVE_DATE
	FROM INBOUND_REQUEST A
	INNER JOIN SCORE B
		ON (A.FI_EEE_IN_REQUEST_ID = B.FI_EEE_IN_REQUEST_ID)
	WHERE B.RISK_MODEL_SCORE IS NOT NULL
;
QUIT;

PROC SORT DATA=COMBINE_SCORE OUT=COMBINE_SCORE_SRT;
BY SSN EFFECTIVE_DATE;
RUN;

PROC SQL;
	DROP TABLE BIOR.RISK_MODEL_SCORE_DM
;
QUIT;

PROC SQL;
	CREATE TABLE BIOR.RISK_MODEL_SCORE_DM AS
	SELECT *
	FROM COMBINE_SCORE_SRT
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="BIOR");
		EXECUTE (CREATE INDEX IDX_RMS_SSN  	ON BIOR.RISK_MODEL_SCORE_DM (SSN))								BY ORACLE;
		EXECUTE (CREATE INDEX IDX_RMS_TID  	ON BIOR.RISK_MODEL_SCORE_DM (TRACK_ID))						BY ORACLE;
		EXECUTE (CREATE INDEX IDX_RMS_PRD  	ON BIOR.RISK_MODEL_SCORE_DM (PRODUCT))							BY ORACLE;
		EXECUTE (CREATE INDEX IDX_RMS_RQI  	ON BIOR.RISK_MODEL_SCORE_DM (REQUEST_ID))							BY ORACLE;

DISCONNECT FROM ORACLE;
QUIT;


