PROC SQL;
	CREATE TABLE MAXDATE AS
	SELECT MAX(EFFECTIVE_DATE)		AS MAX_EFFECTIVE_DATE
		  ,DATETIME()				AS TODAYS_DATE
	FROM BIOR.RISK_MODEL_SCORE_DM
;
QUIT;

DATA HOWFARTOGOBACK;
	SET MAXDATE;
	HOWFARTOGOBACK = INTCK('DAY',DATEPART(MAX_EFFECTIVE_DATE),DATEPART(TODAYS_DATE));
	CALL SYMPUTX('HOWFARTOGOBACK',HOWFARTOGOBACK);
RUN;


PROC SQL;
   CREATE TABLE INBOUND_REQUEST AS 
   SELECT T1.FI_EEE_IN_REQUEST_ID, 
          T1.FD_CREATE_DATE,
          T1.FC_SSN, 
          (	CASE WHEN FC_PRODUCT_CODE = 'I' THEN 'INSTALLMENT'
			WHEN  FC_PRODUCT_CODE = 'A' THEN 'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'T' THEN 'TITLE'
			WHEN  FC_PRODUCT_CODE = 'C' THEN 'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'TR' THEN 'TITLE'
			WHEN  FC_PRODUCT_CODE = 'CR' THEN 'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'L' THEN 'LINEOFCREDIT'
			WHEN  FC_PRODUCT_CODE = 'IR' THEN  'INSTALLMENT'
			WHEN  FC_PRODUCT_CODE = 'AR' THEN  'PAYDAY'
			WHEN  FC_PRODUCT_CODE = 'F'  THEN  'INSTALLMENT'
			WHEN  FC_PRODUCT_CODE = 'TTOC' THEN  'TITLE'
			WHEN  FC_PRODUCT_CODE = 'TTOCR' THEN  'TITLE'
			WHEN  FC_PRODUCT_CODE = 'FR' THEN  'INSTALLMENT' END ) AS PRODUCT
		,FC_PRODUCT_CODE	
      FROM RTDM.TA_EEE_INBOUND_REQUEST T1
	  WHERE FD_CREATE_DATE >= DHMS(TODAY()-&HOWFARTOGOBACK.,00,00,00)
;
QUIT;

PROC SQL;
	CREATE TABLE SCORE AS
	SELECT FI_EEE_IN_REQUEST_ID
		   ,FC_RESPONSE_TYPE_CODE
		   ,FD_CREATE_DATE
		   ,FI_REQUEST_ID
		   ,FC_TRACK_ID
		   ,FI_SCORE						AS RISK_MODEL_SCORE
	FROM RTDM.TA_EEE_OUTBOUND_RESPONSE
	WHERE FD_CREATE_DATE >= DHMS(TODAY()-&HOWFARTOGOBACK.,00,00,00)
;
QUIT;


PROC SQL;
	CREATE TABLE COMBINE_SCORE AS
	SELECT A.PRODUCT	AS PRODUCT
		  ,A.FI_EEE_IN_REQUEST_ID	AS REQUEST_ID
		  ,A.FC_SSN				AS SSN
		  ,B.FC_TRACK_ID		AS TRACK_ID
		  ,B.RISK_MODEL_SCORE
		  ,B.FD_CREATE_DATE		AS EFFECTIVE_DATE
	FROM INBOUND_REQUEST A
	INNER JOIN SCORE B
		ON (A.FI_EEE_IN_REQUEST_ID = B.FI_EEE_IN_REQUEST_ID)
	WHERE B.RISK_MODEL_SCORE IS NOT NULL
;
QUIT;

PROC SORT DATA=COMBINE_SCORE OUT=COMBINE_SCORE_SRT;
BY SSN EFFECTIVE_DATE;
RUN;

PROC FORMAT;
	PICTURE whatDayIsIt other=%0Y.%0m.%0d (DATATYPE=DATE);
	PICTURE whatTimeIsIt other=%0h.%0M.%0S (DATATYPE=TIME);
RUN;

DATA _NULL_;
	CALL SYMPUTX('timestamp',CATX('_',PUT(TODAY(),whatDayIsIt.),PUT(TIME(),whatTimeIsIt.)),'G');
RUN;

%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;

DATA _NULL_;
CALL SYMPUTX('PATH',"\\CSSSASAPP\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\RTDM_UNDERWRITING DM\O_RTDM_UW_DM\LOGS\RMS DM",'G');
CALL SYMPUTX('PATHTWO',"\\CSSSASAPP\CADA\SAS DATA\USER\JHUBBARD\LOGS\RMS DM",'G');
RUN;

PROC SQL;
INSERT INTO BIOR.RISK_MODEL_SCORE_DM (BULKLOAD=YES BL_LOG="&PATH.\BL_&TIMESTAMP..LOG" BL_DELETE_DATAFILE=YES BL_DEFAULT_DIR="&PATHTWO.")
SELECT *
FROM COMBINE_SCORE_SRT;




