
%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\STDM\STDM_LIBRARY_SCRIPT.SAS";

LIBNAME BIOR ORACLE 
	USER=&USER 
	PASSWORD=&PASSWORD
	PATH=BIOR
	SCHEMA=BIOR;

LIBNAME TMP_TBLS ORACLE 
	USER=&USER 
	PASSWORD=&PASSWORD
	PATH=BIOR
	SCHEMA=TEMPTABLES;

LIBNAME RTDM ORACLE
	USER=&USER
	PASSWORD=&PASSWORD
	PATH=PEDWPROD1
	SCHEMA=SC_RTDM;

LIBNAME SC_DM ORACLE
	USER=&USER
	PASSWORD=&PASSWORD
	PATH=PEDWPROD1
	SCHEMA=SC_DMARTS;

OPTIONS OBS=MAX;