/*

	AUTHOR: JUSTIN HUBBARD
	GOAL: PROVIDE AN EASY WAY TO GET MODEL SCORES HISTORICALLY FOR CUSTOMERS

*/

OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT NOQUOTELENMAX LRECL=32767;
%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";

%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\RTDM UW\O_RTDM_UW_DM\DAILY RUN\LIBNAMES.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\RTDM UW\O_RTDM_UW_DM\DAILY RUN\DATA PULL OUTBOUND RESPONSE AND APPEND.SAS";

OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;
FILENAME MAIL EMAIL "NULL";
DATA _NULL_;
	FILE MAIL
	TO=('BI_DATA@ADVANCEAMERICA.NET','SHOPKINS@ADVANCEAMERICA.NET')
	SUBJECT="RISK MODEL SCORE DAILY UPDATE COMPLETE";
RUN;

