%PUT ASSIGNING VALUES RIGHT HERE;

PROC SQL; 
DROP TABLE ASSIGN_VALUES;
QUIT;

/*ASSIGN MACROS AGAIN*/
DATA ASSIGN_VALUES;
	SET INSTANCE_ETL_CHECK;
	ONLINE_HOUR = HOUR(DATETIME());
	DAY = WEEKDAY(TODAY());
	IF INSTANCE = 'EADV'				THEN CALL SYMPUTX("EADV",1,'G');
	IF INSTANCE = 'NEXTGEN' 	  		THEN CALL SYMPUTX("NG",LOADED,'G');

	IF INSTANCE = 'ONLINE' AND DAY = 7 THEN
		DO;
			CALL SYMPUTX("OL",1,'G');
			LOADED = 1;
		END;

	ELSE IF INSTANCE = 'ONLINE' AND DAY ^= 7 THEN CALL SYMPUTX("OL",LOADED,'G');

	IF INSTANCE = 'QFUND1_QFUND2' 		THEN CALL SYMPUTX('QFUND1_QFUND2',LOADED,'G');
	IF INSTANCE = 'QFUND1'				THEN CALL SYMPUTX('QFUND1',LOADED,'G');
	IF INSTANCE = 'QFUND2'				THEN CALL SYMPUTX('QFUND2',LOADED,'G');
	IF INSTANCE = 'QFUND3'		  		THEN CALL SYMPUTX("QFUND3",LOADED,'G');
	IF INSTANCE = 'QFUND4'		  		THEN CALL SYMPUTX("QFUND4",LOADED,'G');
	IF INSTANCE = 'QFUND5'		  		THEN CALL SYMPUTX("QFUND5",LOADED,'G');
	IF INSTANCE = 'FUSE'				THEN CALL SYMPUTX("FUSE",LOADED,'G');
/*	CALL SYMPUTX("FUSE",1,'G');*/
RUN;

/*WRITE MACROS TO THE LOG*/
%PUT NEXTGEN LOAD STATUS = &NG;
%PUT ONLINE LOAD STATUS = &OL;
%PUT QFUND1_QFUND2 LOAD STATUS = &QFUND1_QFUND2;
%PUT QFUND1 LOAD STATUS = &QFUND1;
%PUT QFUND2 LOAD STATUS = &QFUND2;
%PUT QFUND3 LOAD STATUS = &QFUND3;
%PUT QFUND4 LOAD STATUS = &QFUND4;
%PUT QFUND5 LOAD STATUS = &QFUND5;
%PUT EADV LOAD STATUS = &EADV;
%PUT FUSE LOAD STATUS = &FUSE;