/*-----------------------------------------------------------CUSTOMER DATAMART---------------------------------------------------*/

/*EADV*/
PROC SQL NOPRINT;
	SELECT EADV_STATUS
		  ,DATEPART(EADV_RUN_DATE)
		  ,DATEPART(EADV_COMPLETION_DATE) 
				INTO :TRAN_EADV_STATUS
				   , :TRAN_EADV_RUN_DATE
				   , :TRAN_EADV_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*QFUND1*/
PROC SQL NOPRINT;
	SELECT QFUND1_INSTALL_STATUS
		  ,DATEPART(QFUND1_INSTALL_RUN_DATE)
		  ,DATEPART(QFUND1_INSTALL_COMPLETION_DATE)
		  ,QFUND1_TITLE_STATUS
		  ,DATEPART(QFUND1_TITLE_RUN_DATE)
		  ,DATEPART(QFUND1_TITLE_COMPLETION_DATE) 
				INTO :TRAN_QF1_INSTALL_STATUS
				   , :TRAN_QF1_INSTALL_RUN_DATE
				   , :TRAN_QF1_INSTALL_COMPLETION_DATE
				   , :TRAN_QF1_TITLE_STATUS
				   , :TRAN_QF1_TITLE_RUN_DATE
				   , :TRAN_QF1_TITLE_COMPLETION_DATE	
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*QFUND2*/
PROC SQL NOPRINT;
	SELECT QFUND2_INSTALL_STATUS
		  ,DATEPART(QFUND2_INSTALL_RUN_DATE)
		  ,DATEPART(QFUND2_INSTALL_COMPLETION_DATE)
				INTO :TRAN_QF2_INSTALL_STATUS
				   , :TRAN_QF2_INSTALL_RUN_DATE
				   , :TRAN_QF2_INSTALL_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;


/*QFUND3*/
PROC SQL NOPRINT;
	SELECT QFUND3_TTOC_STATUS
		  ,DATEPART(QFUND3_TTOC_RUN_DATE)
		  ,DATEPART(QFUND3_TTOC_COMPLETION_DATE)
		  ,QFUND3_TXTITLE_STATUS
		  ,DATEPART(QFUND3_TXTITLE_RUN_DATE)
		  ,DATEPART(QFUND3_TXTITLE_COMPLETION_DATE)
		  ,QFUND3_TETL_STATUS
		  ,DATEPART(QFUND3_TETL_RUN_DATE)
		  ,DATEPART(QFUND3_TETL_COMPLETION_DATE) 
				INTO :TRAN_QF3_TTOC_STATUS
				   , :TRAN_QF3_TTOC_RUN_DATE
				   , :TRAN_QF3_TTOC_COMPLETION_DATE
				   , :TRAN_QF3_TXTITLE_STATUS
				   , :TRAN_QF3_TXTITLE_RUN_DATE
				   , :TRAN_QF3_TXTITLE_COMPLETION_DATE
				   , :TRAN_QF3_TETL_STATUS
				   , :TRAN_QF3_TETL_RUN_DATE
				   , :TRAN_QF3_TETL_COMPLETION_DATE		
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*QFUND4*/
PROC SQL NOPRINT;
	SELECT QFUND4_PAYDAY_STATUS
		  ,DATEPART(QFUND4_PAYDAY_RUN_DATE)
		  ,DATEPART(QFUND4_PAYDAY_COMPLETION_DATE)
		  ,QFUND4_TITLE_STATUS
		  ,DATEPART(QFUND4_TITLE_RUN_DATE)
		  ,DATEPART(QFUND4_TITLE_COMPLETION_DATE)
				INTO  :TRAN_QF4_PAYDAY_STATUS
					, :TRAN_QF4_PAYDAY_RUN_DATE
					, :TRAN_QF4_PAYDAY_COMPLETION_DATE
					, :TRAN_QF4_TITLE_STATUS
					, :TRAN_QF4_TITLE_RUN_DATE
					, :TRAN_QF4_TITLE_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*QFUND5*/
PROC SQL NOPRINT;
	SELECT QFUND5_PAYDAY_STATUS
		  ,DATEPART(QFUND5_PAYDAY_RUN_DATE)
		  ,DATEPART(QFUND5_PAYDAY_COMPLETION_DATE)
		  ,QFUND5_INSTALL_STATUS
		  ,DATEPART(QFUND5_INSTALL_RUN_DATE)
		  ,DATEPART(QFUND5_INSTALL_COMPLETION_DATE)
		  ,QFUND5_TITLE_STATUS
		  ,DATEPART(QFUND5_TITLE_RUN_DATE)
		  ,DATEPART(QFUND5_TITLE_COMPLETION_DATE)
				INTO  :TRAN_QF5_PAYDAY_STATUS
					, :TRAN_QF5_PAYDAY_RUN_DATE
					, :TRAN_QF5_PAYDAY_COMPLETION_DATE
					, :TRAN_QF5_INSTALL_STATUS
					, :TRAN_QF5_INSTALL_RUN_DATE
					, :TRAN_QF5_INSTALL_COMPLETION_DATE
					, :TRAN_QF5_TITLE_STATUS
					, :TRAN_QF5_TITLE_RUN_DATE
					, :TRAN_QF5_TITLE_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*NG*/
PROC SQL NOPRINT;
	SELECT NG_STATUS
		  ,DATEPART(NG_RUN_DATE)
		  ,DATEPART(NG_COMPLETION_DATE) 
				INTO :TRAN_NG_STATUS
				   , :TRAN_NG_RUN_DATE
				   , :TRAN_NG_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*ONLINE*/
PROC SQL NOPRINT;
	SELECT ONLINE_STATUS
		  ,DATEPART(ONLINE_RUN_DATE)
		  ,DATEPART(ONLINE_COMPLETION_DATE)
		  ,LOC_STATUS
		  ,DATEPART(LOC_RUN_DATE)
		  ,DATEPART(LOC_COMPLETION_DATE)
				INTO :TRAN_OL_STATUS
				   , :TRAN_OL_RUN_DATE
				   , :TRAN_OL_COMPLETION_DATE
				   , :TRAN_LOC_STATUS
				   , :TRAN_LOC_RUN_DATE
				   , :TRAN_LOC_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;

/*FUSE*/
PROC SQL NOPRINT;
	SELECT FUSE_STATUS
		  ,DATEPART(FUSE_RUN_DATE)
		  ,DATEPART(FUSE_COMPLETION_DATE)
				INTO :TRAN_FUSE_STATUS
				   , :TRAN_FUSE_RUN_DATE
				   , :TRAN_FUSE_COMPLETION_DATE
	FROM BIOR.DATAMART_STATUS
	WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
;
QUIT;