OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\TOP SECRET PROGRAM.SAS";


/* CREATE TIMESTAMP */
PROC FORMAT;
	PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
	PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
RUN;

DATA _NULL_;
	CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
RUN;

%PUT &TIMESTAMP;

/* KICK OFF TOTAL LOAN COUNT */

SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
				 'E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET LOAN COUNT\3_YEAR_COUNT.SAS'
				 -LOG 'E:SHARED\CADA\LOGS\3_YEAR_COUNT_&TIMESTAMP..LOG'
				 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
				 TASKNAME=LNCNT
				 STATUS=LNCNT;

SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
				 'E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET LOAN COUNT\DRIVER.SAS'
				 -LOG 'E:SHARED\CADA\LOGS\DRIVER_OLCA_&TIMESTAMP..LOG'
				 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
				 TASKNAME=OLCA
				 STATUS=OLCA;

WAITFOR _ALL_ OLCA;

/* KICK OFF CUSTOMER STATS */

SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
				 'E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\CUSTOMER STATS NEW\CUST_STATS_DRIVER_NEW.SAS'
				 -LOG 'E:SHARED\CADA\LOGS\RTDM_CUSTOMER_STATS_CUST_STATS_NEW_&TIMESTAMP..LOG'
				 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
				 TASKNAME=CUSTSTAT
				 STATUS=CUSTSTAT;

WAITFOR _ALL_ CUSTSTAT;

/* EMAIL FOR CUSTOMER STATS - CHECKS TABLE COUNTS, AND INSERT/UPDATE/DELETE COUNTS */

%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\CUSTOMER STATS NEW\CUST_STATS_EMAIL.SAS";