/*---------------------------------------------END OF CONDITIONAL SOURCE PULL LOGIC-----------------------------------------------------

		NOW THE PROGRAM WILL VISIT PROGRAMS THAT HAVE DEPENDENCIES ON THE PROGRAMS ABOVE FINISHING

		THESE PROGRAMS WILL ONLY BE KICKED OFF IF EVERY INSTANCE/PRODUCT COMBINATION OF DATA HAS BEEN COMPLETED

----------------------------------------------------------------------------------------------------------------------------------*/

/*-----------------------------------------------------------------------------------------------------------------------------------

		ONCE WE GET TO THIS POINT ALL THE DATA HAS: 

			1) DATA FROM ETL HAS BEEN COMPLETED
			2) ALL SKYNET SOURCE PULLS HAVE BEEN KICKED OFF / ARE FINISHING
		
		KNOWING BOTH OF THOSE THINGS, WE NOW NEED TO CONDITIONALLY KICK OFF PROCESSES THAT ARE DEPENDENT ON THE ABOVE SOURCE PULLS. 
		4 DEPENDENCY PROGRAMS WILL KICK OFF SIMULTANEOUSLY NEXT.

			1) DEAL DEPENDENCY
			2) TRAN DEPENDENCY
			3) DEAL AND TRAN DEPENDENCY
			4) DAILY DEPENDENCY

---------------------------------------------------------------------------------------------------------------------------------------*/
OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SKYNET REDESIGN\SKYNET_ERROR_INPUTS.SAS";


LIBNAME BIOR ORACLE
	USER=&USER.
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=BIOR;

LIBNAME TMP_TBLS ORACLE 
	USER=&USER. 
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=TEMPTABLES;

/*PROGRAM LOCATIONS*/
%LET WHEREPRGRMSAT_REDESIGN = E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN;

%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;


/*ASSIGN FILE PATHS*/
DATA _NULL_;
	/*CUSTOMER*/
	CALL SYMPUTX('CUST_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('CUST_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\CUSTOMER",'G');
	/*DEAL*/
	CALL SYMPUTX('DEAL_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('DEAL_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\DEAL",'G');
	/*TRAN*/
	CALL SYMPUTX('TRAN_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('TRAN_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\TRANSACTION",'G');
	/*DAILY*/
	CALL SYMPUTX('DAILY_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('DAILY_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\DAILY",'G');
	/*SKYNET RESIGN LOGS*/
	CALL SYMPUTX('SKYNETREDESIGN',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN",'G');
	CALL SYMPUTX('SKYNETREDESIGN_LOGS',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
%RUNQUIT(&job,&sub1);

/* CREATE TIMESTAMP */
PROC FORMAT;
	PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
	PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
%RUNQUIT(&job,&sub1);

DATA _NULL_;
	CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
%RUNQUIT(&job,&sub1);

%PUT &TIMESTAMP;

	/* KICK OFF DEAL DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\DEAL DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\DEAL_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=DEAL_DEPEND
					 STATUS=DEAL_DEPEND;

	/* KICK OFF TRAN DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\TRAN DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\TRAN_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=TRAN_DEPEND
					 STATUS=TRAN_DEPEND;

	/* KICK OFF DEAL AND TRAN DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\DEAL AND TRAN DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\DEAL_TRAN_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=DT_DEPEND
					 STATUS=DT_DEPEND;

	/* KICK OFF DAILY DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\DAILY DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\DAILY_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=DAILY_DEPEND
					 STATUS=DAILY_DEPEND;

	/* KICK OFF TRANSPOSE DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\TRANSPOSE DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\TRANSPOSE_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=TRANSP_DEPEND
					 STATUS=TRANSP_DEPEND;

	/* KICK OFF CUSTOMER DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\CUSTOMER DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\CUSTOMER_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=CUST_DEPEND
					 STATUS=CUST_DEPEND;

	/* KICK OFF CUSTOMER LIFECYCLE DEPENDENCY*/
	SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
					 '&SKYNETREDESIGN.\CUSTOMER LIFECYCLE DEPENDENCY.SAS'
					 -LOG '&SKYNETREDESIGN_LOGS.\CUSTOMER_LC_DEPENDENCY_DRIVER_&TIMESTAMP..LOG'
					 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
					 TASKNAME=CUST_LC_DEPEND
					 STATUS=CUST_LC_DEPEND;


WAITFOR _ALL_ DEAL_DEPEND TRAN_DEPEND DT_DEPEND DAILY_DEPEND CUST_DEPEND CUST_LC_DEPEND;


	/*GET TIME*/
	DATA _NULL_;
		CALL SYMPUTX('CURRENT_TIME',PUT(DATETIME(),DATEAMPM20.),'G');
	%RUNQUIT(&job,&sub1);

	%PUT &CURRENT_TIME;


	/*KICK OFF REST OF TDES*/
	/*KICK OFF ALL OTHER TDE'S THAT ARE NOT KICKED OFF IN THE DEPENDENCIES*/

	PROC SQL;
		CREATE TABLE DASHBOARD_LIST AS
		SELECT DISTINCT DASHBOARD_NAME
			  ,DEPENDENCIES
		FROM SKY.TDE_DEPENDENCY_DATAMART
		WHERE 
	;
	QUIT;



/*EMAIL TEAM*/
	OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;
	FILENAME MYMAIL EMAIL; 
	DATA _NULL_;
	   FILE MYMAIL
			TO=('BI_DATA@ADVANCEAMERICA.NET','SHOPKINS@ADVANCEAMERICA.NET','BI_REPORTING@ADVANCEAMERICA.NET')
		    FROM=('SKYNET@COMPLETE.NET')
	     SUBJECT="SKYNET DEPENDENCY PROGRAMS COMPLETED - SKYNET DEPENDENT TDE'S KICKED OFF - &CURRENT_TIME ";
	RUN;