	%MACRO EADV_DRIVER_DECISION();
						/*CUSTOMER EADV*/
						%IF &CUST_EADV_STATUS. = NOT_COMPLETE AND %EVAL(&CUST_EADV_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\EADV_CUSTOMER.SAS'
												-LOG '&CUST_LOGPATH.\EADV_CUST_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=EADV_CUST_DRIVE
								STATUS=EADV_CUST_DRIVE;
							%END;

						/*DEAL SUMMARY EADV*/
						%IF &DEAL_EADV_STATUS. = NOT_COMPLETE AND %EVAL(&DEAL_EADV_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&SKYNETREDESIGN.\EADV_DEALSUMMARY.SAS'
												 -LOG '&DEAL_LOGPATH.\EADV_DEALSUMMARY_DRIVER_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=DEAL_EADV_DRIVE
								STATUS=DEAL_EADV_DRIVE;
							%END;

						/*TRANSACTION TABLE EADV*/
						%IF &TRAN_EADV_STATUS. = NOT_COMPLETE AND %EVAL(&TRAN_EADV_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&SKYNETREDESIGN.\EADV_TRANSACTION.SAS'
												 -LOG '&TRAN_LOGPATH.\EADV_TRANSACTION_DRIVER_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=TRAN_EADV_DRIVE
								STATUS=TRAN_EADV_DRIVE;
							%END;

						/*DAILY SUMMARY EADV*/
						%IF &DAIL_EADV_STATUS. = NOT_COMPLETE AND %EVAL(&DAIL_EADV_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&SKYNETREDESIGN.\EADV_DAILY.SAS'
												 -LOG '&DAILY_LOGPATH.\DAILY_SUMMARY_EADV_DRIVER_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=DAILY_EADV_DRIVE
								STATUS=DAILY_EADV_DRIVE;
							%END;
	%MEND;

