%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SKYNET REDESIGN\DATAMART REDESIGN\DAILY\DAILY_ERROR_INPUTS.SAS";
LIBNAME SKYNET "E:\SHARED\CADA\SAS DATA\DATAMART\STDM";

LIBNAME TMP_TBLS ORACLE
	USER=&USER.
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=TEMPTABLES;


/*PICK DATE YOU WANT TO RUN IT FOR*/
%LET DATE_START="01SEP2018"D;
%LET INSTANCE = "QFUND5-6";
%LET INSTANCE_EMAIL = QFUND5-6;
/*---------------------------------*/



/*CUST NUM*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.DAILYSUM_CUST_NUM) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*CUST NUM*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_CUST) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	UPDATE BIOR.DATAMART_STATUS
	SET
	EADV_STATUS = "CUST_UPDATE"
	,QFUND1_INSTALL_STATUS = "CUST_UPDATE"
	,QFUND1_TITLE_STATUS = "CUST_UPDATE"
	,QFUND2_INSTALL_STATUS = "CUST_UPDATE"
	,QFUND3_TTOC_STATUS = "CUST_UPDATE"
	,QFUND3_TXTITLE_STATUS = "CUST_UPDATE"
	,QFUND3_TETL_STATUS = "CUST_UPDATE"
	,QFUND3_FAI_STATUS = "CUST_UPDATE"
	,QFUND4_PAYDAY_STATUS = "CUST_UPDATE"
	,QFUND4_TITLE_STATUS = "CUST_UPDATE"
	,QFUND5_PAYDAY_STATUS = "CUST_UPDATE"
	,QFUND5_INSTALL_STATUS = "CUST_UPDATE"
	,QFUND5_TITLE_STATUS = "CUST_UPDATE"
	,NG_STATUS = "CUST_UPDATE"
	,ONLINE_STATUS = "CUST_UPDATE"
	,LOC_STATUS = "CUST_UPDATE"
	,FUSE_STATUS = "CUST_UPDATE"
	WHERE SOURCE IN ('BIOR.TRANSPOSE_DAILY_SUMMARY','BIOR.O_DAILY_SUMMARY_ALL');
QUIT;

DATA _NULL_;
	/*CUSTOMER*/
	CALL SYMPUTX('CUST_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('CUST_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\DATAMART REDESIGN\CUSTOMER",'G');
	/*DEAL*/
	CALL SYMPUTX('DEAL_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('DEAL_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\DATAMART REDESIGN\DEAL",'G');
	/*TRAN*/
	CALL SYMPUTX('TRAN_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('TRAN_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\DATAMART REDESIGN\TRANSACTION",'G');
	/*DAILY*/
	CALL SYMPUTX('DAILY_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('DAILY_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\DATAMART REDESIGN\DAILY",'G');
	/*SKYNET RESIGN LOGS*/
	CALL SYMPUTX('SKYNETREDESIGN',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN",'G');
	CALL SYMPUTX('SKYNETREDESIGN_LOGS',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');
	CALL SYMPUTX('MONDAY_OR_NOT',(WEEKDAY(DATE())),'G');
RUN;


/*PROGRAM LOCATIONS*/
%LET WHEREPRGRMSAT_REDESIGN = E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN;

/*GET CUST NUMBERS*/

PROC SQL;
   CREATE TABLE PROD_DESC_CHANGE AS 
   SELECT /* BUSINESS_DATE */
            (DATEPART(t1.BUSINESS_DATE)) FORMAT=MMDDYY10. AS BUSINESS_DATE,
          t1.LOCATION_NBR, 
          t1.INSTANCE, 
          t1.PRODUCT, 
          /* PRODUCT_DESC */
            (CASE WHEN (INSTANCE = 'EAPROD1' AND T1.BUSINESS_DATE >= T2.DEALDATE  AND T2.DEALDATE ^= .) 
												    THEN "TX CSO Cash Advance" 
				  WHEN PRODUCTDESC = 'TX CSO' 		THEN 'EADV PAYDAY'
                  WHEN PRODUCTDESC = 'TEXAS TITLE' THEN 'TX TITLE' ELSE PRODUCTDESC END) AS PRODUCT_DESC, 
          /* NEW_CUST_CNT */
            (SUM(t1.NEW_CUST_CNT)) AS NEW_CUST_CNT, 
          /* REDEEM_CUST_CNT */
            (SUM(t1.REDEEM_CUST_CNT)) AS REDEEM_CUST_CNT, 
          /* NEW_REPEAT_CUST_CNT */
            (SUM(t1.NEW_REPEAT_CUST_CNT)) AS NEW_REPEAT_CUST_CNT, 
          /* REACTIVE_CUST_CNT */
            (SUM(t1.REACTIVE_CUST_CNT)) AS REACTIVE_CUST_CNT, 
          /* ACTIVE_CUST_CNT */
            (SUM(t1.ACTIVE_CUST_CNT)) AS ACTIVE_CUST_CNT, 
          /* INACTIVE_CUST_CNT */
            (SUM(t1.INACTIVE_CUST_CNT)) AS INACTIVE_CUST_CNT
      FROM BIOR.CUST_CATEGORY_DAILY_COUNT T1
	  LEFT JOIN SKYNET.TX_UC_DATEBYLOC AS T2
			ON (T1.LOCATION_NBR = T2.LOCNBR)
	  WHERE T1.BUSINESS_DATE >= DHMS(&DATE_START.,00,00,00) AND T1.INSTANCE = &INSTANCE.
      GROUP BY (CALCULATED BUSINESS_DATE),
               t1.LOCATION_NBR,
               t1.INSTANCE,
               t1.PRODUCT,
               (CALCULATED PRODUCT_DESC)
;
QUIT;

PROC SQL;
	DROP TABLE TMP_TBLS.CUST_COUNT_MERGE
;
QUIT;

PROC SQL;
	CREATE TABLE TMP_TBLS.CUST_COUNT_MERGE AS
	SELECT BUSINESS_DATE
		  ,LOCATION_NBR
		  ,INSTANCE
		  ,PRODUCT
		  ,PRODUCT_DESC
		  ,SUM(NEW_CUST_CNT,NEW_REPEAT_CUST_CNT)	AS NEW_CUST_CNT
		  ,REDEEM_CUST_CNT
		  ,REACTIVE_CUST_CNT
		  ,ACTIVE_CUST_CNT
		  ,INACTIVE_CUST_CNT
	FROM PROD_DESC_CHANGE
	WHERE INSTANCE = &INSTANCE.
;
QUIT;


/*DAILY ALL INDEX STAGING INDEX*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_DAIL_ALLCUST ON TEMPTABLES.CUST_COUNT_MERGE(INSTANCE,PRODUCT_DESC,LOCATION_NBR,BUSINESS_DATE,PRODUCT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*GET DAILY SUMMARY */

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PASSWORD=&PASSWORD. PATH="BIOR") ;
	EXECUTE (MERGE INTO BIOR.O_DAILY_SUMMARY_ALL BIOR
    USING TEMPTABLES.CUST_COUNT_MERGE UPSERT
        ON (BIOR.INSTANCE=UPSERT.INSTANCE 
		    AND BIOR.PRODUCT_DESC=UPSERT.PRODUCT_DESC 
			AND BIOR.LOCNBR=UPSERT.LOCATION_NBR
			AND BIOR.BUSINESSDT = UPSERT.BUSINESS_DATE
			AND BIOR.PRODUCT = UPSERT.PRODUCT)
        WHEN MATCHED THEN UPDATE
           SET BIOR.NEWCUSTCNTCOMPANY = UPSERT.NEW_CUST_CNT
		      ,BIOR.REDEEM_CUSTOMER_CNT = UPSERT.REDEEM_CUST_CNT
			  ,BIOR.REACTIVE_CUSTOMER_CNT = UPSERT.REACTIVE_CUST_CNT
			  ,BIOR.ACTIVE_CUST_CNT = UPSERT.ACTIVE_CUST_CNT
			  ,BIOR.INACTIVE_CUST_CNT = UPSERT.INACTIVE_CUST_CNT
) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*GET DAILY SUMMARY NOW*/
PROC SQL;
	CREATE TABLE ODASA AS
	SELECT *
	FROM BIOR.O_DAILY_SUMMARY_ALL
	WHERE BUSINESSDT >= DHMS(&DATE_START.,00,00,00) AND INSTANCE = &INSTANCE.
;
QUIT;

PROC FORMAT;
    PICTURE CHECKTHEDAY OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
    PICTURE CHECKTHETIME OTHER=%0H.%0M.%0S (DATATYPE=TIME);
RUN;

%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;


/* CREATE MACROS FOR BULKLOAD PATH AND TIMESTAMP */
DATA _NULL_;
	CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
    CALL SYMPUTX('PATH',"E:\SHARED\CADA\SAS DATA\DATAMART\SKYNET REDESIGN BULKLOAD LOGS\CUSTOMER\CL",'G');
    CALL SYMPUTX('PATHTWO',"E:\SHARED\CADA\SAS DATA\DATAMART\SKYNET REDESIGN BULKLOAD LOGS\CUSTOMER\CL\DIR2\",'G');
RUN;


PROC SQL;
    INSERT INTO SKY.DAILYSUM_CUST_NUM (BULKLOAD=YES BL_LOG="&PATH.\BL_&DATE..LOG" BL_DELETE_DATAFILE=YES 
                                                   BL_DEFAULT_DIR="&PATHTWO.")
    SELECT 
        *
    FROM ODASA;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXEC(INSERT INTO SKYNET.TRANSPOSE_DAILY_SUMMARY_CUST
		            SELECT
               PRODUCT ,PRODUCT_DESC ,POS ,INSTANCE ,BRANDCD ,BANKMODEL 
                ,COUNTRYCD ,STATE ,CITY ,ZIP ,ZONENBR ,ZONENAME ,REGIONNBR 
                ,REGIONRDO ,DIVISIONNBR ,DIVISIONDDO ,LOCNBR ,LOCATION_NAME 
                ,LOC_OPEN_DT ,LOC_CLOSE_DT ,BUSINESSDT ,LAST_REPORT_DT 
                ,LOC_LAST_REPORTED_DT ,LATITUDE ,LONGITUDE ,HOLIDAYNAME ,LASTTHURSDAY 
                ,THURSDAYWEEK
              ,KPINAME
              ,VALUE1
            FROM
            (
            SELECT 
               PRODUCT ,PRODUCT_DESC ,POS ,INSTANCE ,BRANDCD ,BANKMODEL 
                ,COUNTRYCD ,STATE ,CITY ,ZIP ,ZONENBR ,ZONENAME ,REGIONNBR 
                ,REGIONRDO ,DIVISIONNBR ,DIVISIONDDO ,LOCNBR ,LOCATION_NAME 
                ,LOC_OPEN_DT ,LOC_CLOSE_DT ,BUSINESSDT ,LAST_REPORT_DT 
                ,LOC_LAST_REPORTED_DT ,LATITUDE ,LONGITUDE ,HOLIDAYNAME ,LASTTHURSDAY 
                ,THURSDAYWEEK
              ,TOTADVRECV ,TOTADVFEERECV ,COMPLIANT_LOANS_OUTSTANDING 
                ,NEWCUSTCNTCOMPANY ,NET_REVENUE ,NEW_ORIGINATIONS 
                ,GROSS_REVENUE ,NET_WRITE_OFF ,WORAMTSUM ,TOTDEFAULTRECV
				,REACTIVE_CUSTOMER_CNT 
            FROM SKYNET.DAILYSUM_CUST_NUM
            GROUP BY
                PRODUCT ,PRODUCT_DESC ,POS ,INSTANCE ,BRANDCD ,BANKMODEL 
                ,COUNTRYCD ,STATE ,CITY ,ZIP ,ZONENBR ,ZONENAME ,REGIONNBR 
                ,REGIONRDO ,DIVISIONNBR ,DIVISIONDDO ,LOCNBR ,LOCATION_NAME 
                ,LOC_OPEN_DT ,LOC_CLOSE_DT ,BUSINESSDT ,LAST_REPORT_DT 
                ,LOC_LAST_REPORTED_DT ,LATITUDE ,LONGITUDE ,HOLIDAYNAME ,LASTTHURSDAY 
                ,THURSDAYWEEK                 
              ,TOTADVRECV ,TOTADVFEERECV ,COMPLIANT_LOANS_OUTSTANDING 
                ,NEWCUSTCNTCOMPANY ,NET_REVENUE ,NEW_ORIGINATIONS 
                ,GROSS_REVENUE ,NET_WRITE_OFF ,WORAMTSUM ,TOTDEFAULTRECV
				,REACTIVE_CUSTOMER_CNT  
                )
            UNPIVOT(
                VALUE1
                FOR KPINAME
                IN (   
                TOTADVRECV ,TOTADVFEERECV ,COMPLIANT_LOANS_OUTSTANDING 
                ,NEWCUSTCNTCOMPANY ,NET_REVENUE ,NEW_ORIGINATIONS 
                ,GROSS_REVENUE ,NET_WRITE_OFF ,WORAMTSUM ,TOTDEFAULTRECV
				,REACTIVE_CUSTOMER_CNT                       ))) BY ORACLE;
DISCONNECT FROM ORACLE;
QUIT;

/*MERGE INTO PRODUCTION TABLE*/
PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PASSWORD=&PASSWORD. PATH="BIOR");
	EXECUTE (MERGE INTO BIOR.TRANSPOSE_DAILY_SUMMARY BIOR
    USING SKYNET.TRANSPOSE_DAILY_SUMMARY_CUST UPSERT
        ON (BIOR.INSTANCE=UPSERT.INSTANCE 
		    AND BIOR.PRODUCT_DESC=UPSERT.PRODUCT_DESC 
			AND BIOR.LOCNBR=UPSERT.LOCNBR
			AND BIOR.BUSINESSDT = UPSERT.BUSINESSDT
			AND BIOR.PRODUCT = UPSERT.PRODUCT
			AND BIOR.KPINAME = UPSERT.KPINAME)
        WHEN MATCHED THEN UPDATE
           SET 
				/*BIOR.PRODUCT=UPSERT.PRODUCT,*/
				/*BIOR.PRODUCT_DESC=UPSERT.PRODUCT_DESC,*/
                BIOR.POS=UPSERT.POS,
				/*BIOR.INSTANCE=UPSERT.INSTANCE,*/
                BIOR.BRANDCD=UPSERT.BRANDCD,
                BIOR.BANKMODEL=UPSERT.BANKMODEL,
                BIOR.COUNTRYCD=UPSERT.COUNTRYCD,
                BIOR.STATE=UPSERT.STATE,
                BIOR.CITY=UPSERT.CITY,
                BIOR.ZIP=UPSERT.ZIP,
                BIOR.ZONENBR=UPSERT.ZONENBR,
                BIOR.ZONENAME=UPSERT.ZONENAME,
                BIOR.REGIONNBR=UPSERT.REGIONNBR,
                BIOR.REGIONRDO=UPSERT.REGIONRDO,
                BIOR.DIVISIONNBR=UPSERT.DIVISIONNBR,
				BIOR.DIVISIONDDO=UPSERT.DIVISIONDDO,
				/*BIOR.LOCNBR=UPSERT.LOCNBR,*/
                BIOR.LOCATION_NAME=UPSERT.LOCATION_NAME,
                BIOR.LOC_OPEN_DT=UPSERT.LOC_OPEN_DT,
                BIOR.LOC_CLOSE_DT=UPSERT.LOC_CLOSE_DT,
				/*BIOR.BUSINESSDT=UPSERT.BUSINESSDT,*/
                BIOR.LAST_REPORT_DT=UPSERT.LAST_REPORT_DT,
                BIOR.LOC_LAST_REPORTED_DT=UPSERT.LOC_LAST_REPORTED_DT,
                BIOR.LATITUDE=UPSERT.LATITUDE,
				BIOR.LONGITUDE=UPSERT.LONGITUDE,
                BIOR.HOLIDAYNAME=UPSERT.HOLIDAYNAME,
                BIOR.LASTTHURSDAY=UPSERT.LASTTHURSDAY,
                BIOR.THURSDAYWEEK=UPSERT.THURSDAYWEEK,
				/*BIOR.KPINAME = UPSERT.KPINAME,*/
				BIOR.VALUE1 = UPSERT.VALUE1
         WHEN NOT MATCHED
            THEN INSERT
                 (PRODUCT, 
		          PRODUCT_DESC, 
		          POS, 
		          INSTANCE, 
		          BRANDCD, 
		          BANKMODEL, 
		          COUNTRYCD, 
		          STATE, 
		          CITY, 
		          ZIP, 
		          ZONENBR, 
		          ZONENAME, 
		          REGIONNBR, 
		          REGIONRDO, 
		          DIVISIONNBR, 
		          DIVISIONDDO, 
		          LOCNBR, 
		          LOCATION_NAME, 
		          LOC_OPEN_DT, 
		          LOC_CLOSE_DT, 
		          BUSINESSDT, 
		          LAST_REPORT_DT, 
		          LOC_LAST_REPORTED_DT, 
		          LATITUDE, 
		          LONGITUDE, 
		          HOLIDAYNAME, 
		          LASTTHURSDAY, 
		          THURSDAYWEEK, 
				  KPINAME,
				  VALUE1)
            VALUES 
                 (UPSERT.PRODUCT, 
		          UPSERT.PRODUCT_DESC, 
		          UPSERT.POS, 
		          UPSERT.INSTANCE, 
		          UPSERT.BRANDCD, 
		          UPSERT.BANKMODEL, 
		          UPSERT.COUNTRYCD, 
		          UPSERT.STATE, 
		          UPSERT.CITY, 
		          UPSERT.ZIP, 
		          UPSERT.ZONENBR, 
		          UPSERT.ZONENAME, 
		          UPSERT.REGIONNBR, 
		          UPSERT.REGIONRDO, 
		          UPSERT.DIVISIONNBR, 
		          UPSERT.DIVISIONDDO, 
		          UPSERT.LOCNBR, 
		          UPSERT.LOCATION_NAME, 
		          UPSERT.LOC_OPEN_DT, 
		          UPSERT.LOC_CLOSE_DT, 
		          UPSERT.BUSINESSDT, 
		          UPSERT.LAST_REPORT_DT, 
		          UPSERT.LOC_LAST_REPORTED_DT, 
		          UPSERT.LATITUDE, 
		          UPSERT.LONGITUDE, 
		          UPSERT.HOLIDAYNAME, 
		          UPSERT.LASTTHURSDAY, 
		          UPSERT.THURSDAYWEEK, 
		          UPSERT.KPINAME,
				  UPSERT.VALUE1)
	) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*GET TIME*/
DATA _NULL_;
	CALL SYMPUTX('CURRENT_TIME',PUT(DATETIME(),DATEAMPM20.));
RUN;

%PUT &CURRENT_TIME;

PROC SQL;
	UPDATE BIOR.DATAMART_STATUS
	SET
	EADV_STATUS = "FINISHED"
	,QFUND1_INSTALL_STATUS = "FINISHED"
	,QFUND1_TITLE_STATUS = "FINISHED"
	,QFUND2_INSTALL_STATUS = "FINISHED"
	,QFUND3_TTOC_STATUS = "FINISHED"
	,QFUND3_TXTITLE_STATUS = "FINISHED"
	,QFUND3_TETL_STATUS = "FINISHED"
	,QFUND3_FAI_STATUS = "FINISHED"
	,QFUND4_PAYDAY_STATUS = "FINISHED"
	,QFUND4_TITLE_STATUS = "FINISHED"
	,QFUND5_PAYDAY_STATUS = "FINISHED"
	,QFUND5_INSTALL_STATUS = "FINISHED"
	,QFUND5_TITLE_STATUS = "FINISHED"
	,NG_STATUS = "FINISHED"
	,ONLINE_STATUS = "FINISHED"
	,LOC_STATUS = "FINISHED"
	,FUSE_STATUS = "FINISHED"
	WHERE SOURCE IN ('BIOR.TRANSPOSE_DAILY_SUMMARY','BIOR.O_DAILY_SUMMARY_ALL');
QUIT;

/*EMAIL TEAM*/
OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;
FILENAME MYMAIL EMAIL; 
DATA _NULL_;
   FILE MYMAIL
		TO=('BI_DATA@ADVANCEAMERICA.NET','SHOPKINS@ADVANCEAMERICA.NET','BI_REPORTING@ADVANCEAMERICA.NET')
	    FROM=('SKYNET@COMPLETE.NET')
     SUBJECT="CUSTOMER NUMBER DAILY/TRANSPOSE MERGE (&INSTANCE_EMAIL) COMPLETE - &CURRENT_TIME ";
RUN;





		/*GET DASHBOARDS THAT ONLY DEPEEND ON TRANSPOSE AND PASS THROUGH TO NEW VARIABLE*/

		PROC SQL;
			CREATE TABLE DASHBOARD_LIST AS
			SELECT DISTINCT DASHBOARD_NAME
				  ,DEPENDENCIES
			FROM SKY.TDE_DEPENDENCY_DATAMART
			WHERE DEPENDENCIES = 'BIOR.TRANSPOSE_DAILY_SUMMARY' AND TABLE_DEPENDENT_COUNT = 1
		;
		QUIT;

		%INCLUDE "&SKYNETREDESIGN.\TDE BAT UPLOAD.SAS";

		%LET TDY = %SYSFUNC(TODAY(),WEEKDATE30.);


		/*GET DASHBOARDS THAT ONLY DEPEEND ON DAILY AND PASS THROUGH TO NEW VARIABLE*/

		PROC SQL;
			CREATE TABLE DASHBOARD_LIST AS
			SELECT DISTINCT DASHBOARD_NAME
				  ,DEPENDENCIES
			FROM SKY.TDE_DEPENDENCY_DATAMART
			WHERE DEPENDENCIES = 'BIOR.O_DAILY_SUMMARY_ALL' AND TABLE_DEPENDENT_COUNT = 1
		;
		QUIT;

		%INCLUDE "&SKYNETREDESIGN.\TDE BAT UPLOAD.SAS";	



