	%MACRO NG_DRIVER_DECISION();
						/*CUSTOMER*/
						%IF &CUST_NG_STATUS. = NOT_COMPLETE 
								AND %EVAL(&CUST_NG_RUN_DATE. = .) %THEN 
							%DO;
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\NG_CUSTOMER.SAS'
												-LOG '&CUST_LOGPATH.\CUST_NG_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=NG_CUST_DRIVE
								STATUS=NG_CUST_DRIVE;							
							%END;
								

						/*TRANSACTION*/
						%IF &TRAN_NG_STATUS. = NOT_COMPLETE 
								AND %EVAL(&TRAN_NG_RUN_DATE. = .) %THEN 
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\NG_TRANSACTION.SAS'
												-LOG '&TRAN_LOGPATH.\TRAN_NG_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=NG_TRAN_DRIVE
								STATUS=NG_TRAN_DRIVE;							
							%END;

						/*DEALSUMMARY*/
						%IF &DEAL_NG_STATUS. = NOT_COMPLETE 
								AND %EVAL(&DEAL_NG_RUN_DATE. = .) %THEN 
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\NG_DEALSUMMARY.SAS'
												-LOG '&DEAL_LOGPATH.\DEAL_NG_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=NG_DEAL_DRIVE
								STATUS=NG_DEAL_DRIVE;
							%END;

						/*DAILY*/
						%IF &DAIL_NG_STATUS. = NOT_COMPLETE 
								AND %EVAL(&DAIL_NG_RUN_DATE. = .) %THEN 
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\NG_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_NG_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=NG_DAIL_DRIVE
								STATUS=NG_DAIL_DRIVE;
							%END;

	%MEND;