/*						%IF &DAILY_OL_STATUS. = NOT_COMPLETE AND &DAILY_OL_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET ONLINE_STATUS = 'RUNNING'
											   ,ONLINE_RUN_DATE = CURRENT_DATE
											   ,LOC_STATUS = 'RUNNING'
											   ,LOC_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF OL_DAILY*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP15_ONLINE_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\ONLINE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=ONLINE_DAILY
								STATUS=ONLINE_DAILY;

								/*KICK OFF LOC DAILY SUMMARY*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\LOC_DAILY_SUMMARY_AANET.SAS'
												-LOG '&DAILY_LOGPATH.\LOC_DAILY_SUMMARY_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=LOC_DS
								STATUS=LOC_DS;

								WAITFOR _ALL_ ONLINE_DAILY LOC_DS;

								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET ONLINE_STATUS = 'FINISHED'
											   ,ONLINE_COMPLETION_DATE = CURRENT_DATE
											   ,LOC_STATUS = 'FINISHED'
											   ,LOC_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT; 