	%MACRO ONLINE_DRIVER_DECISION();
						/*CUSTOMER*/
						%IF &CUST_OL_STATUS. = NOT_COMPLETE 
							AND %EVAL(&CUST_OL_RUN_DATE. = .) %THEN 
							%DO;
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\OL_CUSTOMER.SAS'
												-LOG '&CUST_LOGPATH.\CUST_OL_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OL_CUST_DRIVE
								STATUS=OL_CUST_DRIVE;							
							%END;
								
						/*TRANSACTION*/
						%IF &TRAN_OL_STATUS. = NOT_COMPLETE 
							AND %EVAL(&TRAN_OL_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\OL_TRANSACTION.SAS'
												-LOG '&TRAN_LOGPATH.\TRAN_OL_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OL_TRAN_DRIVE
								STATUS=OL_TRAN_DRIVE;							
							%END;

						/*DEALSUMMARY*/
						%IF &DEAL_OL_STATUS. = NOT_COMPLETE 
							AND %EVAL(&DEAL_OL_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\OL_DEALSUMMARY.SAS'
												-LOG '&DEAL_LOGPATH.\DEAL_OL_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OL_DEAL_DRIVE
								STATUS=OL_DEAL_DRIVE;
							%END;

						/*DAILY*/
						%IF &DAIL_OL_STATUS. = NOT_COMPLETE 
							AND %EVAL(&DAIL_OL_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\OL_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_OL_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OL_DAILY_DRIVE
								STATUS=OL_DAILY_DRIVE;
							%END;

	%MEND;