/*						%IF &DAILY_QF1QF2_STATUS. = NOT_COMPLETE AND &DAILY_QF1QF2_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND1_INSTALL_STATUS = 'RUNNING'
											   ,QFUND1_INSTALL_RUN_DATE = CURRENT_DATE
											   ,QFUND2_INSTALL_STATUS = 'RUNNING'
											   ,QFUND2_INSTALL_RUN_DATE = CURRENT_DATE
											   ,QFUND1_TITLE_STATUS = 'RUNNING'
											   ,QFUND1_TITLE_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND1_QFUND2_DAILY*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP3_QFUND1_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\QF1_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1_DAILY
								STATUS=QF1_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP4_QFUND2_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\QF2_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
							    TASKNAME=QF2_DAILY
							    STATUS=QF2_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP5_QFUND1_TITLE_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\QF1TITLE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1TITLE_DAILY
								STATUS=QF1TITLE_DAILY;

								WAITFOR _ALL_ QF1_DAILY QF2_DAILY QF1TITLE_DAILY;

								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND1_INSTALL_STATUS = 'FINISHED'
											   ,QFUND1_INSTALL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND2_INSTALL_STATUS = 'FINISHED'
											   ,QFUND2_INSTALL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND1_TITLE_STATUS = 'FINISHED'
											   ,QFUND1_TITLE_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;