
%PUT THERE IS NOT A QF1 DAILY SUMMARY PROGRAM;

/*						%IF &DAILY_EADV_STATUS. = NOT_COMPLETE AND &DAILY_EADV_RUN_DATE. = . %THEN*/
/*							%DO; */
/*								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;*/
/*								%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";*/
/*								/*ASSIGN FILE PATHS*/*/
/*								DATA _NULL_;*/
/*									/*CUSTOMER*/*/
/*									CALL SYMPUTX('CUST_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');*/
/*									CALL SYMPUTX('CUST_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\CUSTOMER",'G');*/
/*									/*DEAL*/*/
/*									CALL SYMPUTX('DEAL_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');*/
/*									CALL SYMPUTX('DEAL_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\DEAL",'G');*/
/*									/*TRAN*/*/
/*									CALL SYMPUTX('TRAN_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');*/
/*									CALL SYMPUTX('TRAN_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\TRANSACTION",'G');*/
/*									/*DAILY*/*/
/*									CALL SYMPUTX('DAILY_LOGPATH',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');*/
/*									CALL SYMPUTX('DAILY_FILE_PATH',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN\DATAMART REDESIGN\DAILY",'G');*/
/*									/*SKYNET RESIGN LOGS*/*/
/*									CALL SYMPUTX('SKYNETREDESIGN',"E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V2\SKYNET REDESIGN",'G');*/
/*									CALL SYMPUTX('SKYNETREDESIGN_LOGS',"E:\SHARED\CADA\LOGS\SKYNET V2",'G');*/
/*								RUN;*/
/**/
/**/
/*								/* CREATE TIMESTAMP */*/
/*								PROC FORMAT;*/
/*									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);*/
/*									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);*/
/*								RUN;*/
/**/
/*								DATA _NULL_;*/
/*									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');*/
/*								RUN;*/
/**/
/*								%PUT &TIMESTAMP;*/

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
/*								PROC SQL;*/
/*								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH='BIOR');*/
/*									EXECUTE(UPDATE BIOR.DATAMART_STATUS*/
/*											SET QFUND1_TITLE_STATUS = 'RUNNING'*/
/*											   ,QFUND1_TITLE_RUN_DATE = CURRENT_DATE*/
/*											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'*/
/*											)*/
/*									 BY ORACLE;*/
/*									 DISCONNECT FROM ORACLE;*/
/*								QUIT;*/
/*								*/
/*								/*KICK OFF QF1_DAILY*/*/
/*								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'*/
/*												 '&DAILY_FILE_PATH.\STDM_STEP5_QFUND1_TITLE_CURRENT.SAS'*/
/*												 -LOG '&DAILY_LOGPATH.\DAILY_QF1T_&TIMESTAMP..LOG'*/
/*												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"*/
/*								TASKNAME=DAILY_QF1T*/
/*								STATUS=DAILY_QF1T;*/
/**/
/*								WAITFOR _ALL_ DAILY_QF1T;*/
/**/
/*								/*UPDATE STATUS TABLE*/*/
/*								PROC SQL;*/
/*								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH='BIOR');*/
/*									EXECUTE(UPDATE BIOR.DATAMART_STATUS*/
/*											SET QFUND1_TITLE_STATUS = 'FINISHED'*/
/*											   ,QFUND1_TITLE_COMPLETION_DATE = CURRENT_DATE*/
/*											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'*/
/*											)*/
/*									 BY ORACLE;*/
/*									 DISCONNECT FROM ORACLE;*/
/*								QUIT;*/