/*						%IF &DEAL_QF1QF2_STATUS. = NOT_COMPLETE AND &DEAL_QF1QF2_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND1_INSTALL_STATUS = 'RUNNING'
											   ,QFUND1_INSTALL_RUN_DATE = CURRENT_DATE
											   ,QFUND2_INSTALL_STATUS = 'RUNNING'
											   ,QFUND2_INSTALL_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEAL_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND1_QFUND2_DEAL*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&DEAL_FILE_PATH.\SKYNET_STEP_2_QF12.SAS'
												 -LOG '&DEAL_LOGPATH.\QF12_DS_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF12_DEAL
								STATUS=QF12_DEAL;

								WAITFOR _ALL_ QF12_DEAL;

								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND1_INSTALL_STATUS = 'FINISHED'
											   ,QFUND1_INSTALL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND2_INSTALL_STATUS = 'FINISHED'
											   ,QFUND2_INSTALL_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEAL_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;