/*						%IF &DAILY_QFUND3_STATUS. = NOT_COMPLETE AND &DAILY_QFUND3_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											  SET 
											   QFUND3_TXTITLE_STATUS = 'RUNNING'
											   ,QFUND3_TXTITLE_RUN_DATE = CURRENT_DATE
											   ,QFUND3_TETL_STATUS = 'RUNNING'
											   ,QFUND3_TETL_RUN_DATE = CURRENT_DATE
											   ,QFUND3_TTOC_STATUS = 'RUNNING'
											   ,QFUND3_TTOC_RUN_DATE = CURRENT_DATE
											   ,QFUND3_FAI_STATUS = 'RUNNING'
											   ,QFUND3_FAI_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND3_DAILY*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP13_TTOC_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\TTOC_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
							 	TASKNAME=TTOC_DAILY
							 	STATUS=TTOC_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP8_FAI_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\FAI_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=FAI_DAILY
								STATUS=FAI_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP6_TXTITLE_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\TXTITLE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=TXTITLE_DAILY
								STATUS=TXTITLE_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP7_TETL_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\TETL_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=TETL_DAILY
								STATUS=TETL_DAILY;

								WAITFOR _ALL_ TTOC_DAILY FAI_DAILY TXTITLE_DAILY TETL_DAILY;

								/*UPDATE TABLE CURRENT DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											  SET 
											   QFUND3_TXTITLE_STATUS = 'FINISHED'
											   ,QFUND3_TXTITLE_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND3_TETL_STATUS = 'FINISHED'
											   ,QFUND3_TETL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND3_TTOC_STATUS = 'FINISHED'
											   ,QFUND3_TTOC_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND3_FAI_STATUS = 'FINISHED'
											   ,QFUND3_FAI_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;