/*						%IF &TRAN_QFUND3_STATUS. = NOT_COMPLETE AND &TRAN_QFUND3_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											  SET 
											   QFUND3_TXTITLE_STATUS = 'RUNNING'
											   ,QFUND3_TXTITLE_RUN_DATE = CURRENT_DATE
											   ,QFUND3_TETL_STATUS = 'RUNNING'
											   ,QFUND3_TETL_RUN_DATE = CURRENT_DATE
											   ,QFUND3_TTOC_STATUS = 'RUNNING'
											   ,QFUND3_TTOC_RUN_DATE = CURRENT_DATE
											   ,QFUND3_FAI_STATUS = 'RUNNING'
											   ,QFUND3_FAI_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND3_TRANSACTION*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_QF3_DAILYTT.SAS'
												 -LOG '&TRAN_LOGPATH.\QF3TT_TRAN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF3TT_TRAN
								STATUS=QF3TT_TRAN;


								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_QF3_DAILY.SAS'
												 -LOG '&TRAN_LOGPATH.\QF3_TRAN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF3_TRAN
								STATUS=QF3_TRAN;

								WAITFOR _ALL_ QF3TT_TRAN QF3_TRAN;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											  SET 
											   QFUND3_TXTITLE_STATUS = 'FINISHED'
											   ,QFUND3_TXTITLE_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND3_TETL_STATUS = 'FINISHED'
											   ,QFUND3_TETL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND3_TTOC_STATUS = 'FINISHED'
											   ,QFUND3_TTOC_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND3_FAI_STATUS = 'FINISHED'
											   ,QFUND3_FAI_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;