/*						%IF &TRAN_QFUND4_STATUS. = NOT_COMPLETE AND &TRAN_QFUND4_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND4_PAYDAY_STATUS = 'RUNNING'
											   ,QFUND4_PAYDAY_RUN_DATE = CURRENT_DATE
											   ,QFUND4_TITLE_STATUS = 'RUNNING'
											   ,QFUND4_TITLE_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND4_TRANSACTION*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_QF4_DAILYT.SAS'
												 -LOG '&TRAN_LOGPATH.\QF4T_TRAN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF4T_TRAN
								STATUS=QF4T_TRAN;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_QF4_DAILYP.SAS'
												 -LOG '&TRAN_LOGPATH.\QF4P_TRAN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF4P_TRAN
								STATUS=QF4P_TRAN;

								WAITFOR _ALL_ QF4T_TRAN QF4P_TRAN;


								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND4_PAYDAY_STATUS = 'FINISHED'
											   ,QFUND4_PAYDAY_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND4_TITLE_STATUS = 'FINISHED'
											   ,QFUND4_TITLE_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;