/*						%IF &DEAL_QFUND5_STATUS. = NOT_COMPLETE AND &DEAL_QFUND5_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND5_PAYDAY_STATUS = 'RUNNING'
											   ,QFUND5_PAYDAY_RUN_DATE = CURRENT_DATE
											   ,QFUND5_INSTALL_STATUS = 'RUNNING'
											   ,QFUND5_INSTALL_RUN_DATE = CURRENT_DATE
											   ,QFUND5_TITLE_STATUS = 'RUNNING'
											   ,QFUND5_TITLE_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEAL_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND5_DEAL_SUMMARY*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&DEAL_FILE_PATH.\SKYNET_STEP_10_OHCSO_ILP.SAS'
												 -LOG '&DEAL_LOGPATH.\QF5_ILP_DS_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_ILP_DEAL
								STATUS=QF5_ILP_DEAL;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&DEAL_FILE_PATH.\SKYNET_STEP_11_OHCSO_PDL.SAS'
												 -LOG '&DEAL_LOGPATH.\QF5_PDL_DS_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_PDL_DEAL
								STATUS=QF5_PDL_DEAL;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&DEAL_FILE_PATH.\SKYNET_STEP_12_OHCSO_TLP.SAS'
												 -LOG '&DEAL_LOGPATH.\QF5_TLP_DS_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_TLP_DEAL
								STATUS=QF5_TLP_DEAL;

								WAITFOR _ALL_ QF5_ILP_DEAL QF5_PDL_DEAL QF5_TLP_DEAL;


								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND5_PAYDAY_STATUS = 'FINISHED'
											   ,QFUND5_PAYDAY_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND5_INSTALL_STATUS = 'FINISHED'
											   ,QFUND5_INSTALL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND5_TITLE_STATUS = 'FINISHED'
											   ,QFUND5_TITLE_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEAL_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT; 