/*						%IF &TRAN_QFUND5_STATUS. = NOT_COMPLETE AND &TRAN_QFUND5_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND5_PAYDAY_STATUS = 'RUNNING'
											   ,QFUND5_PAYDAY_RUN_DATE = CURRENT_DATE
											   ,QFUND5_INSTALL_STATUS = 'RUNNING'
											   ,QFUND5_INSTALL_RUN_DATE = CURRENT_DATE
											   ,QFUND5_TITLE_STATUS = 'RUNNING'
											   ,QFUND5_TITLE_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;

								/*KICK OFF QFUND5_TRANSACTION*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_QF5_DAILY.SAS'
												 -LOG '&TRAN_LOGPATH.\QF5_TRAN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_TRAN
								STATUS=QF5;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TEMPTABLES_5_YEAR_MAINTAIN.SAS'
												 -LOG '&TRAN_LOGPATH.\5_YEAR_MAINTAIN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=YEARMAIN
								STATUS=YEARMAIN;

								WAITFOR _ALL_ YEARMAIN;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\DELETE_NCP_BIOR.SAS'
												 -LOG '&TRAN_LOGPATH.\DELETE_NCP_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=DELETENCP
								STATUS=DELETENCP;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_NCP_DAILY.SAS'
												 -LOG '&TRAN_LOGPATH.\NCP_TRAN_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=NCP
								STATUS=NCP;

								WAITFOR _ALL_ NCP DELETENCP QF5_TRAN;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&TRAN_FILE_PATH.\TRANSACTION_TABLE_ROLLUP_QF5_DAILY.SAS'
												 -LOG '&TRAN_LOGPATH.\ROLLUP_QF5_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=ROLLUPQF5
								STATUS=ROLLUPQF5;

								WAITFOR _ALL_ ROLLUPQF5;

								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND5_PAYDAY_STATUS = 'FINISHED'
											   ,QFUND5_PAYDAY_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND5_INSTALL_STATUS = 'FINISHED'
											   ,QFUND5_INSTALL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND5_TITLE_STATUS = 'FINISHED'
											   ,QFUND5_TITLE_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DEALTRANSACTION_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;