/*						%IF &DAILY_QFUND5_STATUS. = NOT_COMPLETE AND &DAILY_QFUND5_RUN_DATE. = . %THEN*/
/*							%DO; */
								OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT;
								%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\PATHS.SAS";



								/* CREATE TIMESTAMP */
								PROC FORMAT;
									PICTURE WHATDAYISIT OTHER=%0Y.%0M.%0D (DATATYPE=DATE);
									PICTURE WHATTIMEISIT OTHER=%0H.%0M.%0S (DATATYPE=TIME);
								RUN;

								DATA _NULL_;
									CALL SYMPUTX('TIMESTAMP',TRANWRD(PUT(DATETIME(),DATETIME20.),':','.'),'G');
								RUN;

								%PUT &TIMESTAMP;

								/*UPDATE TABLE WITH RUNNING FLAG AND CURRENT RUN DATE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND5_PAYDAY_STATUS = 'RUNNING'
											   ,QFUND5_PAYDAY_RUN_DATE = CURRENT_DATE
											   ,QFUND5_INSTALL_STATUS = 'RUNNING'
											   ,QFUND5_INSTALL_RUN_DATE = CURRENT_DATE
											   ,QFUND5_TITLE_STATUS = 'RUNNING'
											   ,QFUND5_TITLE_RUN_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;
								
								/*KICK OFF QFUND5_DAILY_SUMMARY*/
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP9_OHCSO_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\OHCSO_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OHCSO_DAILY
								STATUS=OHCSO_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP10_OHCSO_TITLE_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\OHCSOTITLE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OHCSOTITLE_DAILY
								STATUS=OHCSOTITLE_DAILY;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&DAILY_FILE_PATH.\STDM_STEP11_OHCSO_PAYDAY_CURRENT.SAS'
												-LOG '&DAILY_LOGPATH.\OHCSOPAYDAY_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OHCSOPAYDAY_DAILY
								STATUS=OHCSOPAYDAY_DAILY;

								WAITFOR _ALL_ OHCSO_DAILY OHCSOTITLE_DAILY OHCSOPAYDAY_DAILY;


								/*UPDATE STATUS TABLE*/
								PROC SQL;
								CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
									EXECUTE(UPDATE BIOR.DATAMART_STATUS
											SET QFUND5_PAYDAY_STATUS = 'FINISHED'
											   ,QFUND5_PAYDAY_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND5_INSTALL_STATUS = 'FINISHED'
											   ,QFUND5_INSTALL_COMPLETION_DATE = CURRENT_DATE
											   ,QFUND5_TITLE_STATUS = 'FINISHED'
											   ,QFUND5_TITLE_COMPLETION_DATE = CURRENT_DATE
											WHERE SOURCE = 'BIOR.O_DAILY_SUMMARY_ALL'
											)
									 BY ORACLE;
									 DISCONNECT FROM ORACLE;
								QUIT;