	%MACRO QFUND1_DRIVER_DECISION();
						/*CUSTOMER*/
						%IF &CUST_QF1_INSTALL_STATUS. = NOT_COMPLETE 
								AND &CUST_QF1_TITLE_STATUS. = NOT_COMPLETE 
								AND %EVAL(&CUST_QF1_INSTALL_RUN_DATE. = .) 
								AND %EVAL(CUST_QF1_TITLE_RUN_DATE. = .) %THEN
							%DO;
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF1_CUSTOMER.SAS'
												-LOG '&CUST_LOGPATH.\QF1_CUSTOMER_DRIVE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1_CUST_DRIVE
								STATUS=QF1_CUST_DRIVE;
							%END;
								

						/*TRANSACTION*/
						%IF &TRAN_QF1_INSTALL_STATUS. = NOT_COMPLETE 
							AND %EVAL(&TRAN_QF1_INSTALL_RUN_DATE. = .)
							AND &TRAN_QF1_TITLE_STATUS. = NOT_COMPLETE 
							AND %EVAL(&TRAN_QF1_TITLE_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF1_TRANSACTION.SAS'
												-LOG '&TRAN_LOGPATH.\QF1_TRANSACTION_DRIVE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1_TRAN_DRIVE
								STATUS=QF1_TRAN_DRIVE;

							%END;

						/*DEALSUMMARY*/
						%IF /*&DEAL_QF1_INSTALL_STATUS. = NOT_COMPLETE 
							AND &DEAL_QF1_INSTALL_RUN_DATE. = .
							AND*/ &DEAL_QF1_TITLE_STATUS. = NOT_COMPLETE 
							AND %EVAL(&DEAL_QF1_TITLE_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF1_DEALSUMMARY.SAS'
												-LOG '&DEAL_LOGPATH.\QF1_DEALSUMMARY_DRIVE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1_DEAL_DRIVE
								STATUS=QF1_DEAL_DRIVE;
							%END;

						/*DAILY*/
						%IF &DAIL_QF1_INSTALL_STATUS. = NOT_COMPLETE 
							AND %EVAL(&DAIL_QF1_INSTALL_RUN_DATE. = .)
							AND &DAIL_QF1_TITLE_STATUS. = NOT_COMPLETE 
							AND %EVAL(&DAIL_QF1_TITLE_RUN_DATE. = .) %THEN
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF1_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\QF1_DAILY_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1_DAILY_DRIVE
								STATUS=QF1_DAILY_DRIVE;
							%END;

	%MEND;