	%MACRO QFUND5_DRIVER_DECISION();
						/*CUSTOMER*/
						%IF &CUST_QF5_PAYDAY_STATUS. = NOT_COMPLETE
							AND %EVAL(&CUST_QF5_PAYDAY_RUN_DATE. = .)
							AND &CUST_QF5_INSTALL_STATUS. = NOT_COMPLETE
							AND %EVAL(&CUST_QF5_INSTALL_RUN_DATE. = .)
							AND &CUST_QF5_TITLE_STATUS. = NOT_COMPLETE
							AND %EVAL(&CUST_QF5_TITLE_RUN_DATE. = .)   %THEN 
							%DO;
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF5_CUSTOMER.SAS'
												-LOG '&CUST_LOGPATH.\CUST_QF5_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_CUST_DRIVE
								STATUS=QF5_CUST_DRIVE;							
							%END;
								

						/*TRANSACTION*/
						%IF &TRAN_QF5_PAYDAY_STATUS. = NOT_COMPLETE
							AND %EVAL(&TRAN_QF5_PAYDAY_RUN_DATE. = .)
							AND &TRAN_QF5_INSTALL_STATUS. = NOT_COMPLETE
							AND %EVAL(&TRAN_QF5_INSTALL_RUN_DATE. = .)
							AND &TRAN_QF5_TITLE_STATUS. = NOT_COMPLETE
							AND %EVAL(&TRAN_QF5_TITLE_RUN_DATE. = .)   %THEN 
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF5_TRANSACTION.SAS'
												-LOG '&TRAN_LOGPATH.\TRAN_QF5_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_TRAN_DRIVE
								STATUS=QF5_TRAN_DRIVE;							
							%END;

						/*DEALSUMMARY*/
						%IF &DEAL_QF5_PAYDAY_STATUS. = NOT_COMPLETE
							AND %EVAL(&DEAL_QF5_PAYDAY_RUN_DATE. = .)
							AND &DEAL_QF5_INSTALL_STATUS. = NOT_COMPLETE
							AND %EVAL(&DEAL_QF5_INSTALL_RUN_DATE. = .)
							AND &DEAL_QF5_TITLE_STATUS. = NOT_COMPLETE
							AND %EVAL(&DEAL_QF5_TITLE_RUN_DATE. = .)   %THEN 
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF5_DEALSUMMARY.SAS'
												-LOG '&DEAL_LOGPATH.\DEAL_QF5_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_DEAL_DRIVE
								STATUS=QF5_DEAL_DRIVE;
							%END;

						/*DAILY*/
						%IF &DAIL_QF5_PAYDAY_STATUS. = NOT_COMPLETE
							AND %EVAL(&DAIL_QF5_PAYDAY_RUN_DATE. = .)
							AND &DAIL_QF5_INSTALL_STATUS. = NOT_COMPLETE
							AND %EVAL(&DAIL_QF5_INSTALL_RUN_DATE. = .)
							AND &DAIL_QF5_TITLE_STATUS. = NOT_COMPLETE
							AND %EVAL(&DAIL_QF5_TITLE_RUN_DATE. = .)   %THEN 
							%DO; 
								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF5_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_QF5_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_DAILY_DRIVE
								STATUS=QF5_DAILY_DRIVE;
							%END;

	%MEND;