								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												 '&SKYNETREDESIGN.\EADV_DAILY.SAS'
												 -LOG '&DAILY_LOGPATH.\DAILY_SUMMARY_EADV_DRIVER_&TIMESTAMP..LOG'
												 -CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=DAILY_EADV_DRIVE
								STATUS=DAILY_EADV_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF1_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\QF1_DAILY_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1_DAILY_DRIVE
								STATUS=QF1_DAILY_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF2_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\QF2_DAILY_DRIVE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF2_DAILY_DRIVE
								STATUS=QF2_DAILY_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF1_QF2_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\QF1_QF2_DAILY_DRIVE_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF1QF2_DAILY_DRIVE
								STATUS=QF1QF2_DAILY_DRIVE;


								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF3_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_QF3_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF3_DAILY_DRIVE
								STATUS=QF3_DAILY_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF4_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_QF4_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF4_DAIL_DRIVE
								STATUS=QF4_DAIL_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\QF5_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_QF5_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=QF5_DAILY_DRIVE
								STATUS=QF5_DAILY_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\NG_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_NG_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=NG_DAIL_DRIVE
								STATUS=NG_DAIL_DRIVE;

								SYSTASK COMMAND "'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SAS.EXE'
												'&SKYNETREDESIGN.\OL_DAILY.SAS'
												-LOG '&DAILY_LOGPATH.\DAILY_OL_DRIVER_&TIMESTAMP..LOG'
												-CONFIG 'C:\PROGRAM FILES\SASHOME\SASFOUNDATION\9.4\SASV9.CFG'"
								TASKNAME=OL_DAILY_DRIVE
								STATUS=OL_DAILY_DRIVE;
