/***************************************************************************************
Sub Program	: DEAL_ERROR_INPUTS
Main		: ERROR_CHECK
Purpose		: Inputs needed to run MASTER_ERROR_CHECK in each job & sub-program
Programmer  : Spencer Hopkins, JUSTIN HUBBARD
****************************************************************************************/

* INCLUDE MASTER_ERROR_CHECK PROGRAM;
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SAS MACRO\MASTER_ERROR_CHECK.SAS";

/*
============================================================================= 
     INPUTS & SETUP
=============================================================================
*/

* NAME OF PROGRAM/JOB;
%LET JOB = DAILY DATAMART;

* NAME(S) OF SUB PROGRAMS INCLUDED IN JOB;
%LET SUB1 = EADV INPUT;
%LET SUB2 = QF1 INPUT;
%LET SUB3 = QF2 INPUT;
%LET SUB4 = QF1T INPUT;
%LET SUB5 = TXTITLE INPUT;
%LET SUB6 = TETL INPUT;
%LET SUB7 = TTOC INPUT;
%LET SUB8 = FAI INPUT;
%LET SUB9 = ECA INPUT;
%LET SUB10 = QF5I INPUT;
%LET SUB11 = QF5TLP INPUT;
%LET SUB12 = QF5PDL INPUT;
%LET SUB13 = NG INPUT;
%LET SUB14 = ONLINE INPUT;
%LET SUB15 = FUSE INPUT;
%LET SUB16 = LOC INPUT;

/*UPLOAD STEPS*/
%LET SUB16 = UPLOAD_EADV;
%LET SUB17 = UPLOAD_QF1;
%LET SUB18 = UPLOAD_QF2;
%LET SUB19 = UPLOAD_QF1T;
%LET SUB20 = UPLOAD_TXTITLE;
%LET SUB21 = UPLOAD_TETL;
%LET SUB22 = UPLOAD_TTOC;
%LET SUB23 = UPLOAD_FAI;
%LET SUB24 = UPLOAD_ECA;
%LET SUB25 = UPLOAD_QF5I;
%LET SUB26 = UPLOAD_QF5TLP;
%LET SUB27 = UPLOAD_QF5PDL;
%LET SUB28 = UPLOAD_NG;
%LET SUB29 = UPLOAD_ONLINE;
%LET SUB30 = UPLOAD_FUSE;

/*TRANPOSE STEPS*/
%LET SUB30 = TRANSPOSE_EADV;
%LET SUB31 = TRANSPOSE_QF1;
%LET SUB32 = TRANSPOSE_QF2;
%LET SUB33 = TRANSPOSE_QF1T;
%LET SUB34 = TRANSPOSE_TXTITLE;
%LET SUB35 = TRANSPOSE_TETL;
%LET SUB36 = TRANSPOSE_TTOC;
%LET SUB37 = TRANSPOSE_FAI;
%LET SUB38 = TRANSPOSE_ECA;
%LET SUB39 = TRANSPOSE_QF5I;
%LET SUB40 = TRANSPOSE_QF5TLP;
%LET SUB41 = TRANSPOSE_QF5PDL;
%LET SUB42 = TRANSPOSE_NG;
%LET SUB43 = TRANSPOSE_ONLINE;
%LET SUB44 = TRANSPOSE_FUSE;


* NAME OF TEMP ERROR TABLE;
%LET TEMP_TBL = DAILY_TEMP_ERROR;

* PEOPLE WHO NEED TO RECEIVE ERROR EMAIL;
%LET PPL_TO_EMAIL = 'SHOPKINS@ADVANCEAMERICA.NET','JHUBBARD@ADVANCEAMERICA.NET','JROSE@ADVANCEAMERICA.NET','RMUGABE@ADVANCEAMERICA.NET','ADOBBINS@ADVANCEAMERICA.NET';

