/*STAGING TABLES DAILY SUMMARY*/

/*EADV*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_EADV
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_EADV
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_EADV ON SKYNET.DAILYSUM_DATAMART_EADV(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*QFUND1*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF1
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF1
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF1 ON SKYNET.DAILYSUM_DATAMART_QF1(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*QFUND2*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF2
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF2
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF2 ON SKYNET.DAILYSUM_DATAMART_QF2(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*QFUND1 TITLE*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF1T
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF1T
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF1T ON SKYNET.DAILYSUM_DATAMART_QF1T(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*QFUND3 TXTITLE*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF3
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF3
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF3 ON SKYNET.DAILYSUM_DATAMART_QF3(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*QFUND3 TETL*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_TETL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_TETL
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_TETL ON SKYNET.DAILYSUM_DATAMART_TETL(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*QFUND3 TTOC*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_TTOC
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_TTOC
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_TTOC ON SKYNET.DAILYSUM_DATAMART_TTOC(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND3 FAI*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_FAI
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_FAI
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_FAI ON SKYNET.DAILYSUM_DATAMART_FAI(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND4*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF4
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF4
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF4 ON SKYNET.DAILYSUM_DATAMART_QF4(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND5 INSTALLMENT*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF5I
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF5I
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF5I ON SKYNET.DAILYSUM_DATAMART_QF5I(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND5 TITLE*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF5T
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF5T
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF5T ON SKYNET.DAILYSUM_DATAMART_QF5T(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND5 PAYDAY*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_QF5P
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_QF5P
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_QF5P ON SKYNET.DAILYSUM_DATAMART_QF5P(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*NEXTGEN*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_NG
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_NG
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_NG ON SKYNET.DAILYSUM_DATAMART_NG(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*ONLINE*/

PROC SQL;
	DROP TABLE SKY.DAILYSUM_DATAMART_OL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.DAILYSUM_DATAMART_OL
	LIKE BIOR.ODASA_CHANNELCD_TEST
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_OL ON SKYNET.DAILYSUM_DATAMART_OL(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(CREATE INDEX IDX_O_CN_DS_CUST ON SKYNET.DAILYSUM_CUST_NUM(INSTANCE,PRODUCT_DESC,PRODUCT,LOCNBR,BUSINESSDT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;








/*TRANSPOSE INDEX*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_EADV_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_EADV(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF1_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF1(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF2_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF2(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF1T_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF1T(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF3_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF3(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_TETL_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_TETL(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_TTOC_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_TTOC(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_FAI_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_FAI(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF4_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF4(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF5I_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF5I(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF5T_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF5T(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_QF5P_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_QF5P(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_NG_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_NG(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_TRANPOSE_OL_ALL ON SKYNET.TRANSPOSE_DAILY_SUMMARY_OL(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;*/
	EXECUTE(CREATE INDEX IDX_O_TRANSPOSE_IDX_THING ON BIOR.TRANSPOSE_DAILY_SUMMARY(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*DAILY ALL INDEX STAGING INDEX*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_EADV_ALL ON SKYNET.DAILYSUM_DATAMART_EADV(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF1_ALL ON SKYNET.DAILYSUM_DATAMART_QF1(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF2_ALL ON SKYNET.DAILYSUM_DATAMART_QF2(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF1T_ALL ON SKYNET.DAILYSUM_DATAMART_QF1T(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF3_ALL ON SKYNET.DAILYSUM_DATAMART_QF3(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_TETL_ALL ON SKYNET.DAILYSUM_DATAMART_TETL(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_TTOC_ALL ON SKYNET.DAILYSUM_DATAMART_TTOC(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_FAI_ALL ON SKYNET.DAILYSUM_DATAMART_FAI(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF4_ALL ON SKYNET.DAILYSUM_DATAMART_QF4(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF5I_ALL ON SKYNET.DAILYSUM_DATAMART_QF5I(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF5T_ALL ON SKYNET.DAILYSUM_DATAMART_QF5T(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_QF5P_ALL ON SKYNET.DAILYSUM_DATAMART_QF5P(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_NG_ALL ON SKYNET.DAILYSUM_DATAMART_NG(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
/*	EXECUTE(CREATE INDEX IDX_O_DAIL_OL_ALL ON SKYNET.DAILYSUM_DATAMART_OL(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;*/
	EXECUTE(CREATE INDEX IDX_O_DAIL_ALL ON BIOR.O_DAILY_SUMMARY_ALL(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


