%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
LIBNAME SKYNET "E:\SHARED\CADA\SAS DATA\DATAMART\STDM";


LIBNAME EDW ORACLE
	USER=&USER
	PW=&PASSWORD
	PATH=EDWPRD
	SCHEMA=EDW;

DATA PNL_INTIAL_PULL;
	SET EDW.QF_BADDEBT_PNLAMT;
	BUSINESSDT = DATEPART(BUSINESS_DATE);
	WHERE BUSINESS_DATE >= '01APR2017:00:00:00'DT;
	FORMAT BUSINESSDT MMDDYY10.;
RUN;

PROC SQL;
	CREATE TABLE WORK.QFUND_PNL AS 
		SELECT 
			STORE_NUMBER AS LOCNBR
		   ,CASE WHEN SOURCE_SYSTEM = 'QFUND5' THEN 'QFUND5-6' ELSE SOURCE_SYSTEM END AS INSTANCE
		   ,PRODUCT_TYPE
		   ,BUSINESSDT
		   ,BAD_DEBT AS GROSS_WRITE_OFF
		   ,-BADDEBT_PMT AS WORAMTSUM
		   ,-PNL_AMT AS GROSS_REVENUE
		   ,SUM(BAD_DEBT,BADDEBT_PMT) AS NET_WRITE_OFF
		   ,SUM(-PNL_AMT,(-SUM(BAD_DEBT,BADDEBT_PMT))) AS NET_REVENUE
		FROM WORK.PNL_INTIAL_PULL
	WHERE COMPRESS(PRODUCT_TYPE) ^= 'MISC'
;
QUIT;

/*-------------*/
/* QFUND 1 ILP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND1_ILP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'ILP' THEN 'INSTALLMENT' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,CASE WHEN LOC.ST_PVC_CD IN('IL','WI','DE','CO') THEN 'IPDL'
		         ELSE 'MULTISTATE INSTALLMENT'
		    END AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'STANDARD' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'ILP' AND INSTANCE = 'QFUND1'
;
QUIT;

/*-------------*/
/* QFUND 1 TLP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND1_TLP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'TLP' THEN 'TITLE' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'MULTISTATE TITLE' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'STANDARD' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'TLP' AND INSTANCE = 'QFUND1'
;
QUIT;

/*-------------*/
/* QFUND 2 ILP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND2_ILP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'ILP' THEN 'INSTALLMENT' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,CASE WHEN LOC.ST_PVC_CD IN('IL','WI','DE','CO') THEN 'IPDL'
		         ELSE 'MULTISTATE INSTALLMENT'
		    END AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'STANDARD' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'ILP' AND INSTANCE = 'QFUND2'
;
QUIT;

/*-------------*/
/* QFUND 3 TLP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND3_TLP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'TLP' THEN 'TITLE' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'TX TITLE' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'TLP' AND INSTANCE = 'QFUND3'
;
QUIT;

/*--------------*/
/* QFUND 3 TETL */
/*--------------*/
PROC SQL;
	CREATE TABLE QFUND3_TETL AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) IN('TETL','TETL2') THEN 'INSTALLMENT' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'TX TETL' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) IN('TETL','TETL2') AND INSTANCE = 'QFUND3'
;
QUIT;

/*--------------*/
/* QFUND 3 TTOC */
/*--------------*/
PROC SQL;
	CREATE TABLE QFUND3_TTOC AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'TTOC' THEN 'TITLE' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'TX TTOC' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'TTOC' AND INSTANCE = 'QFUND3'
;
QUIT;

/*--------------*/
/* QFUND 3 FAI  */
/*--------------*/
PROC SQL;
	CREATE TABLE QFUND3_FAI AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'FAI' THEN 'INSTALLMENT' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'TX FAI' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'FAI' AND INSTANCE = 'QFUND3'
;
QUIT;

/*-------------*/
/* QFUND 4 TLP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND4_TLP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) IN('TLP','VATLP') THEN 'TITLE' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'ECA TITLE' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'STANDARD' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,SUM(GROSS_WRITE_OFF) AS GROSS_WRITE_OFF
		   ,SUM(NET_WRITE_OFF) AS NET_WRITE_OFF
		   ,SUM(WORAMTSUM) AS WORAMTSUM
		   ,SUM(NET_REVENUE) AS NET_REVENUE
		   ,SUM(GROSS_REVENUE) AS GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) IN('TLP','VATLP') AND INSTANCE = 'QFUND4' AND ZONENBR IS NOT MISSING
	GROUP BY CALCULATED PRODUCT, CALCULATED PRODUCT_DESC, CALCULATED POS, INSTANCE, CALCULATED BANKMODEL, LOC.BRND_CD, LOC.CTRY_CD, LOC.ST_PVC_CD, LOC.ADR_CITY_NM, LOC.MAIL_CD, 
			 LOC.BUSN_UNIT_ID,  LOC.HIER_ZONE_NBR, LOC.HIER_ZONE_NM, LOC.HIER_RGN_NBR, LOC.HIER_RDO_NM, LOC.HIER_DIV_NBR, LOC.HIER_DDO_NM, LOCNBR,
			 LOC.LOC_NM, LOC.OPEN_DT, LOC.CLS_DT, BUSINESSDT
;
QUIT;

/*-------------*/
/* QFUND 4 PDL */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND4_PDL AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'PDL' THEN 'PAYDAY' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'ECA PAYDAY' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'STANDARD' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,SUM(GROSS_WRITE_OFF) AS GROSS_WRITE_OFF
		   ,SUM(NET_WRITE_OFF) AS NET_WRITE_OFF
		   ,SUM(WORAMTSUM) AS WORAMTSUM
		   ,SUM(NET_REVENUE) AS NET_REVENUE
		   ,SUM(GROSS_REVENUE) AS GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'PDL' AND INSTANCE = 'QFUND4' AND ZONENBR IS NOT MISSING
	GROUP BY CALCULATED PRODUCT, CALCULATED PRODUCT_DESC, CALCULATED POS, INSTANCE, LOC.BRND_CD, LOC.CTRY_CD, LOC.ST_PVC_CD, LOC.ADR_CITY_NM, LOC.MAIL_CD, 
			 LOC.BUSN_UNIT_ID,  LOC.HIER_ZONE_NBR, LOC.HIER_ZONE_NM, LOC.HIER_RGN_NBR, LOC.HIER_RDO_NM, LOC.HIER_DIV_NBR, LOC.HIER_DDO_NM, LOCNBR,
			 LOC.LOC_NM, LOC.OPEN_DT, LOC.CLS_DT, BUSINESSDT
;
QUIT;

/*-------------*/
/* QFUND 5 ILP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND5_ILP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'ILP' THEN 'INSTALLMENT' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'OH CSO INSTALLMENT' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'ILP' AND INSTANCE = 'QFUND5-6'
;
QUIT;

/*-------------*/
/* QFUND 5 TLP */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND5_TLP AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'TLP' THEN 'TITLE' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'OH CSO TITLE' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'TLP' AND INSTANCE = 'QFUND5-6'
;
QUIT;

/*-------------*/
/* QFUND 5 PDL */
/*-------------*/
PROC SQL;
	CREATE TABLE QFUND5_PDL AS
		SELECT
		    CASE WHEN COMPRESS(PRODUCT_TYPE) = 'PDL' THEN 'PAYDAY' 
			     ELSE PRODUCT_TYPE 
            END AS PRODUCT
		   ,'CSO CASH ADVANCE' AS PRODUCT_DESC
		   ,'QFUND' AS POS
		   ,INSTANCE
		   ,'CSO' AS BANKMODEL
		   ,LOC.BRND_CD AS BRANDCD
		   ,LOC.CTRY_CD AS COUNTRYCD
		   ,LOC.ST_PVC_CD AS STATE
		   ,LOC.ADR_CITY_NM AS CITY
		   ,LOC.MAIL_CD AS ZIP
		   ,LOC.BUSN_UNIT_ID AS BUSINESS_UNIT
		   ,LOC.HIER_ZONE_NBR AS ZONENBR
		   ,LOC.HIER_ZONE_NM AS ZONENAME
		   ,LOC.HIER_RGN_NBR AS REGIONNBR
		   ,LOC.HIER_RDO_NM AS REGIONRDO
		   ,LOC.HIER_DIV_NBR AS DIVISIONNBR
		   ,LOC.HIER_DDO_NM AS DIVISIONDDO
		   ,LOCNBR
		   ,LOC.LOC_NM AS LOCATION_NAME
		   ,LOC.OPEN_DT AS LOC_OPEN_DT
		   ,LOC.CLS_DT AS LOC_CLOSE_DT
		   ,BUSINESSDT
		   ,GROSS_WRITE_OFF
		   ,NET_WRITE_OFF
		   ,WORAMTSUM
		   ,NET_REVENUE
		   ,GROSS_REVENUE
		FROM WORK.QFUND_PNL PNL
		LEFT JOIN 
		EDW.D_LOCATION LOC
		ON(PNL.LOCNBR=LOC.LOC_NBR)
	WHERE COMPRESS(PRODUCT_TYPE) = 'PDL' AND INSTANCE = 'QFUND5-6'
;
QUIT;

/*------------------*/
/* COMBINE ALL DATA */
/*------------------*/
PROC SQL;
	CREATE TABLE WORK.QFUND_PNL_ALL_PRE AS
		SELECT * FROM WORK.QFUND1_ILP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND2_ILP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND1_TLP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND3_TETL
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND3_TLP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND3_TTOC
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND3_FAI
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND4_PDL
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND4_TLP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND5_ILP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND5_TLP
	OUTER UNION CORR
		SELECT * FROM WORK.QFUND5_PDL
;
QUIT;

DATA SKYNET.QFUND_PNL_ALL;
	SET WORK.QFUND_PNL_ALL_PRE;
WHERE SUM(GROSS_WRITE_OFF,WORAMTSUM,GROSS_REVENUE) ^= 0;
RUN;