%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";

LIBNAME BIOR ORACLE
	USER=&USER.
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=BIOR;

%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\STDM\STDM_LIBRARY_SCRIPT.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SKYNET REDESIGN\DATAMART REDESIGN\DAILY\DAILY_ERROR_INPUTS.SAS";
LIBNAME SKYNET "E:\SHARED\CADA\SAS DATA\DATAMART\STDM";


%LET ENDINGDT = INTNX('DAY',TODAY(),-1,'BEGINNING');

DATA _NULL_;
	CALL SYMPUTX('END_DT',PUT(&ENDINGDT,YYMMDDN8.),G);
RUN;

DATA FIRST.A&END_DT;
	X = &ENDINGDT;
	FORMAT X MMDDYY10.;
RUN;

PROC SQL;
   CREATE TABLE DAILY_SUMMARY_DIV AS 
   SELECT T1.PRODUCT, 
          T1.PRODUCT_DESC, 
          T1.POS, 
          T1.INSTANCE, 
          T1.BRANDCD, 
          T1.BANKMODEL, 
          T1.COUNTRYCD, 
          T1.STATE, 
          T1.BUSINESS_UNIT, 
          T1.ZONENBR, 
          T1.ZONENAME, 
          T1.REGIONNBR, 
          T1.REGIONRDO, 
          T1.DIVISIONNBR, 
          T1.DIVISIONDDO, 
          /* LOCATION_COUNT */
            (COUNT(T1.LOCNBR)) AS LOCATION_COUNT, 
          T1.HOLIDAYNAME, 
          T1.BUSINESSDT, 
          T1.LASTTHURSDAY, 
          T1.THURSDAYWEEK, 
          T1.LAST_REPORT_DT, 
          /* NEW_ADV_AMT */
            (SUM(T1.NEW_ADV_AMT)) FORMAT=16.2 LABEL="NEW_ADV_AMT" AS NEW_ADV_AMT, 
          /* NEW_ADVFEE_AMT */
            (SUM(T1.NEW_ADVFEE_AMT)) AS NEW_ADVFEE_AMT, 
          /* NEW_ORIGINATIONS */
            (SUM(T1.NEW_ORIGINATIONS)) AS NEW_ORIGINATIONS, 
          /* TOTADVRECV */
            (SUM(T1.TOTADVRECV)) FORMAT=16.2 AS TOTADVRECV, 
          /* TOTADVFEERECV */
            (SUM(T1.TOTADVFEERECV)) FORMAT=16.2 AS TOTADVFEERECV, 
          /* COMPLIANT_LOANS_OUTSTANDING */
            (SUM(T1.COMPLIANT_LOANS_OUTSTANDING)) AS COMPLIANT_LOANS_OUTSTANDING, 
          /* DEFAULT_LOANS_OUTSTANDING */
            (SUM(T1.DEFAULT_LOANS_OUTSTANDING)) AS DEFAULT_LOANS_OUTSTANDING, 
          /* TOTDEFAULTRECV */
            (SUM(T1.TOTDEFAULTRECV)) FORMAT=16.2 AS TOTDEFAULTRECV, 
          /* TOTDEFAULTFEERECV */
            (SUM(T1.TOTDEFAULTFEERECV)) FORMAT=16.2 AS TOTDEFAULTFEERECV, 
          /* NSF_AMOUNT */
            (SUM(T1.NSF_AMOUNT)) FORMAT=16.2 AS NSF_AMOUNT, 
          /* NSF_PAYMENT_AMOUNT */
            (SUM(T1.NSF_PAYMENT_AMOUNT)) FORMAT=16.2 AS NSF_PAYMENT_AMOUNT, 
          /* NSF_PREPAYMENT_AMOUNT */
            (SUM(T1.NSF_PREPAYMENT_AMOUNT)) FORMAT=16.2 AS NSF_PREPAYMENT_AMOUNT, 
          /* WOAMTSUM */
            (SUM(T1.WOAMTSUM)) FORMAT=16.2 AS WOAMTSUM, 
          /* WOCNT */
            (SUM(T1.WOCNT)) AS WOCNT, 
          /* WOBAMTSUM */
            (SUM(T1.WOBAMTSUM)) FORMAT=16.2 AS WOBAMTSUM, 
          /* WOBCNT */
            (SUM(T1.WOBCNT)) AS WOBCNT, 
          /* WORAMTSUM */
            (SUM(T1.WORAMTSUM)) FORMAT=16.2 AS WORAMTSUM, 
          /* WORCNT */
            (SUM(T1.WORCNT)) AS WORCNT, 
          /* CASHAGAIN_COUNT */
            (SUM(T1.CASHAGAIN_COUNT)) FORMAT=16.2 AS CASHAGAIN_COUNT, 
          /* BUYBACK_COUNT */
            (SUM(T1.BUYBACK_COUNT)) FORMAT=16.2 AS BUYBACK_COUNT, 
          /* DEPOSIT_COUNT */
            (SUM(T1.DEPOSIT_COUNT)) FORMAT=16.2 AS DEPOSIT_COUNT, 
          /* GROSS_REVENUE */
            (SUM(T1.GROSS_REVENUE)) FORMAT=16.2 AS GROSS_REVENUE, 
          /* GROSS_WRITE_OFF */
            (SUM(T1.GROSS_WRITE_OFF)) FORMAT=16.2 AS GROSS_WRITE_OFF, 
          /* NET_WRITE_OFF */
            (SUM(T1.NET_WRITE_OFF)) FORMAT=16.2 AS NET_WRITE_OFF, 
          /* NET_REVENUE */
            (SUM(T1.NET_REVENUE)) FORMAT=16.2 LABEL="NET_REVENUE" AS NET_REVENUE, 
          /* BEGIN_PWO_AMT */
            (SUM(T1.BEGIN_PWO_AMT)) AS BEGIN_PWO_AMT, 
          /* CURRENT_PWO_AMT */
            (SUM(T1.CURRENT_PWO_AMT)) AS CURRENT_PWO_AMT, 
          /* NEXT_MONTH_PWO_AMT */
            (SUM(T1.NEXT_MONTH_PWO_AMT)) AS NEXT_MONTH_PWO_AMT, 
          /* NEXT_2_MONTH_PWO_AMT */
            (SUM(T1.NEXT_2_MONTH_PWO_AMT)) AS NEXT_2_MONTH_PWO_AMT, 
          /* RCC_IN_PROCESS */
            (SUM(T1.RCC_IN_PROCESS)) AS RCC_IN_PROCESS, 
          /* RCC_INELIGIBLE */
            (SUM(T1.RCC_INELIGIBLE)) FORMAT=11. AS RCC_INELIGIBLE, 
          /* DEFAULT_PMT */
            (SUM(T1.DEFAULT_PMT)) FORMAT=10.2 AS DEFAULT_PMT, 
          /* DEFAULT_CNT */
            (SUM(T1.DEFAULT_CNT)) AS DEFAULT_CNT, 
          /* DEFAULT_AMT */
            (SUM(T1.DEFAULT_AMT)) FORMAT=10.2 AS DEFAULT_AMT, 
          /* NEWCUSTCNTCOMPANY */
            (SUM(T1.NEWCUSTCNTCOMPANY)) AS NEWCUSTCNTCOMPANY, 
          /* REDEEM_CUSTOMER_CNT */
            (SUM(T1.REDEEM_CUSTOMER_CNT)) AS REDEEM_CUSTOMER_CNT, 
          /* REACTIVE_CUSTOMER_CNT */
            (SUM(T1.REACTIVE_CUSTOMER_CNT)) AS REACTIVE_CUSTOMER_CNT, 
          /* ACTIVE_CUST_CNT */
            (SUM(T1.ACTIVE_CUST_CNT)) AS ACTIVE_CUST_CNT, 
          /* INACTIVE_CUST_CNT */
            (SUM(T1.INACTIVE_CUST_CNT)) AS INACTIVE_CUST_CNT, 
          /* ACTUAL_DURATION_COUNT */
            (SUM(T1.ACTUAL_DURATION_COUNT)) AS ACTUAL_DURATION_COUNT, 
          /* ACTUAL_DURATION_DAYS */
            (SUM(T1.ACTUAL_DURATION_DAYS)) AS ACTUAL_DURATION_DAYS, 
          /* ACTUAL_DURATION_ADVAMT */
            (SUM(T1.ACTUAL_DURATION_ADVAMT)) AS ACTUAL_DURATION_ADVAMT, 
          /* ACTUAL_DURATION_FEES */
            (SUM(T1.ACTUAL_DURATION_FEES)) AS ACTUAL_DURATION_FEES, 
          /* AVGDURATIONDAYS */
            (SUM(T1.AVGDURATIONDAYS)) AS AVGDURATIONDAYS, 
          /* AVGDURATIONCNT */
            (SUM(T1.AVGDURATIONCNT)) AS AVGDURATIONCNT, 
          /* BLACK_BOOK_VALUE */
            (SUM(T1.BLACK_BOOK_VALUE)) AS BLACK_BOOK_VALUE, 
          /* PASTDUECNT_1 */
            (SUM(T1.PASTDUECNT_1)) AS PASTDUECNT_1, 
          /* PASTDUEAMT_1 */
            (SUM(T1.PASTDUEAMT_1)) FORMAT=12.2 AS PASTDUEAMT_1, 
          /* PASTDUEAMT_2 */
            (SUM(T1.PASTDUEAMT_2)) FORMAT=12.2 AS PASTDUEAMT_2, 
          /* PASTDUECNT_2 */
            (SUM(T1.PASTDUECNT_2)) FORMAT=11. AS PASTDUECNT_2, 
          /* PASTDUEAMT_3 */
            (SUM(T1.PASTDUEAMT_3)) FORMAT=12.2 AS PASTDUEAMT_3, 
          /* PASTDUECNT_3 */
            (SUM(T1.PASTDUECNT_3)) FORMAT=11. AS PASTDUECNT_3, 
          /* PASTDUEAMT_4 */
            (SUM(T1.PASTDUEAMT_4)) FORMAT=12.2 AS PASTDUEAMT_4, 
          /* PASTDUECNT_4 */
            (SUM(T1.PASTDUECNT_4)) FORMAT=11. AS PASTDUECNT_4, 
          /* PASTDUEAMT_5 */
            (SUM(T1.PASTDUEAMT_5)) FORMAT=12.2 AS PASTDUEAMT_5, 
          /* PASTDUECNT_5 */
            (SUM(T1.PASTDUECNT_5)) FORMAT=11. AS PASTDUECNT_5, 
          /* PASTDUEAMT_6 */
            (SUM(T1.PASTDUEAMT_6)) FORMAT=12.2 AS PASTDUEAMT_6, 
          /* PASTDUECNT_6 */
            (SUM(T1.PASTDUECNT_6)) FORMAT=11. AS PASTDUECNT_6, 
          /* OVERSHORTAMT */
            (SUM(T1.OVERSHORTAMT)) AS OVERSHORTAMT, 
          /* HOLDOVERAMT */
            (SUM(T1.HOLDOVERAMT)) AS HOLDOVERAMT, 
          /* REFINANCE_CNT */
            (SUM(T1.REFINANCE_CNT)) AS REFINANCE_CNT, 
          /* FIRST_PRESENTMENT_CNT */
            (SUM(T1.FIRST_PRESENTMENT_CNT)) AS FIRST_PRESENTMENT_CNT, 
          /* SATISFIED_PAYMENT_CNT */
            (SUM(T1.SATISFIED_PAYMENT_CNT)) AS SATISFIED_PAYMENT_CNT, 
          /* POSSESSION_AMT */
            (SUM(T1.POSSESSION_AMT)) FORMAT=21.4 AS POSSESSION_AMT, 
          /* POSSESSION_CNT */
            (SUM(T1.POSSESSION_CNT)) AS POSSESSION_CNT, 
          /* SOLD_AMOUNT */
            (SUM(T1.SOLD_AMOUNT)) FORMAT=21.4 AS SOLD_AMOUNT, 
          /* SOLD_COUNT */
            (SUM(T1.SOLD_COUNT)) FORMAT=12.2 AS SOLD_COUNT, 
          /* ADVCNT */
            (SUM(T1.ADVCNT)) AS ADVCNT, 
          /* AVGADVAMT */
            (SUM(T1.AVGADVAMT)) FORMAT=10.2 AS AVGADVAMT, 
          /* AVGDURATION */
            (SUM(T1.AVGDURATION)) FORMAT=10.2 AS AVGDURATION, 
          /* AVGFEEAMT */
            (SUM(T1.AVGFEEAMT)) FORMAT=10.2 AS AVGFEEAMT, 
          /* ADVAMTSUM */
            (SUM(T1.ADVAMTSUM)) FORMAT=14.2 AS ADVAMTSUM, 
          /* HELDCNT */
            (SUM(T1.HELDCNT)) AS HELDCNT, 
          /* AGNCNT */
            (SUM(T1.AGNCNT)) AS AGNCNT, 
          /* REPMTPLANCNT */
            (SUM(T1.REPMTPLANCNT)) AS REPMTPLANCNT
      FROM BIOR.O_DAILY_SUMMARY_ALL T1
      GROUP BY T1.PRODUCT,
               T1.PRODUCT_DESC,
               T1.POS,
               T1.INSTANCE,
               T1.BRANDCD,
               T1.BANKMODEL,
               T1.COUNTRYCD,
               T1.STATE,
               T1.BUSINESS_UNIT,
               T1.ZONENBR,
               T1.ZONENAME,
               T1.REGIONNBR,
               T1.REGIONRDO,
               T1.DIVISIONNBR,
               T1.DIVISIONDDO,
               T1.HOLIDAYNAME,
               T1.BUSINESSDT,
               T1.LASTTHURSDAY,
               T1.THURSDAYWEEK,
               T1.LAST_REPORT_DT;
QUIT;


/* UPLOAD DIVISION LEVEL SUMMARY */
PROC SQL;
	CONNECT TO ORACLE (USER=&USER PASSWORD=&PASSWORD PATH='BIOR');
	EXEC(TRUNCATE TABLE BIOR.O_DAILY_SUMMARY_DIV) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	INSERT INTO BIOR.O_DAILY_SUMMARY_DIV (BULKLOAD=YES BL_DELETE_FILES=YES BL_DEFAULT_DIR ="E:\SHARED\CADA\SAS DATA\USER\BULKLOAD\")
	SELECT * FROM DAILY_SUMMARY_DIV
;
QUIT;


