%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SKYNET REDESIGN\DATAMART REDESIGN\DAILY\DAILY_ERROR_INPUTS.SAS";


/*UPDATE STATUS TABLE*/
PROC SQL;
CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH='BIOR');
	EXECUTE(UPDATE BIOR.DATAMART_STATUS
			SET LOC_STATUS = 'UPLOADING'
			   ,LOC_RUN_DATE = CURRENT_DATE
			WHERE SOURCE = 'BIOR.TRANSPOSE_DAILY_SUMMARY'
			)
	 BY ORACLE;
	 DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub42);

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(
		INSERT INTO SKYNET.TRANSPOSE_DAILY_SUM_LOC_STG
			SELECT
				PRODUCT ,PRODUCT_DESC ,POS ,INSTANCE ,BRANDCD ,BANKMODEL 
				,COUNTRYCD ,STATE ,CITY ,ZIP ,ZONENBR ,ZONENAME ,REGIONNBR 
				,REGIONRDO ,DIVISIONNBR ,DIVISIONDDO ,LOCNBR ,LOCATION_NAME 
				,LOC_OPEN_DT ,LOC_CLOSE_DT ,BUSINESSDT ,LAST_REPORT_DT 
				,LOC_LAST_REPORTED_DT ,LATITUDE ,LONGITUDE ,HOLIDAYNAME ,LASTTHURSDAY 
				,THURSDAYWEEK
				,CHANNELCD 
				,KPINAME
				,VALUE1
            FROM (
				SELECT * FROM (
					SELECT 
						PRODUCT ,PRODUCT_DESC ,POS ,INSTANCE ,BRANDCD ,BANKMODEL 
						,COUNTRYCD ,STATE ,CITY ,ZIP ,ZONENBR ,ZONENAME ,REGIONNBR 
						,REGIONRDO ,DIVISIONNBR ,DIVISIONDDO ,LOCNBR ,LOCATION_NAME 
						,LOC_OPEN_DT ,LOC_CLOSE_DT ,BUSINESSDT ,LAST_REPORT_DT 
						,cast(null as date) LOC_LAST_REPORTED_DT ,LATITUDE ,LONGITUDE ,HOLIDAYNAME ,LASTTHURSDAY 
						,THURSDAYWEEK
						,'ONLINE' as CHANNELCD
						,TOTALLINERECV as TOTADVRECV
						,NULL as TOTADVFEERECV
						,ACTIVE_CREDIT_LINE_CNT as COMPLIANT_LOANS_OUTSTANDING 
						,NEWCUSTCNTCOMPANY
						,NET_REVENUE
						,NEW_ORIGINATION_LINE_COUNT as NEW_ORIGINATIONS 
						,GROSS_REVENUE
						,NET_WRITE_OFF
						,WORAMTSUM
						,TOTALDEFAULTLINERECV as TOTDEFAULTRECV
						,NULL as REACTIVE_CUSTOMER_CNT
					FROM BIOR.O_DAILY_SUMMARY_LOC
					WHERE BUSINESSDT >= (TRUNC(CURRENT_DATE) - 5)
					)
            GROUP BY
				PRODUCT ,PRODUCT_DESC ,POS ,INSTANCE ,BRANDCD ,BANKMODEL 
				,COUNTRYCD ,STATE ,CITY ,ZIP ,ZONENBR ,ZONENAME ,REGIONNBR 
				,REGIONRDO ,DIVISIONNBR ,DIVISIONDDO ,LOCNBR ,LOCATION_NAME 
				,LOC_OPEN_DT ,LOC_CLOSE_DT ,BUSINESSDT ,LAST_REPORT_DT 
				,LOC_LAST_REPORTED_DT ,LATITUDE ,LONGITUDE ,HOLIDAYNAME ,LASTTHURSDAY 
				,THURSDAYWEEK
				,CHANNELCD 
					,TOTADVRECV ,TOTADVFEERECV ,COMPLIANT_LOANS_OUTSTANDING 
					,NEWCUSTCNTCOMPANY ,NET_REVENUE ,NEW_ORIGINATIONS 
					,GROSS_REVENUE ,NET_WRITE_OFF ,WORAMTSUM ,TOTDEFAULTRECV
					,REACTIVE_CUSTOMER_CNT  
                )
            UNPIVOT(
                VALUE1
                FOR KPINAME
                IN (   
                TOTADVRECV ,TOTADVFEERECV ,COMPLIANT_LOANS_OUTSTANDING 
                ,NEWCUSTCNTCOMPANY ,NET_REVENUE ,NEW_ORIGINATIONS 
                ,GROSS_REVENUE ,NET_WRITE_OFF ,WORAMTSUM ,TOTDEFAULTRECV
				,REACTIVE_CUSTOMER_CNT                       ))
		) BY ORACLE;
DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub42);

/*MERGE INTO PRODUCTION TABLE*/
PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PASSWORD=&PASSWORD. PATH="BIOR");
	EXECUTE (MERGE INTO BIOR.TRANSPOSE_LOC_DAILY_SUMMARY BIOR
    USING SKYNET.TRANSPOSE_DAILY_SUM_LOC_STG UPSERT
        ON (BIOR.INSTANCE=UPSERT.INSTANCE 
		    AND BIOR.PRODUCT_DESC=UPSERT.PRODUCT_DESC 
			AND BIOR.LOCNBR=UPSERT.LOCNBR
			AND BIOR.BUSINESSDT = UPSERT.BUSINESSDT
			AND BIOR.PRODUCT = UPSERT.PRODUCT
			AND BIOR.KPINAME = UPSERT.KPINAME)
        WHEN MATCHED THEN UPDATE
           SET 
                BIOR.POS=UPSERT.POS,
                BIOR.BRANDCD=UPSERT.BRANDCD,
                BIOR.BANKMODEL=UPSERT.BANKMODEL,
                BIOR.COUNTRYCD=UPSERT.COUNTRYCD,
                BIOR.STATE=UPSERT.STATE,
                BIOR.CITY=UPSERT.CITY,
                BIOR.ZIP=UPSERT.ZIP,
                BIOR.ZONENBR=UPSERT.ZONENBR,
                BIOR.ZONENAME=UPSERT.ZONENAME,
                BIOR.REGIONNBR=UPSERT.REGIONNBR,
                BIOR.REGIONRDO=UPSERT.REGIONRDO,
                BIOR.DIVISIONNBR=UPSERT.DIVISIONNBR,
				BIOR.DIVISIONDDO=UPSERT.DIVISIONDDO,
                BIOR.LOCATION_NAME=UPSERT.LOCATION_NAME,
                BIOR.LOC_OPEN_DT=UPSERT.LOC_OPEN_DT,
                BIOR.LOC_CLOSE_DT=UPSERT.LOC_CLOSE_DT,
                BIOR.LAST_REPORT_DT=UPSERT.LAST_REPORT_DT,
                BIOR.LOC_LAST_REPORTED_DT=UPSERT.LOC_LAST_REPORTED_DT,
                BIOR.LATITUDE=UPSERT.LATITUDE,
				BIOR.LONGITUDE=UPSERT.LONGITUDE,
                BIOR.HOLIDAYNAME=UPSERT.HOLIDAYNAME,
                BIOR.LASTTHURSDAY=UPSERT.LASTTHURSDAY,
                BIOR.THURSDAYWEEK=UPSERT.THURSDAYWEEK,
				BIOR.CHANNELCD=UPSERT.CHANNELCD,
				BIOR.VALUE1 = UPSERT.VALUE1
         WHEN NOT MATCHED
            THEN INSERT
                 (PRODUCT, 
		          PRODUCT_DESC, 
		          POS, 
		          INSTANCE, 
		          BRANDCD, 
		          BANKMODEL, 
		          COUNTRYCD, 
		          STATE, 
		          CITY, 
		          ZIP, 
		          ZONENBR, 
		          ZONENAME, 
		          REGIONNBR, 
		          REGIONRDO, 
		          DIVISIONNBR, 
		          DIVISIONDDO, 
		          LOCNBR, 
		          LOCATION_NAME, 
		          LOC_OPEN_DT, 
		          LOC_CLOSE_DT, 
		          BUSINESSDT, 
		          LAST_REPORT_DT, 
		          LOC_LAST_REPORTED_DT, 
		          LATITUDE, 
		          LONGITUDE, 
		          HOLIDAYNAME, 
		          LASTTHURSDAY, 
		          THURSDAYWEEK,
				  CHANNELCD, 
				  KPINAME,
				  VALUE1)
            VALUES 
                 (UPSERT.PRODUCT, 
		          UPSERT.PRODUCT_DESC, 
		          UPSERT.POS, 
		          UPSERT.INSTANCE, 
		          UPSERT.BRANDCD, 
		          UPSERT.BANKMODEL, 
		          UPSERT.COUNTRYCD, 
		          UPSERT.STATE, 
		          UPSERT.CITY, 
		          UPSERT.ZIP, 
		          UPSERT.ZONENBR, 
		          UPSERT.ZONENAME, 
		          UPSERT.REGIONNBR, 
		          UPSERT.REGIONRDO, 
		          UPSERT.DIVISIONNBR, 
		          UPSERT.DIVISIONDDO, 
		          UPSERT.LOCNBR, 
		          UPSERT.LOCATION_NAME, 
		          UPSERT.LOC_OPEN_DT, 
		          UPSERT.LOC_CLOSE_DT, 
		          UPSERT.BUSINESSDT, 
		          UPSERT.LAST_REPORT_DT, 
		          UPSERT.LOC_LAST_REPORTED_DT, 
		          UPSERT.LATITUDE, 
		          UPSERT.LONGITUDE, 
		          UPSERT.HOLIDAYNAME, 
		          UPSERT.LASTTHURSDAY, 
		          UPSERT.THURSDAYWEEK,
				  UPSERT.CHANNELCD, 
		          UPSERT.KPINAME,
				  UPSERT.VALUE1)
	) BY ORACLE;
	DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub42);

/*UPDATE STATUS TABLE*/
PROC SQL;
CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH='BIOR');
	EXECUTE(UPDATE BIOR.DATAMART_STATUS
			SET LOC_STATUS = 'FINISHED'
			   ,LOC_COMPLETION_DATE = CURRENT_DATE
			WHERE SOURCE = 'BIOR.TRANSPOSE_DAILY_SUMMARY'
			)
	 BY ORACLE;
	 DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub42);

