%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\STDM\STDM_LIBRARY_SCRIPT.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_EADV) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF1) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF2) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF1T) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF3) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_TETL) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_TTOC) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_FAI) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF4) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF5I) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF5T) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_QF5P) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_NG) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
		EXEC(TRUNCATE TABLE SKYNET.TRANSPOSE_DAILY_SUMMARY_OL) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;