%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";

LIBNAME BIOR ORACLE
	USER=&USER.
	PASSWORD=&PASSWORD.
	PATH=BIOR
	SCHEMA=BIOR;

%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\STDM\STDM_LIBRARY_SCRIPT.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SKYNET REDESIGN\DATAMART REDESIGN\DAILY\DAILY_ERROR_INPUTS.SAS";
LIBNAME SKYNET "E:\SHARED\CADA\SAS DATA\DATAMART\STDM";

/*THIS SHOULD RUN EVERY NIGHT TO UPDATE THE TRANSPOSE TABLE DATES TO TODAY*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(DROP INDEX IDX_O_TRANSPOSE_MERGEZ) BY ORACLE;
	EXECUTE(UPDATE BIOR.TRANSPOSE_DAILY_SUMMARY
		    SET LAST_REPORT_DT = TO_DATE(TO_CHAR(CURRENT_DATE-1, 'MM/DD/YYYY'), 'MM/DD/YYYY')
			)	BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TRANSPOSE_MERGEZ ON BIOR.TRANSPOSE_DAILY_SUMMARY(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(DROP INDEX IDX_O_TRANSPOSE_MERGEFUSE) BY ORACLE;
	EXECUTE(UPDATE BIOR.TRANSPOSE_DAILY_SUMMARY_FUSE
		    SET LAST_REPORT_DT = TO_DATE(TO_CHAR(CURRENT_DATE-1, 'MM/DD/YYYY'), 'MM/DD/YYYY')
			)	BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TRANSPOSE_MERGEFUSE ON BIOR.TRANSPOSE_DAILY_SUMMARY_FUSE(INSTANCE,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(DROP INDEX IDX_O_TRANSPOSE_MERGELOC) BY ORACLE;
	EXECUTE(UPDATE BIOR.TRANSPOSE_LOC_DAILY_SUMMARY
		    SET LAST_REPORT_DT = TO_DATE(TO_CHAR(CURRENT_DATE-1, 'MM/DD/YYYY'), 'MM/DD/YYYY')
			)	BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_TRANSPOSE_MERGELOC ON BIOR.TRANSPOSE_LOC_DAILY_SUMMARY(INSTANCE,PRODUCT_DESC,LOCNBR,BUSINESSDT,PRODUCT,KPINAME)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;