%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\SKYNET REDESIGN\DATAMART REDESIGN\CUSTOMER\CUSTDM_ERROR_INPUTS.SAS";

/*UPDATE STATUS TABLE*/
PROC SQL;
CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(UPDATE BIOR.DATAMART_STATUS
			  SET 
			   QFUND3_TXTITLE_STATUS = 'UPLOADING'
			   ,QFUND3_TXTITLE_RUN_DATE = CURRENT_DATE
			   ,QFUND3_TETL_STATUS = 'UPLOADING'
			   ,QFUND3_TETL_RUN_DATE = CURRENT_DATE
			   ,QFUND3_TTOC_STATUS = 'UPLOADING'
			   ,QFUND3_TTOC_RUN_DATE = CURRENT_DATE
			   ,QFUND3_FAI_STATUS = 'UPLOADING'
			   ,QFUND3_FAI_RUN_DATE = CURRENT_DATE
			WHERE SOURCE = 'BIOR.O_CUSTOMER_ALL'
			)
	 BY ORACLE;
	 DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub10);

/*  UPDATE BIOR PRODUCTION TABLE WITH NEW DATA  */
%INCLUDE "&CUST_FILE_PATH.\CUSTDM_UPLOAD_MASTER.SAS";
%CUSTMERGEINTO(QF3)


/*UPDATE STATUS TABLE*/
PROC SQL;
CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(UPDATE BIOR.DATAMART_STATUS
			  SET 
			   QFUND3_TXTITLE_STATUS = 'FINISHED'
			   ,QFUND3_TXTITLE_COMPLETION_DATE = CURRENT_DATE
			   ,QFUND3_TETL_STATUS = 'FINISHED'
			   ,QFUND3_TETL_COMPLETION_DATE = CURRENT_DATE
			   ,QFUND3_TTOC_STATUS = 'FINISHED'
			   ,QFUND3_TTOC_COMPLETION_DATE = CURRENT_DATE
			   ,QFUND3_FAI_STATUS = 'FINISHED'
			   ,QFUND3_FAI_COMPLETION_DATE = CURRENT_DATE
			WHERE SOURCE = 'BIOR.O_CUSTOMER_ALL'
			)
	 BY ORACLE;
	 DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub10);
