
OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT NOQUOTELENMAX LRECL=32767;
/*	INCLUDE LIBNAMES SCRIPT */
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\TOP SECRET PROGRAM.SAS";


%LET DAYS_BACK = 5;


/*CREATE BACKUPS FOR CUSTOMER LIFECYCLE*/

	/*	MAKE BACKUP OF UPDATED/CURRENT */
	DATA CLA.CUST_STATUS_BY_DEAL_CURRENT (ALTER=justdont WRITE=justdont);
		SET BIOR.CUST_STATUS_BY_DEAL;
	RUN;

	/*	MAKE BACKUP OF UPDATED/CURRENT */
	DATA CLA.TRANSITIONS_DETAIL_CURRENT (ALTER=justdont WRITE=justdont);
		SET BIOR.CUST_CATEGORY_DETAIL;
	RUN;

	/*DAILY COUNT*/
	DATA CLA.TRANSITIONS_DAILY_CURRENT (ALTER=justdont WRITE=justdont);
		SET BIOR.CUST_CATEGORY_DAILY_COUNT;
	RUN;