
OPTIONS SYMBOLGEN MPRINT MLOGIC NOXWAIT NOQUOTELENMAX LRECL=32767;
/*	INCLUDE LIBNAMES SCRIPT */
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\TOP SECRET PROGRAM.SAS";


%LET DAYS_BACK = 5;


/*CREATE BACKUPS FOR CUSTOMER LIFECYCLE*/

/*BACKUP CUST STATUS BY DEAL*/
DATA CLA.CUST_STATUS_BY_DEAL_1_DAY_OLD (ALTER=justdont WRITE=justdont);
	SET BIOR.CUST_STATUS_BY_DEAL;
RUN;

/*BACKUP DETAILS*/
DATA CLA.TRANSITIONS_DETAIL_1_DAY_OLD (ALTER=justdont WRITE=justdont);
	SET BIOR.CUST_CATEGORY_DETAIL;
RUN;

/*DAILY COUNT*/
DATA CLA.TRANSITIONS_DAILY_1_DAY_OLD (ALTER=justdont WRITE=justdont);
	SET BIOR.CUST_CATEGORY_DAILY_COUNT;
RUN;


/*ABORT PROGRAM*/
%MACRO STOPPROGRAM();

	%IF %EVAL(1=1) %THEN %DO;
		%abort cancel;
	%END;

%MEND;

%STOPPROGRAM