/*CUST LIFE AUDIT NUMBERS*/

/*MAKE SURE DATA EXISTS*/

%GLOBAL WEEKDAY;
%LET WEEKDAY=%SYSFUNC(WEEKDAY(%SYSFUNC(TODAY())));
%PUT &WEEKDAY;

OPTIONS MPRINT MLOGIC SYMBOLGEN;

%MACRO CUSTLIFE_AUDIT();

	PROC SQL;
		CREATE TABLE DAILY_COUNT_CHECKER_YEAR AS
		SELECT YEAR(DATEPART(BUSINESS_DATE))					AS YEAR
			  ,SUM(NEW_CUST_CNT)			AS NEW_CUST_CNT
			  ,SUM(NEW_REPEAT_CUST_CNT)		AS NEW_REPEAT_CUST_CNT
			  ,SUM(REDEEM_CUST_CNT)			AS REDEEM_CUST_CNT
			  ,SUM(REACTIVE_CUST_CNT)		AS REACTIVE_CUST_CNT
		FROM BIOR.CUST_CATEGORY_DAILY_COUNT
		GROUP BY CALCULATED YEAR
	;
	QUIT;

	PROC SQL;
		SELECT COUNT(*)
			  ,ABS(INTCK('YEAR',TODAY(),'01JAN2013'D)) INTO:COUNT_YEARS, : DIFF
		FROM DAILY_COUNT_CHECKER_YEAR
	;
	QUIT;

	%PUT &COUNT_YEARS;
	%PUT &DIFF;

	%IF %EVAL(&COUNT_YEARS. <=&DIFF.) %THEN 
		%DO;
			OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;
			FILENAME MYMAIL EMAIL; 
			DATA _NULL_;
			   FILE MYMAIL
/*					TO=('BI_DATA@ADVANCEAMERICA.NET')*/
			   		TO=('BI_DATA@ADVANCEAMERICA.NET')
					CC=('SHOPKINS@ADVANCEAMERICA.NET')
			     SUBJECT='ALERT! SOMETHING IS WRONG WITH CUST LIFE - CSSSASMETA';
				 PUT "CUST LIFE IS MISSING DATA (YEAR)";
			RUN;
		%END;

	PROC SQL;
		CREATE TABLE DAILY_COUNT_CHECKER_INSTANCE AS
		SELECT INSTANCE
			  ,SUM(NEW_CUST_CNT)			AS NEW_CUST_CNT
			  ,SUM(NEW_REPEAT_CUST_CNT)		AS NEW_REPEAT_CUST_CNT
			  ,SUM(REDEEM_CUST_CNT)			AS REDEEM_CUST_CNT
			  ,SUM(REACTIVE_CUST_CNT)		AS REACTIVE_CUST_CNT
		FROM BIOR.CUST_CATEGORY_DAILY_COUNT
		WHERE BUSINESS_DATE >= DHMS(TODAY()-1,00,00,00)
		GROUP BY INSTANCE
	;
	QUIT;

	DATA TOTAL_INSTANCE_CHECK;
		SET DAILY_COUNT_CHECKER_INSTANCE;
		IF NEW_CUST_CNT = 0 AND WEEKDAY(TODAY()) ^= 1 THEN 
			DO;
				NEW_CUST_CNT_BAD = 1;
			END;	
		IF NEW_REPEAT_CUST_CNT = 0 AND WEEKDAY(TODAY()) ^= 1 THEN 
			DO;
				NEW_REPEAT_CUST_CNT_BAD = 1;
			END;	
		IF REDEEM_CUST_CNT = 0 AND WEEKDAY(TODAY()) ^= 1 THEN 
			DO;
				REDEEM_CUST_CNT_BAD = 1;
			END;
		IF REACTIVE_CUST_CNT = 0 AND WEEKDAY(TODAY()) ^= 1 THEN 
			DO;
				REACTIVE_CUST_CNT_BAD = 1;
			END;
	RUN;

	PROC SQL;
		CREATE TABLE POSSIBLE_BAD_ONES AS
		SELECT INSTANCE
			  ,NEW_CUST_CNT
			  ,NEW_REPEAT_CUST_CNT
			  ,REDEEM_CUST_CNT
			  ,REACTIVE_CUST_CNT
		FROM TOTAL_INSTANCE_CHECK
		WHERE (NEW_CUST_CNT_BAD = 1 
			OR NEW_REPEAT_CUST_CNT_BAD = 1
			OR REDEEM_CUST_CNT_BAD = 1
			OR REACTIVE_CUST_CNT_BAD = 1)
		HAVING NEW_CUST_CNT = 0 OR REACTIVE_CUST_CNT = 0
	;
	QUIT; 

	PROC SQL;
		SELECT COUNT(*) INTO: BAD_COUNT
		FROM POSSIBLE_BAD_ONES
	;
	QUIT;

	%PUT &BAD_COUNT;

	%IF %EVAL(&BAD_COUNT. >= 1) AND %EVAL(&WEEKDAY. ^= 2) %THEN 
		%DO;

			FILENAME EML EMAIL TO=(
					'BI_DATA@ADVANCEAMERICA.NET','SHOPKINS@ADVANCEAMERICA.NET') 
			SUBJECT="CUSTOMER LIFECYCLE POTENTIAL DATA ISSUES IN THESE INSTANCES:" CT='TEXT/HTML';
			ODS LISTING CLOSE;
			ODS HTML BODY=EML;
			ODS SELECT SQL_RESULTS;
			ODS NOPROCTITLE;

			PROC SQL;
			TITLE "CUSTOMER LIFECYCLE POTENTIAL DATA ISSUES IN THESE INSTANCES:";
				SELECT *
					FROM POSSIBLE_BAD_ONES
					;
			QUIT;

		%END;

%MEND;