/*	INCLUDE LIBNAMES SCRIPT */
/*	INCLUDE LIBNAMES SCRIPT */
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\PRODUCTION\SKYNET V3\SKYNET REDESIGN\TOP SECRET PROGRAM.SAS";


%LET DAYS_BACK = 5;

%MACRO CHECK_DATE;

	/*	INSERT MOST RECENT TRANSACTION DATE INTO MACRO VARIABLE (&DT_CHECK) */
	PROC SQL;
		SELECT MAX(DATEPART(NEW_TRANSACTION_DT)) FORMAT DATE9.
		INTO :DT_CHECK
		FROM BIOR.WT_CUST_LAST_TRAN_ACTV_COMPR
		;
	QUIT;
	
	/*	SET MACRO VARIABLE (&DT_COMPR) TO TODAY()-2 */
	%LET DT_COMPR = %SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),-2),DATE9.);

	/*	IF MOST RECENT TRAN DATE NOT NE TO TODAY()-2, THEN DO NOT RUN AND SEND SHOPKINS EMAIL */
	%IF &DT_CHECK NE &DT_COMPR %THEN %DO;
		
		OPTIONS EMAILSYS=SMTP EMAILHOST=MAIL.ADVANCEAMERICA.NET EMAILPORT=25;
		FILENAME MYMAIL EMAIL; 
		DATA _NULL_;
		   FILE MYMAIL
		   		TO=('SHOPKINS@ADVANCEAMERICA.NET','JHUBBARD@ADVANCEAMERICA.NET','JROSE@ADVANCEAMERICA.NET','BI_DATA@ADVANCEAMERICA.NET')
		        SUBJECT="IMPORTANT: NOT ABLE TO RUN CUSTOMER LIFECYCLE PROGRAM";
				IMPORTANCE="HIGH";
				PUT "NOT ABLE TO RUN CUSTOMER LIFECYCLE PROGRAM";
				PUT "&DT_CHECK IS NOT 2 DAYS PRIOR TO TODAY";
		RUN;
	%END;

	/*	ELSE, IF MOST RECENT TRAN DATE IS EQUAL TO TODAY()-2, THEN RUN PRODUCTION CODE */
	%ELSE %DO;
		%INCLUDE "&CUST_FILE_PATH.\CUST_LIFECYCLE_DAILY.SAS";
	%END;

%MEND;

%CHECK_DATE