/*	INCLUDE LIBNAMES SCRIPT */
%include "E:\Shared\CADA\SAS Source Code\Development\shopkins\LIBNAMES.sas";

PROC SQL;
CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
EXECUTE(
	MERGE INTO BIOR.O_DEAL_SUMMARY_ALL BIOR
		USING (SELECT * FROM BIOR.CUST_STATUS_BY_DEAL WHERE DEAL_DT >=TRUNC(SYSDATE)-2) UPSERT
			ON(BIOR.INSTANCE = UPSERT.INSTANCE AND
			   BIOR.DEALNBR = UPSERT.DEALNBR AND
		       BIOR.TITLE_DEALNBR = UPSERT.TITLE_DEALNBR)
		 WHEN MATCHED THEN UPDATE
			SET BIOR.CUST_STATUS=UPSERT.CUST_STATUS)
	BY ORACLE;
DISCONNECT FROM ORACLE;
QUIT;