
/*	
===================================================
	CREATED TO HAVE TABLE WITH LAST CUSTOMER
	INITIATED TRANSACTION BY
	SSN/INSTANCE/CUSTNBR/PRODUCT
==================================================
*/


/* 	GET THE MOST RECENT CI TRANSACTION GROUPED BY SSN/CUSTNBR/INSTANCE/PRODUCT */

PROC SQL;
	CREATE TABLE WORK.LCITD_PRODUCT AS
	SELECT
		SSN
		,INSTANCE
		,CUSTNBR
		,PRODUCT
		,MAX(TRANDT) AS TRANDT
	FROM BIOR.O_DEALTRANSACTION_ALL
	WHERE CI_FLG = 'Y' 
		AND SSN IS NOT NULL
	GROUP BY 
		SSN
		,INSTANCE
		,CUSTNBR
		,PRODUCT
	;
QUIT;

/*	SORT TABLE  */

/*	TRUNCATE BIOR TABLE */
PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
		EXEC(TRUNCATE TABLE BIOR.LCITD_PRODUCT) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;


/*	APPEND REFRESHED TABLE TO BIOR */
PROC APPEND BASE=BIOR.LCITD_PRODUCT 
			DATA=WORK.LCITD_PRODUCT;
RUN;