/*CREATE STAGING TABLES */

/*EADV*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_EADV
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_EADV
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_EADV ON SKYNET.CUSTOMER_DATAMART_EADV(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_EADV ON SKYNET.CUSTOMER_DATAMART_EADV(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_SSN_EADV ON SKYNET.CUSTOMER_DATAMART_EADV(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF1_QF2*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_QF1QF2
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_QF1QF2
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_QF1QF2 ON SKYNET.CUSTOMER_DATAMART_QF1QF2(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_QF1QF2 ON SKYNET.CUSTOMER_DATAMART_QF1QF2(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_TWO_CUST_ALL_QF1QF2 ON SKYNET.CUSTOMER_DATAMART_QF1QF2(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND3*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_QF3
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_QF3
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_QF3 ON SKYNET.CUSTOMER_DATAMART_QF3(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_QF3 ON SKYNET.CUSTOMER_DATAMART_QF3(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_TWO_CUST_ALL_QF3 ON SKYNET.CUSTOMER_DATAMART_QF3(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND4*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_QF4
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_QF4
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_QF4 ON SKYNET.CUSTOMER_DATAMART_QF4(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_QF4 ON SKYNET.CUSTOMER_DATAMART_QF4(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_TWO_CUST_ALL_QF4 ON SKYNET.CUSTOMER_DATAMART_QF4(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QFUND5*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_QF5
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_QF5
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_QF5 ON SKYNET.CUSTOMER_DATAMART_QF5(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_QF5 ON SKYNET.CUSTOMER_DATAMART_QF5(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_TWO_CUST_ALL_QF5 ON SKYNET.CUSTOMER_DATAMART_QF5(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*NG*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_NG
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_NG
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_NG ON SKYNET.CUSTOMER_DATAMART_NG(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_NG ON SKYNET.CUSTOMER_DATAMART_NG(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_TWO_CUST_ALL_NG ON SKYNET.CUSTOMER_DATAMART_NG(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*ONLINE*/

PROC SQL;
	DROP TABLE SKY.CUSTOMER_DATAMART_OL
;
QUIT;

PROC SQL;
	CREATE TABLE SKY.CUSTOMER_DATAMART_OL
	LIKE BIOR.O_CUSTOMER_ALL
;
QUIT;

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_CN_OL ON SKYNET.CUSTOMER_DATAMART_OL(CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_CUST_ALL_OL ON SKYNET.CUSTOMER_DATAMART_OL(INSTANCE,CUSTNBR)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_TWO_CUST_ALL_OL ON SKYNET.CUSTOMER_DATAMART_OL(SSN)) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*JOINT INDEXES*/

PROC SQL;
	CONNECT TO ORACLE (USER=&USER. PW=&PASSWORD. PATH="&PATH.");
	EXECUTE(CREATE INDEX IDX_O_JT_OL ON SKYNET.CUSTOMER_DATAMART_OL(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_JT_NG ON SKYNET.CUSTOMER_DATAMART_NG(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_JT_QF5 ON SKYNET.CUSTOMER_DATAMART_QF5(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_JT_QF4 ON SKYNET.CUSTOMER_DATAMART_QF4(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_JT_QF3 ON SKYNET.CUSTOMER_DATAMART_QF3(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_JT_QF1QF2 ON SKYNET.CUSTOMER_DATAMART_QF1QF2(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
	EXECUTE(CREATE INDEX IDX_O_JT_EADV ON SKYNET.CUSTOMER_DATAMART_EADV(INSTANCE,CUSTNBR,SSN)) BY ORACLE;
/*	EXECUTE(CREATE INDEX IDX_O_JT_CUST ON BIOR.O_CUSTOMER_ALL(INSTANCE,CUSTNBR,SSN)) BY ORACLE;*/
	DISCONNECT FROM ORACLE;
QUIT;