/****************************************************************************
* Program		: Customer SSN Macro From Source						  	*
* Description	: Pulls Source SSN and CUSTNBR from all POS's              	*
* Programmer	: Nathan Rochester										  	*
* Date			: 07/05/2016											  	*	
****************************************************************************/

%GLOBAL SQL_TEXT;

%MACRO SSN(INSTANCE);

%IF &INSTANCE=EAPROD1 %THEN %DO;
    %LET SQL_TEXT = SELECT 'EAPROD1' AS INSTANCE ,CUSTNBR AS CUSTNBR ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM EADV.CUSTOMER;
%END;

%ELSE %IF &INSTANCE=QFUND1I %THEN %DO;

PROC SORT DATA=EDW_STAR.CUSTOMER_DIM(KEEP=CUSTOMER_NBR CUSTOMER_ID SSN SOURCE_SYSTEM where=(SOURCE_SYSTEM IN ('QF1'))) OUT=WORK.QFUND1CUSTI;
	BY CUSTOMER_NBR CUSTOMER_ID;
RUN;

DATA TRANDM.QFUND1CUSTI;
	SET WORK.QFUND1CUSTI;
		BY CUSTOMER_NBR;
		IF LAST.CUSTOMER_NBR;
RUN;

    %LET SQL_TEXT = SELECT DISTINCT 'QFUND1' AS INSTANCE ,CUSTOMER_NBR AS CUSTNBR LABEL="CUSTNBR"  ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM TRANDM.QFUND1CUSTI;
%END;

%ELSE %IF &INSTANCE=QFUND1T %THEN %DO;

PROC SORT DATA=EDW_STAR.CUSTOMER_DIM(KEEP=CUSTOMER_NBR CUSTOMER_ID SSN SOURCE_SYSTEM where=(SOURCE_SYSTEM IN ('QF1'))) OUT=WORK.QFUND1CUSTT;
	BY CUSTOMER_NBR CUSTOMER_ID;
RUN;

DATA TRANDM.QFUND1CUSTT;
	SET WORK.QFUND1CUSTT;
		BY CUSTOMER_NBR;
		IF LAST.CUSTOMER_NBR;
RUN;

    %LET SQL_TEXT = SELECT DISTINCT 'QFUND1' AS INSTANCE ,CUSTOMER_NBR AS CUSTNBR LABEL="CUSTNBR"  ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM TRANDM.QFUND1CUSTT;
%END;

%ELSE %IF &INSTANCE=QFUND2 %THEN %DO;

PROC SORT DATA=EDW_STAR.CUSTOMER_DIM(KEEP=CUSTOMER_NBR CUSTOMER_ID SSN SOURCE_SYSTEM where=(SOURCE_SYSTEM IN ('QF2'))) OUT=WORK.QFUND2CUST;
	BY CUSTOMER_NBR CUSTOMER_ID;
RUN;

DATA TRANDM.QFUND2CUST;
	SET WORK.QFUND2CUST;
		BY CUSTOMER_NBR;
		IF LAST.CUSTOMER_NBR;
RUN;

    %LET SQL_TEXT = SELECT 'QFUND2' AS INSTANCE ,CUSTOMER_NBR AS CUSTNBR LABEL="CUSTNBR" ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM TRANDM.QFUND2CUST;
%END;

%ELSE %IF &INSTANCE=QFUND3 %THEN %DO;

PROC SORT DATA=QFUND3.CUSTOMER (KEEP=BO_CODE BO_ID SSN) OUT=WORK.QFUND3CUST2;
	BY BO_CODE BO_ID;
RUN;

DATA WORK.QFUND3CUST1 (RENAME=(BO_CODE=CUSTNBR) DROP=BO_ID);
	SET WORK.QFUND3CUST2;
		BY BO_CODE;
		IF LAST.BO_CODE;
RUN;

PROC SQL NOPRINT;
CREATE TABLE WORK.QFUND3CUST AS 
SELECT CUSTNBR,
	   SSN LENGTH=9 FORMAT=$9.
FROM WORK.QFUND3CUST1;
QUIT;

PROC SORT DATA=EDW.TITLE_CUSTOMER_DETAIL (KEEP=CUSTNBR UPDATEDT SSN) OUT=WORK.QFUND3CUSTTX2;
	BY CUSTNBR UPDATEDT;
RUN;

DATA WORK.QFUND3CUSTTX1 (RENAME=(SSN1=SSN) DROP=UPDATEDT);
	SET WORK.QFUND3CUSTTX2 (RENAME=(SSN=SSN1));
	    BY CUSTNBR UPDATEDT;
	    IF LAST.CUSTNBR;
RUN;

PROC SQL NOPRINT;
CREATE TABLE WORK.QFUND3CUSTTX AS 
SELECT CUSTNBR,
	   SSN LENGTH=9 FORMAT=$9.
FROM WORK.QFUND3CUSTTX1;
QUIT;

DATA TRANDM.QFUND3CUST;
SET WORK.QFUND3CUST
	WORK.QFUND3CUSTTX;
RUN;


    %LET SQL_TEXT = SELECT 'QFUND3' AS INSTANCE ,CUSTNBR AS CUSTNBR ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM TRANDM.QFUND3CUST;
%END;

%ELSE %IF &INSTANCE=QFUND3TT %THEN %DO;

PROC SORT DATA=QFUND3.CUSTOMER (KEEP=BO_CODE BO_ID SSN) OUT=WORK.QFUND3CUST2;
	BY BO_CODE BO_ID;
RUN;

DATA WORK.QFUND3CUST1 (RENAME=(BO_CODE=CUSTNBR) DROP=BO_ID);
	SET WORK.QFUND3CUST2;
		BY BO_CODE;
		IF LAST.BO_CODE;
RUN;

PROC SQL NOPRINT;
CREATE TABLE WORK.QFUND3CUST AS 
SELECT CUSTNBR,
	   SSN LENGTH=9 FORMAT=$9.
FROM WORK.QFUND3CUST1;
QUIT;

PROC SORT DATA=EDW.TITLE_CUSTOMER_DETAIL (KEEP=CUSTNBR UPDATEDT SSN) OUT=WORK.QFUND3CUSTTX2;
	BY CUSTNBR UPDATEDT;
RUN;

DATA WORK.QFUND3CUSTTX1 (RENAME=(SSN1=SSN) DROP=UPDATEDT);
	SET WORK.QFUND3CUSTTX2 (RENAME=(SSN=SSN1));
	    BY CUSTNBR UPDATEDT;
	    IF LAST.CUSTNBR;
RUN;

PROC SQL NOPRINT;
CREATE TABLE WORK.QFUND3CUSTTX AS 
SELECT CUSTNBR,
	   SSN LENGTH=9 FORMAT=$9.
FROM WORK.QFUND3CUSTTX1;
QUIT;

DATA TRANDM.QFUND3CUSTTX;
SET WORK.QFUND3CUST
	WORK.QFUND3CUSTTX;
RUN;


    %LET SQL_TEXT = SELECT 'QFUND3TT' AS INSTANCE ,CUSTNBR AS CUSTNBR ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM TRANDM.QFUND3CUSTTX;
%END;

%ELSE %IF &INSTANCE=QFUND4 %THEN %DO;
    %LET SQL_TEXT = SELECT 'QFUND4' AS INSTANCE ,CUSTOMER_NBR AS CUSTNBR ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM ECA.QF_CUSTOMER_DETAILS;
%END;

%ELSE %IF &INSTANCE=QFUND5 %THEN %DO;

PROC SORT DATA=EDW.CSO_CUSTOMER (KEEP=BO_CODE BO_ID SSN) OUT=WORK.QFUND5CUST;
	BY BO_CODE BO_ID;
RUN;

DATA TRANDM.QFUND5CUST;
	SET WORK.QFUND5CUST;
		BY BO_CODE;
		IF LAST.BO_CODE;
RUN;

   %LET SQL_TEXT = SELECT 'QFUND5' AS INSTANCE ,BO_CODE AS CUSTNBR ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM TRANDM.QFUND5CUST;
%END;

%ELSE %IF &INSTANCE=NG %THEN %DO;

PROC SORT DATA=NG_IDS.TA_CUSTOMER_MASTER (KEEP=FC_SOURCE_CUST_IDENTIFIER FI_SCD_KEY_ID_CUST_MASTER) OUT=WORK.NGCUST1;
	BY FC_SOURCE_CUST_IDENTIFIER FI_SCD_KEY_ID_CUST_MASTER;
RUN;

DATA WORK.NGCUST;
	SET WORK.NGCUST1;
	BY FC_SOURCE_CUST_IDENTIFIER FI_SCD_KEY_ID_CUST_MASTER;
	IF LAST.FC_SOURCE_CUST_IDENTIFIER;
RUN;

PROC SORT DATA=NG_IDS.TA_CUSTOMER_SSN (KEEP=FC_SOURCE_CUST_IDENTIFIER FI_SCD_KEY_ID_CUST_SSN FE_CUST_SSN) OUT=WORK.NGSSN1;
	BY FC_SOURCE_CUST_IDENTIFIER FI_SCD_KEY_ID_CUST_SSN;
RUN;

DATA WORK.NGSSN;
	SET WORK.NGSSN1;
	BY FC_SOURCE_CUST_IDENTIFIER FI_SCD_KEY_ID_CUST_SSN;
	IF LAST.FC_SOURCE_CUST_IDENTIFIER;
RUN;

   %LET SQL_TEXT = SELECT 'NG' AS INSTANCE ,A.FC_SOURCE_CUST_IDENTIFIER AS CUSTNBR ,B.FE_CUST_SSN AS SSN LENGTH=9 FORMAT=$9. FROM WORK.NGCUST A LEFT JOIN WORK.NGSSN B ON (A.FC_SOURCE_CUST_IDENTIFIER = B.FC_SOURCE_CUST_IDENTIFIER);
%END;

%ELSE %IF &INSTANCE=AANET %THEN %DO;
   %LET SQL_TEXT = SELECT 'AANET' AS INSTANCE ,CUSTIDENTITYID AS CUSTNBR ,SSN AS SSN LENGTH=9 FORMAT=$9. FROM SC_AA_LG.CUSTIDENTITY;
%END;

%PUT SQL TEXT: &SQL_TEXT.;

%MEND;

/*%SSN(NG);*/