*Error Checking;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\TRANSACTION_DATAMART_DAILY\Transaction_Table_Error_Check.sas";

*Libname Statements;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\Libname_Statements.sas";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";

PROC SQL;    
CONNECT TO ORACLE (USER=SVC_SASUSER PASSWORD="{SAS002}8E8C78044906924E47EBAD620CFCE3294AE9C1533DF26A16" PATH="BIOR") ;
EXECUTE (DELETE FROM TEMPTABLES.O_CSO_5_YEAR WHERE BUSINESSDT >= TRUNC(SYSDATE)-5) BY ORACLE;
QUIT;


/*DATA O_CSO_5_YEAR (DROP=DEALNBR1);*/
/*	SET TEMPTABL.O_CSO_5_YEAR;*/
/*	CHANNELCD = 'STOREFRONT';*/
/*RUN;*/
/**/
/*PROC SQL;*/
/*	DROP TABLE TEMPTABL.O_CSO_5_YEAR;*/
/*QUIT;*/
/**/
/*DATA TEMPTABL.O_CSO_5_YEAR;*/
/*	SET O_CSO_5_YEAR;*/
/*	DEALNBR1 = INPUT(DEALNBR,15.);*/
/*RUN;*/
