*Error Checking;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\TRANSACTION_DATAMART_DAILY\Transaction_Table_Error_Check.sas";

*Libname Statements;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\Libname_Statements.sas";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";

PROC SQL;    
CONNECT TO ORACLE (USER=SVC_SASUSER PASSWORD="{SAS002}8E8C78044906924E47EBAD620CFCE3294AE9C1533DF26A16" PATH="BIOR") ;
EXECUTE (DELETE FROM BIOR.O_DEALTRANSACTION_90 WHERE NCP_IND='N' AND DEALNBR IN (SELECT DEALNBR FROM TEMPTABLES.O_DT_CSO_5_YEAR_2)) BY ORACLE;
QUIT;

/*PROC SQL;    */
/*CONNECT TO ORACLE (USER=SVC_SASUSER PASSWORD="{SAS002}8E8C78044906924E47EBAD620CFCE3294AE9C1533DF26A16" PATH="BIOR") ;*/
/*EXECUTE (DELETE FROM TEMPTABLES.O_CSO_5_YEAR WHERE NCP_IND='N' AND DEALNBR IN (SELECT DEALNBR FROM TEMPTABLES.O_DT_CSO_5_YEAR)) BY ORACLE;*/
/*QUIT;*/


