*Libname Statements;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\Libname_Statements.sas";

*Error Checking;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\TRANSACTION_DATAMART_DAILY\Transaction_Table_Error_Check.sas";

/* DROP INDEXES */
PROC SQL;    
CONNECT TO ORACLE (USER=SVC_SASUSER PASSWORD="{SAS002}8E8C78044906924E47EBAD620CFCE3294AE9C1533DF26A16" PATH="BIOR") ;
EXECUTE (DROP INDEX IDX_TRANSACTION_DN)      BY ORACLE;
EXECUTE (DROP INDEX IDX_TRANSACTION_BD)      BY ORACLE;
EXECUTE (DROP INDEX IDX_TRANSACTION_CN)      BY ORACLE;
EXECUTE (DROP INDEX IDX_TRANSACTION_SSN)     BY ORACLE;
/*EXECUTE (DROP INDEX IDX_TRANSACTION_CN)    BY ORACLE;*/
/*EXECUTE (DROP INDEX IDX_TRANSACTION_SSN)   BY ORACLE;*/
DISCONNECT FROM ORACLE;
%RUNQUIT(&job,&sub17);


