/*KEEP TRACK OF PARTITIONS*/

/*THIS PROGRAM SHOULD RUN ONCE MONTH AND CHECK TO SEE IF ITS BEEN ONE MONTH SINCE CREATING A PARTITION*/

%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\NROCHESTER\LIBNAME_STATEMENTS.SAS";
%INCLUDE "E:\SHARED\CADA\SAS SOURCE CODE\DEVELOPMENT\JHUBBARD\TOP SECRET PROGRAM.SAS";

%LET RUN=1;

OPTIONS SYMBOLGEN MPRINT MLOGIC;

%GLOBAL DATE;
%LET DATE=%SYSFUNC(INTNX(DAY,%SYSFUNC(TODAY()),0,END),DATE7.);
%PUT &DATE;

%LET DAY = %SYSFUNC(WEEKDAY("&DATE"D));
%PUT &DAY;

/*PROC SQL;*/
/*	DROP TABLE SKY.TRANSACTION_PARTITION_MASTER */
/*;*/
/*QUIT;*/

PROC SORT DATA=SKY.TRANSACTION_PARTITION_MASTER OUT=TRANSACTION_PARTITION_MASTER;
BY PARTITION_DATE;
RUN;

DATA LAST_PARTITION_CHECK;
	SET TRANSACTION_PARTITION_MASTER END=LAST;
	IF LAST THEN OUTPUT;
RUN;

/*GET YES/NO CHECKER FOR PARTITION_DECISION*/

DATA YES_NO;
	SET LAST_PARTITION_CHECK;
	DATE_DIFF = INTCK('MONTH',DATEPART(PARTITION_DATE),TODAY());
	CALL SYMPUTX('DATE_DIFF',DATE_DIFF,'G');
	YEAR = COMPRESS(PUT(YEAR(DATEPART(PARTITION_DATE)),4.));
	DAY = COMPRESS(PUT(DAY(DATEPART(PARTITION_DATE)),2.));
	MONTH = COMPRESS(UPCASE(PUT(DATEPART(PARTITION_DATE),MONNAME3.)));
	IF LENGTH(DAY)=1 THEN DAY = COMPRESS(CATX('','0',DAY));
	CALL SYMPUTX('PARTITION_NAME',COMPRESS(CATX('_',MONTH,YEAR)));
	CALL SYMPUTX('DATE_USE',COMPRESS(CATX("","'",CATX('-',DAY,MONTH,YEAR),"'")));
RUN;

%PUT &DATE_USE;
%PUT %STR(&PARTITION_NAME);

/*SEE IF ITS A SUNDAY AND IF IT'S BEEN A MONTH. IF ITS A SUNDAY AND IT HAS BEEN A MONTH WE WILL MAKE A NEW PARTITION*/

%MACRO PARTITION_DECISION(RUN=,DAY=,DATE_DIFF=,PARTITION_NAME=);
	
	%IF %EVAL(&RUN. = 1 AND &DAY. = 1 AND &DATE_DIFF. >= 1) %THEN 
		%DO;
			PROC SQL;
				CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
				EXECUTE(ALTER TABLE TEMPTABLES.PARTITION_TEST
							ADD PARTITION &PARTITION_NAME. VALUES LESS THAN (&DATE_USE.)
							TABLESPACE FINOR_TBL7_INDEX
						)
				BY ORACLE;
				DISCONNECT FROM ORACLE;
			QUIT;
		%END;

%MEND;

%PARTITION_DECISION(RUN=&RUN.,DAY=&DAY.,DATE_DIFF=&DATE_DIFF.,PARTITION_NAME=&PARTITION_NAME.)


DATA TRANSACTION_PARTITION_INSERT;
	PARTITION_DATE = DATETIME();
	FORMAT PARTITION_DATE DATETIME20.;
RUN;


PROC APPEND BASE=SKY.TRANSACTION_PARTITION_MASTER DATA=TRANSACTION_PARTITION_INSERT FORCE;
RUN;