*Error Checking;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\TRANSACTION_DATAMART_DAILY\Transaction_Table_Error_Check.sas";

*Libname Statements;
%include "E:\Shared\CADA\SAS Source Code\Development\nrochester\Libname_Statements.sas";

/* ROLLUP ALL POS SYSTEMS FOR UPLOAD */
DATA    TRANDM.TRANSACTION_TABLE_UPDATE1;
	SET	/*TRANDM.TRANSACTION_TABLE_EADV_UPDATE*/
	    TRANDM.TRANSACTION_TABLE_QF1_UPDATEI
		TRANDM.TRANSACTION_TABLE_QF1_UPDATET
		TRANDM.TRANSACTION_TABLE_QF2_UPDATE
		TRANDM.TRANSACTION_TABLE_QF3_UPDATE
		TRANDM.TRANSACTION_TABLE_QF3_UPDATETT
		TRANDM.TRANSACTION_TABLE_QF4_UPDATEP
		TRANDM.TRANSACTION_TABLE_QF4_UPDATET
/*		TRANDM.TRANSACTION_TABLE_QF5_UPDATE*/
		TRANDM.TRANSACTION_TABLE_QF5_ALL
		TRANDM.TRANSACTION_TABLE_NG_UPDATE
		TRANDM.TRANSACTION_TABLE_AANET_SC;
%RUNQUIT(&job,&sub10);

/* SORT THE ROLLUP FOR UPLOADING */
PROC SORT DATA=TRANDM.TRANSACTION_TABLE_UPDATE1 NODUPKEY DUPOUT=TRANDM.DUPOUTDAILY1;
BY POS DEALNBR DEALTRANNBR POSTRANCD POSAPPLIEDCD TRANAMT;
%RUNQUIT(&job,&sub10);