/*TRUNCATE TABLES TRANSACTION*/
%INCLUDE "\\CSSSASAPP\CADA\SAS SOURCE CODE\PRODUCTION\SERVICE ACCOUNTS\SVC_SASUSER.SAS";


/*EADV*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_EADV) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF1I*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF1I) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF1T*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF1T) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF2*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF2) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF3*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF3) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF3T*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF3TT) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF4P*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF4P) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF4T*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF4T) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*QF5*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_QF5) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*NG*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_NG) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;

/*AANET*/
PROC SQL;
	CONNECT TO ORACLE(USER=&USER. PASSWORD=&PASSWORD. PATH='BIOR');
	EXECUTE(TRUNCATE TABLE SKYNET.TRAN_DATAMART_ONLINE) BY ORACLE;
	DISCONNECT FROM ORACLE;
QUIT;








